### PR TITLE
[Scheduler] LPS-88710

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang 

The current change divide two points.

1. MessageListener and Scheduler together. SchedulerEventMessageListenerServiceTrackerCustomizer take cares this.
2. MessageListener without Scheduler: SchedulerEventMessageListenerAdapterRegistrar takes care it.

I have done the below tests and they are passed:
1. New mode: *messageListener as SchedulerEventMessageListener service publish.
2. Old mode:  Test schedulerEngineHelper.register() way.
3. Test create Scheduler by manual, publish one scheduler event when publish to live.

I will test "the war development" next Tuesday.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
fixed the ci errors and run again

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Pull request closed without merging**
