### PR TITLE
LPS 136753 9 9 1

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-136753 Add value.object.finder.cache.list.threshold value to BasePersistenceImpl
- LPS-136753 Skip caching the list to entity cache when its size is larger than the threshold
- LPS-136753 Regenerate
- LPS-136753 packageinfo

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you please take a look at the test results when the tests end? Thanks!

**Comment by dantewang** [comment]
Hi @vicnate5, could you take a look at the test results? The service-builder-jdk8 failure is known and I'll handle it.
cc @tinatian

**Comment by dantewang** [comment]
@tinatian By the way, I still get OOM (gc overhead limit) when executing the ticket's scripts, but from the heap dump I don't see anything related to cache or `UncommitedBuffer`, it's just the mysql result set / hibernate persistence context being too big.

**Comment by zhangyan0701** [comment]
Hi @dantewang 

The failures are unrelated. But some integration tests were aborted.

**Pull request closed without merging**
