### PR TITLE
[Hibernate Upgrade] LPS-128873 

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please check the issue description from the last commit message.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@yuhai Please also run ci with only the websphere upgrade fix, so we can see whether we can send this separately.

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test result when it's done? Thanks!

**Comment by yuhai** [comment]
> @yuhai Please also run ci with only the websphere upgrade fix, so we can see whether we can send this separately.

@dantewang, sorry, I just saw your comment. I think we can send this separately and need to explain the issue only happens on hibernate upgrade.

**Pull request closed without merging**
