### PR TITLE
[SampleSQLBuilder] LPS-74148 Commerce

### PR DESCRIPTION
**Pull request by dantewang**
Added SF (sort and group) as per https://github.com/brianchandotcom/liferay-portal/pull/92267#issuecomment-669693821 cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:forward

**Comment by slnn** [comment]
Hi @dantewang 

CI failed about "Semantic versioning is incorrect.", it seems that no related about SampleSQLBuilder.

Lily

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:forward


Liferay Continuous Integration <notifications@github.com> 于 2020年8月8日周六
00:11写道：

**Pull request closed without merging**
