### PR TITLE
LPS 142794 2022 2 14

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-142794 Add new method to provide secure TransformerFactory
- LPS-142794 Add XXE test coverage for the new method
- LPS-142794 Apply to PortletResponseImpl
- LPS-142794 Apply to DiffHtmlImpl
- LPS-142794 Apply to XMLUtil in sharepoint-soap-repository
- LPS-142794 Apply to SampleHandler
- LPS-142794 Apply to XSLContentUtil
- LPS-142794 Apply to SPDXBuilder and XSLTBuilder (this fixes LPS-142695)
- LPS-142794 Sem Ver (without bnd.bnd changes)

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
https://issues.apache.org/jira/browse/XERCESJ-1654?focusedCommentId=17314743&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17314743

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Pull request closed without merging**
