### PR TITLE
LPS-116325 Rolling restart failed caused by MethodKey

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/ChiZeLin/liferay-portal/pull/266. [See changes here.](https://github.com/dantewang/liferay-portal/compare/31ce79f1b131~6...31ce79f1b131)

**Pull request closed without merging**
