### PR TITLE
LPS 154828 6 30

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-154828 The AtomicInteger should be a field, otherwise the limit won't work
- LPS-154828 Use computer name initialized in portal instance to remove the only usage of InetAddressUtil#getLocalHostName()
- LPS-154828 Remove unused method
- LPS-154828 Add cache to check local host name to reduce DNS resolving
- LPS-154828 Apply usages
- LPS-154828 Apply to PingbackMethodImpl and fix unit test
- LPS-154828 Inline the only usage
- LPS-154828 Add method to check if host is allowed
- LPS-154828 Employ AllowedIPAddressValidator to perform additional checking
- LPS-154828 Temp: return false when UnknownHostException in isHostAllowed() method
- LPS-154828 Apply to replace AccessControlUtil.isAccessAllowed()

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@catarineaguiar Could you check the CI results for regression? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang regressions found:

```
[exec] /opt/dev/projects/github/liferay-portal/modules/apps/blogs/blogs-service/src/test/java/com/liferay/blogs/internal/util/PingbackMethodImplTest.java:495: error: cannot find symbol
     [exec] 			_inetAddressLookup
     [exec] 			^
     [exec]   symbol:   variable _inetAddressLookup
     [exec]   location: class PingbackMethodImplTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/blogs/blogs-service/src/test/java/com/liferay/blogs/internal/util/PingbackMethodImplTest.java:505: error: cannot find symbol
     [exec] 				_inetAddressLookup
     [exec] 				^
     [exec]   symbol:   variable _inetAddressLookup
     [exec]   location: class PingbackMethodImplTest
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/blogs/blogs-service/src/test/java/com/liferay/blogs/internal/util/PingbackMethodImplTest.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-26/test-portal-acceptance-pullrequest(master)/3743/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

semver error:
```
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/60.0.0/e51eff1816462bc1b09441fb517fdfd94aa603e2/com.liferay.portal.kernel-60.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-26/test-portal-acceptance-pullrequest(master)/3743/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@catarineaguiar Force pushed. Could you check the new ci-run results? Thanks!

Please ignore the compile error in `PingbackMethodImplTest` as it's a known one which we plan to fix after upgrading to latest Mockito.

**Comment by zhangyan0701** [comment]
1. The [source-format-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1896038136) failed with below error:
```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Variable '_SERVER_IP' is unused: ./portal-kernel/src/com/liferay/portal/kernel/security/access/control/AccessControlUtil.java 80 (Checkstyle:UnusedVariableCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 12:18.974 sec]
```

2. One functional test [LocalFile.MultiFactorAuthentication#LoginWithIPBasedVerifierEnabled](https://testray.liferay.com/home/-/testray/case_results/1895943539) only failed in this PR, but I am not familiar with this feature. @JoyceWang08211 Would you mind taking a look at this test to confirm if it relates to this PR? Thanks!

**Comment by JoyceWang08211** [comment]
> 2\. LoginWithIPBasedVerifierEnabled

Hi @zhangyan0701 Please see the detailed steps of [LocalFile.MultiFactorAuthentication#LoginWithIPBasedVerifierEnabled](https://testray.liferay.com/home/-/testray/case_results/1895943539) here: https://issues.liferay.com/browse/LRQA-59248. Hope that it could be helpful.

**Pull request closed without merging**
