### PR TITLE
LPS-105126

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the issue was caused by the commit cbb83b05a86cf9d5788925971ea2582050e1b9d8.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1618.

**Pull request closed without merging**
