### PR TITLE
LPS-118542 test

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I use portal-log4j-ext.xml and portal-impl/**/portal-log4j.xml as test config files.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang. I just resolve the ci:test error and rerun ci:test:relevant

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Pull request closed without merging**
