### PR TITLE
LPS 149473 Replace powermock with Mockito in portal-impl and portal-kernel

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

Main Task: LPS-84905 Remove Mockito and PowerMockito
Sub Task: LPS 149473 Replace powermock with Mockito in portal-impl and portal-kernel

Thanks for checking!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/490

**Pull request closed without merging**
