### PR TITLE
LPS X hypersonic

### PR DESCRIPTION
**Pull request by dantewang**
Running CI tests to see if it impacts any test. cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:depot

**Comment by dantewang** [comment]
ci:test:depot

**Comment by dantewang** [comment]
ci:test:depot

**Comment by dantewang** [comment]
ci:test:depot

**Comment by dantewang** [comment]
ci:test:depot

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:backend-hypersonic

**Comment by zhangyan0701** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/4103

**Pull request closed without merging**
