### PR TITLE
LPS-125170 BackgroundTask queue resume refactoring

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, during testIntegration, SynchronousDestinationTestRule changed ParallelDestination(destinationName=liferay/background_task) for synchronousDestination.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/238. [See changes here.](https://github.com/dantewang/liferay-portal/compare/929ea974f6d1~7...929ea974f6d1)

**Pull request closed without merging**
