### PR TITLE
vsingleton/tck3-ci

### PR DESCRIPTION
**Pull request by vsingleton**
uses google chrome in CI

### CODE REVIEW

**Comment by vsingleton** [comment]
ci:test:tck

**Comment by vsingleton** [comment]
um, why did the tck job not run?

**Comment by vsingleton** [comment]
ci:test:tck

**Comment by vsingleton** [comment]
@michaelhashimoto why did the portlet3 tck job not run above?

**Comment by vsingleton** [comment]
ci:test:tck

**Comment by vsingleton** [comment]
ci:test:tck

**Comment by michaelhashimoto** [comment]
ci:test:tck

**Comment by vsingleton** [comment]
ci:test:tck

**Comment by vsingleton** [comment]
ci:test:tck

**Pull request closed without merging**
