### PR TITLE
TCK3-CI 3-1

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:retest

**Comment by dantewang** [comment]
ci:test:0ab69a797c41c8b4e3e65963fb43e957e607de65

**Comment by vsingleton** [comment]
portlet-tck_3.0/driver/src/main/java/javax/portlet/tck/driver/TCKSimpleTestDriver.java
-   @Parameters
+   @Parameters (name = “{1}“)

Please let me know if this helps.

**Pull request closed without merging**
