### PR TITLE
 [Bug fix] LPS-129172 Upgrade jackson

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the requirement from https://github.com/tinatian/liferay-portal/pull/2341#pullrequestreview-729274252. I add the last two commits.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2356

**Pull request closed without merging**
