### PR TITLE
LPS-87327

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang

I do the fix in UI part. 

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Could you record a gif of your change and upload to the ticket? You can get a QA to help.

**Comment by yuhai** [comment]
Hi @dantewang 

Done. Please refer to https://issues.liferay.com/browse/LPS-87327?focusedCommentId=1631765&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1631765

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1124. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
