### PR TITLE
LPS-X hibernate 12 21

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/dantewang/liferay-portal/pull/2126. Remove the previous LPS-134886 fix.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@zhangyan0701, could you please help check the current test errors if they are related with the pr?

**Comment by zhangyan0701** [comment]
There is an error in [semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1593442027) that seems related:
```
     [exec] [Baseline Warning] Bundle Version Change Recommended: 19.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/18.0.1/6da7b575dcaa1547b2ffc0b9fdc664fe0b850ce7/com.liferay.portal.impl-18.0.1.jar
```
Full Jenkins console:
https://testray.liferay.com/reports/production/logs/2021-12/test-1-33/test-portal-acceptance-pullrequest(master)/738/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz

No other related failures found.

**Comment by zhangyan0701** [comment]
There are some failures seem related to this PR:

1. There is an error in test [semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1593442027):
```
     [exec] [Baseline Warning] Bundle Version Change Recommended: 19.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/18.0.1/6da7b575dcaa1547b2ffc0b9fdc664fe0b850ce7/com.liferay.portal.impl-18.0.1.jar
```
Full Jenkins console:
https://testray.liferay.com/reports/production/logs/2021-12/test-1-33/test-portal-acceptance-pullrequest(master)/738/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz

2. NPE error thrown when startup portal with PostgreSQL:
```
 [parallel] 2021-12-22 07:30:34.554 INFO  [main][DialectDetector:154] Using dialect org.hibernate.dialect.PostgreSQL10Dialect for PostgreSQL 13.4
 [parallel] 2021-12-22 07:30:34.563 ERROR [main][PortalContextLoaderListener:69] java.lang.NullPointerException
 [parallel] java.lang.NullPointerException: null
```
This happens on both PostgreSQL 12.1 and 13.4.
Example failed test: [LocalFile.PortalSmoke#Smoke](https://testray.liferay.com/home/-/testray/case_results/1593441691)

3. Failed upgrade process for module com.liferay.layout.page.template.service on DB2, Oracle and SQLServer:
``` 
     [java] 2021-12-22 07:58:58.764 INFO  [Portal Dependency Manager Component Executor--2][UpgradeProcess:134] Failed upgrade process com.liferay.layout.page.template.internal.upgrade.v1_1_0.LayoutPrototypeUpgradeProcess in 276 ms
     [java] 2021-12-22 07:58:58.774 ERROR [Portal Dependency Manager Component Executor--2][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.layout.page.template.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute query
```
DB2 Example: [LocalFile.DroolsUpgrade#ViewDroolsInAppManagerAfterUpgrade70106](https://testray.liferay.com/home/-/testray/case_results/1593445049)
Oracle Example: [LocalFile.DroolsUpgrade#ViewDroolsInAppManagerAfterUpgrade621021](https://testray.liferay.com/home/-/testray/case_results/1593441770)
SQLServer Example: [LocalFile.DroolsUpgrade#ViewDroolsInAppManagerAfterUpgrade7110](https://testray.liferay.com/home/-/testray/case_results/1593445178)

4. Web Content portlet is unavailable on SQLServer, and error in console:
`2021-12-22 07:41:13.132 ERROR [http-nio-8080-exec-6][PortletRequestDispatcherImpl:304] Unable to dispatch request: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.RuntimeException: Failed to parse sql for (  SELECT DIST top(?)INCT folderId AS modelFolderId, '' AS articleId, JournalFolder.name AS title, 0 AS version, 1 AS modelFolder, JournalFolder.createDate AS displayDate, JournalFolder.modifiedDate AS modifiedDate FROM JournalFolder WHERE (JournalFolder.groupId = ?) AND (JournalFolder.status != ?)  AND JournalFolder.parentFolderId = ?    ) UNION ALL (  SELECT JournalArticle.folderId AS modelFolderId, JournalArticle.articleId AS articleId, JournalArticleLocalization.title AS title, JournalArticle.version AS version, 0 AS modelFolder, JournalArticle.displayDate AS displayDate, JournalArticle.modifiedDate AS modifiedDate FROM (SELECT JournalArticle.groupId AS groupId, JournalArticle.articleId AS articleId, MAX(JournalArticle.version) AS version FROM JournalArticle WHERE (JournalArticle.groupId = ?) AND (JournalArticle.classNameId = 0) AND (  (JournalArticle.status != ?))  AND JournalArticle.folderId = ?  GROUP BY JournalArticle.groupId, JournalArticle.folderId, JournalArticle.articleId) TEMP_TABLE INNER JOIN JournalArticle ON (TEMP_TABLE.groupId = JournalArticle.groupId) AND (TEMP_TABLE.articleId = JournalArticle.articleId) AND (TEMP_TABLE.version = JournalArticle.version) LEFT JOIN JournalArticleLocalization ON (JournalArticle.id_ = JournalArticleLocalization.articlePK) AND (JournalArticleLocalization.languageId = ?)   ) ORDER BY modelFolder DESC, modifiedDate DESC`

Example test: [LocalFile.PortalSmoke#Smoke](https://testray.liferay.com/home/-/testray/case_results/1593441769)

**Comment by yuhai** [comment]
@zhangyan0701 thanks for your check.
@dantewang, 
failure 2 should be not related with the fix. Spring inject issue.
failure 3 the error as the following, we didn't change LayoutPrototype related data column.
```  
[java] Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][t4][1092][11644][4.24.92] Invalid data conversion: Wrong result column type for requested conversion. ERRORCODE=-4461, SQLSTATE=42815
     [java] 	at com.ibm.db2.jcc.am.b6.a(b6.java:810) ~[db2jcc4.jar:?]
     [java] 	at com.ibm.db2.jcc.am.b6.a(b6.java:66) ~[db2jcc4.jar:?]
     [java] 	at com.ibm.db2.jcc.am.b6.a(b6.java:133) ~[db2jcc4.jar:?]
     [java] 	at com.ibm.db2.jcc.am.bh.W(bh.java:2197) ~[db2jcc4.jar:?]
     [java] 	at com.ibm.db2.jcc.am.ResultSet.getClob(ResultSet.java:1429) ~[db2jcc4.jar:?]
     [java] 	at com.ibm.db2.jcc.am.ResultSet.getClob(ResultSet.java:1878) ~[db2jcc4.jar:?]
     [java] 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getClob(HikariProxyResultSet.java) ~[hikaricp.jar:?]
     [java] 	at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3212) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1874) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.hydrateEntityState(Loader.java:1798) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1771) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.getRow(Loader.java:1623) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:747) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1046) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.processResultSet(Loader.java:997) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.doQuery(Loader.java:966) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:356) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.doList(Loader.java:2855) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.doList(Loader.java:2837) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2669) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.loader.Loader.list(Loader.java:2664) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.hql.internal.classic.QueryTranslatorImpl.list(QueryTranslatorImpl.java:1037) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1443) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617) ~[hibernate-core.jar:5.5.3.Final]
     [java] 	at com.liferay.portal.dao.orm.hibernate.QueryImpl.list(QueryImpl.java:112) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.dao.orm.hibernate.QueryImpl.list(QueryImpl.java:104) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:61) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:53) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.service.persistence.impl.LayoutPrototypePersistenceImpl.findAll(LayoutPrototypePersistenceImpl.java:4365) ~[portal-impl.jar:?]
``` 
failure 4, the error as the following, it seems unrelated with the pr.
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
     [exec]     at line 1, column 19.
     [exec] 
     [exec] Was expecting one of:
     [exec] 
     [exec]     ")"
     [exec]     ","
     [exec]     "CONNECT"
     [exec]     "EXCEPT"
     [exec]     "FOR"
     [exec]     "FROM"
     [exec]     "GROUP"
     [exec]     "HAVING"
     [exec]     "INTERSECT"
     [exec]     "INTO"
     [exec]     "MINUS"
     [exec]     "ORDER"
     [exec]     "START"
     [exec]     "UNION"
     [exec]     "WHERE"
     [exec]     "WINDOW"
```
I will execute ci:test again. If the above issue still happens, I will check them.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@zhangyan0701, could you please help check if the previous [errors](https://github.com/dantewang/liferay-portal/pull/2131#issuecomment-1000255675) still exist?

**Comment by zhangyan0701** [comment]
Hi @yuhai 

The above four issues also happen on the most recently test jobs.

1.  [semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1594094218).
2.  NPE error thrown when startup portal with PostgreSQL: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1594113754&testrayRunId=1594114136
3. Failed upgrade process for module com.liferay.layout.page.template.service on DB2, Oracle and SQLServer: https://testray.liferay.com/home/-/testray/case_results/1594114263
4. Web Content portlet is unavailable on SQLServer, and error in console: https://testray.liferay.com/home/-/testray/case_results/1594116561

**Pull request closed without merging**
