### PR TITLE
LPS-105095 sp_dropkey primary doesn't work on Sybase 16.0

### PR DESCRIPTION
**Pull request by yuhai**
Reference: https://stackoverflow.com/questions/37977018/sybase-drop-primary-key

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1616.

**Pull request closed without merging**
