### PR TITLE
LPS-X Always check resources during startup

### PR DESCRIPTION
**Pull request by dantewang**
@slnn FYI, this pull attempts to always check resource actions during portal startup, so you don't need to make them in SampleSQLBuilder.

@zhangyan0701 Could you check CI results later? I'll run several different batches.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@slnn @GinsonRen could you test startup performance for this pull? Thanks!

**Comment by slnn** [comment]
I have updated startup performance test results in our daily startup performance monitor google doc

**Comment by dantewang** [comment]
Formal branch: https://github.com/dantewang/liferay-portal/pull/1793

**Pull request closed without merging**
