### PR TITLE
[DS-migration] LPS-98936 portal-security-wedeploy-auth-service

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/827. [See changes here.](https://github.com/dantewang/liferay-portal/compare/76919f8b7e42~1...76919f8b7e42)

**Pull request closed without merging**
