### PR TITLE
LPS-161990 Fix on MimeTypesImpl

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-161990 Satisfy Portlet Specification and Servlet Specification: when detected content type is application/octet-stream, but the extension is not known by Tika, return null
- LPS-161990 Add shortcut, always use Tika result when inputstream is provided
- LPS-161990 SF, rename variable; the key for this map should be file extension name, not mime type
- LPS-161990 Add test

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
```
     [exec]    after class.
     [exec] Tests run: 4405, Failures: 0, Errors: 0, Skipped: 9, Time elapsed: 279.693 sec - in javax.portlet.tck.driver.TCKLiferayTestDriver
     [exec] 
     [exec] Results :
     [exec] 
     [exec] Tests run: 4405, Failures: 0, Errors: 0, Skipped: 9
```

**Comment by zhangyan0701** [comment]
No related failures.

The tck test in LPS-161990 passed.

**Pull request closed without merging**
