### PR TITLE
LPS-125348 Increase the length of DDMFiled's InstanceId

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/520.

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2089.

**Pull request closed without merging**
