### PR TITLE
Master lps 113497 11 26

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
Hi @dantewang 

Here are the changes that make SampleSQLBuilder to generate the homepage with content page type, I also change the way SampleSQLBuilder generate the journal article with content page to avoid using different ways to generate the content page data.

cc @tinatian 

Lily

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@slnn Got conflict when rebasing to latest master, please rebase.

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1826

**Pull request closed without merging**
