### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I will run ci:test to check baseline related test.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by yuhai** [comment]
@dantewang, no baseline issue exists.

**Comment by dantewang** [comment]
https://github.com/dantewang/liferay-portal/pull/1721

**Pull request closed without merging**
