### PR TITLE
LPS-120256

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/231. [See changes here.](https://github.com/dantewang/liferay-portal/compare/12f6c565db05~2...12f6c565db05)

**Pull request closed without merging**
