### PR TITLE
LPS-98626

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1460. [See changes here.](https://github.com/dantewang/liferay-portal/compare/8a813f003bf9~2...8a813f003bf9)

**Pull request closed without merging**
