### PR TITLE
LPS-122653

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@GinsonRen Please run performance test on this pull, thanks!

**Comment by GinsonRen** [comment]
@dantewang Here is the result:

LOGIN:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 37e768bf | 38669 | 264 | 78.3 | -
PR-1791 | - | 38543 | 262 | 77.5 | -0.33%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 37e768bf | 52267 | 797 | 234 | -
PR-1791 | - | 52428 | 815 | 243 | 0.31%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 37e768bf | 16288 | 276 | 265 | -
PR-1791 | - | 16557 | 101 | 138 | 1.65%

BLOG:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 37e768bf | 14179 | 45.5 | 123 | -
PR-1791 | - | 14178 | 44.8 | 119 | -0.01%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 37e768bf | 25125 | 223 | 288 | -
PR-1791 | - | 24978 | 225 | 286 | -0.59%

WIKI:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 37e768bf | 14211 | 246 | 570 | -
PR-1791 | - | 13981 | 266 | 648 | -1.62%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 37e768bf | 20039 | 344 | 179 | -
PR-1791 | - | 19644 | 346 | 183 | -1.97%

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2032.

**Pull request closed without merging**
