### PR TITLE
LPS-96692

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, we can't use the package name "com.liferay.counter.service.test" due to SF limition. 
Please refer to [JavaSourceProcessor._getPortalJavaFiles()](https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/JavaSourceProcessor.java#L168-L211)

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by yuhai** [comment]
@dantewang,  the fix wasn't compatible when the bundle used other databases (for example, mysql). I will close it.

**Pull request closed without merging**
