### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I append one commit to solve the previous issue.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1975. [See changes here.](https://github.com/dantewang/liferay-portal/compare/e4d5289b4070~3...e4d5289b4070)

**Pull request closed without merging**
