### PR TITLE
LPS 89470 pr2

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang ,
Resend.
I deleted the changes in portal fabric and intraband tests.

Thanks for checking.

Janis.

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Please resolve the conflict on portal-test/bnd.bnd (I recommend that you rollback the change in this PR, and run `ant clean deploy` in portal-test or `ant all` in portal source root to regenerate the version bump. You can force push after re-committing.

**Comment by JanisZhang** [comment]
Hi @dantewang,

Conflict have been resolved, thanks

**Comment by dantewang** [comment]
@JanisZhang It seems I can't pull this PR using `gh`. Please resend and force push. It's `portal-test/bnd.bnd` again. Thanks!

**Comment by JanisZhang** [comment]
Hi @dantewang ,

Conflict have been resolved.

Thanks

**Comment by JanisZhang** [comment]
Hi @dantewang,

rebased and dropped commit of semantic versioning. Thanks!

**Pull request closed without merging**
