### PR TITLE
COMMERCE-1079 Extract service jars during deploy as benchmark project…

### PR DESCRIPTION
**Pull request by slnn**
… need these sql templates in these service jars

### CODE REVIEW

**Comment by slnn** [comment]
The changes of benchmark project is https://github.com/dantewang/liferay-benchmark-ee/pull/360

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@ChiZeLin Let's look into this and simplify the logic when having time. Basically Gradle is a project management & build tool built upon its own DSL on top of Groovy. There should be simpler ways to extract a file from a dependency.

**Comment by tinatian** [comment]
Hi @dantewang ,
Why not use "compileInclude"? what we need is the original jar, right? "compileInclude" will copy the jar into lib folder.

Tina.

**Comment by slnn** [comment]
Hi @tinatian 
What do you mean by compileInclude" will copy the jar into lib folder? 

After COMMERCE-1079, when deploy the SampleSQLBuilder, I can see these service jars be download edin ${portal-source-root}/.gradle/caches/

Dante's aim is to find a more simple gradle way  to find these jars in ${portal-source-root}/.gradle/caches directory.

The origin aim is to find these service jars and extract them to get the file path of these *.sql files in these jars, please see the property portal.module.dir.list in benchmark project, all-database need it to create all the DB tables before insert the data that generated by SampleSQLBuilder, however after COMMERCE-1079, even though we do not set any commerce related properties in the SampleSQLBuilder properties, SampleSQLBuilder still generated part data about commerce, so it will fail the inset task in benchmark project as we do not create these commerce DB table before insert data into it.

The origin solution is do the extract in benchmark side:
https://github.com/dantewang/liferay-benchmark-ee/pull/358


Lily

**Comment by tinatian** [comment]
Use `compileInclude group: "com.liferay.commerce", name: "com.liferay.commerce.currency.api", version: "2.0.0"`
instead of
`compile group: "com.liferay.commerce", name: "com.liferay.commerce.currency.api", version: "2.0.0"`

Tina

**Comment by dantewang** [comment]
@tinatian Thanks! Didn't realize `compileInclude` will copy the file.

@slnn Closing this pull. Please simplify and resend.

**Comment by slnn** [comment]
Recend it in https://github.com/dantewang/liferay-portal/pull/1393

**Pull request closed without merging**
