### PR TITLE
[DS-migration] LPS-99329 segments-service | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
@ChiZeLin Conflict with upstream, please resend.

**Pull request closed without merging**
