### PR TITLE
LPS-120666 Remove unused c3p0 dependency from portal-tools-sample-sql-builder

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1970.

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
