### PR TITLE
LPS-75917 Set cookies before the response has been flushed or committed during the resource phase

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:stop

**Comment by ChiZelin** [comment]
ci:retest

**Comment by dantewang** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/5251. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
