### PR TITLE
LPS-111744 Remove intraband

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please refer to ci:test result from https://github.com/yuhai/liferay-portal/pull/212. It had a baseline error and I have solved it in this pr.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1780.

**Pull request closed without merging**
