### PR TITLE
ResourceAction-0706

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please check ci:test result from https://github.com/yuhai/liferay-portal/pull/221. It looks good.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1654. [See changes here.](https://github.com/dantewang/liferay-portal/compare/1dd1150838f1~1...1dd1150838f1)

**Pull request closed without merging**
