### PR TITLE
LPS-98028

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1202.

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1445.

**Pull request closed without merging**
