### PR TITLE
[Deprecation] LPS-106564 util-taglib

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please check the ci:test result from https://github.com/yuhai/liferay-portal/pull/203. 
I check modules-unit-jdk8, modules-integration-mysql57-jdk8 and modules-compile-jdk8. These errors aren't related with the fix.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1676.

**Pull request closed without merging**
