### PR TITLE
Lps 119985 part 1 9 18

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@slnn Could you try to see if it's possible to simplify this part by:

1. Move `<include>` of asset.ftl into group.ftl -- so avoid creating array of maps/lists and using their index as group id; instead, assign real group id to each model.
2. Record IDs in the data factory when `new*Model()` methods of asset are called, so that you can avoid adding the `*maps` parameters to the macros.

**Pull request closed without merging**
