### PR TITLE
LPS 159586 8 3

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-159586 Enable dependency-injector="ds"
- LPS-159586 Enable "-dsannotations-options: inherit"
- LPS-159586 gw buildService
- LPS-159586 Convert spring beans to scr components
- LPS-159586 Add references since they are removed from the base class during regenerate (gw buildService)
- LPS-159586 Break circular dependency between CommercePriceEntryLocalServiceImpl and CommercePriceListLocalServiceImpl by calling persistence directly
- LPS-159586 Break circular dependency between various services and CommercePriceListLocalServiceImpl by extracting logic in a separate component and letting everyone depending on it
- LPS-159586 SF, centralize MultiVMPool usage to the new component
- LPS-159586 Break circular dependency between CommercePriceEntryLocalServiceImpl and CommerceTierPriceEntryLocalServiceImpl by extracting logic to a util and letting everyone use it
- LPS-159586 SF, delegate
- LPS-159586 SF, use reference as Source Formatter requested

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the commerce test results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
