### PR TITLE
LPS-76257 Auto build service

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/5401. [See changes here.](https://github.com/dantewang/liferay-portal/compare/d1c9fdcd562a~1...d1c9fdcd562a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
