### PR TITLE
LPD 41245 ehcache3

### PR DESCRIPTION
**Pull request by dantewang**
- **LPD-X Create portal-cache-ehcache3-impl**
- **LPD-X Adapt EhcachePortalCache. Use <Object, Object> to avoid massively change our current APIs. In Ehcache 3, TTL needs to be handled by a custom ExpiryPolicy, will implement it later.**
- **LPD-X Adapt bridge listeners**
- **LPD-41245 Adapt managers**
- **LPD-41245 Adapt EhcachePortalCacheConfiguration**
- **LPD-41245 Add EhcachePortalCacheManagerConfiguration and apply (configurator imcomplete)**
- **LPD-41245 Finish lazy cache creation**
- **LPD-41245 PortalCacheManagerEventListener: implement status transition, call init() and dispose(); sf and rename**
- **LPD-41245 Should init**
- **LPD-41245 Class loader**
- **LPD-41245 Adapt management**
- **LPD-41245 Migrate liferay-single-vm.xml**
- **LPD-41245 Migrate liferay-multi-vm.xml**
- **LPD-41245 Migrate module-log4j.xml**
- **LPD-41245 Only override default template when exists**
- **TEMP not applied: Infra for per-value TTL support**
- **LPD-41245 Adapt cache listener handling. Due to Ehcache 3 changes, it's impossible to manipulate CacheEventListener declared in the ehcache xml configuration file.**
- **LPD-41245 Tests, not finished**
- **LPD-41245 Auto SF**
- **LPD-41245 Manual SF**
- **LPD-41245 Auto SF**
- **LPD-41245 SF**
- **LPD-41245 Test: remove "removeAll" assertion. Ehcache 3 cache clear does not fire any event.**
- **LPD-41245 Register a "execute-on-caller" ExecutorService for Ehcache3's event dispatching to keep the thread-local based replication control working.**
- **LPD-41245 Test: coverage**
- **LPD-41245 No longer need this dependency**
- **LPD-41245 Fix template**
- **LPD-41245 Properly implement MBeans**
- **LPD-41245 Handle default portal cache configuration**
- **LPD-41245 Migrate module-multi-vm.xml and module-single-vm.xml**
- **LPD-41245 Update bnd.bnd**
- **LPD-41245 Suppress logs**
- **LPD-41245 Remove unused files**
- **LPD-41245 temp: ignore this test, will fix later.**
- **LPD-41245 build ehcache3 by default**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:76607451

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:report:77452276

**Comment by dantewang** [comment]
ci:report:77473149

**Comment by dantewang** [comment]
@victorhcunha Please run a login comparison for this PR, thanks!
@JerryAdrianoo Please run a startup comparison for this PR, thanks!

This PR still has some issues to fix, but it should be able to go through the performance tests. If you see any error in the tests on this PR, please let me know.

cc @slnn

**Comment by victorhcunha** [comment]
Hi @dantewang !
Here are the results for login compare:


Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | d1f383eb | 14,152 | - | 309 | 3,2,1 | 0,0,0 | 94,95,94
PR | - | 13,874 | -1.96% | 292 | 2,2,1 | 0,0,0 | 94,96,95

More details you can see [here](https://docs.google.com/spreadsheets/d/1mhbYTDaFgznv6s_Z4kbagQTFK8PJdYh_1MyoBssg1Bc/edit?gid=0#gid=0).
If you want, I can do more rounds to get more stable results.

**Comment by JerryAdrianoo** [comment]
Hey @dantewang, see the results below:

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-41245 | **41,674** | | 15,783 | | | **2,415** | 1,888
|  | | | 16,474 | | | | 1,919
|  | | | 16,295 | | | | 1,951
 | | | | 16,102 | | | | 1,872
 | | | | 16,290|**16,229** | | | 1,888 | **1,898**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-41245 | **42,030** | | 16,771 | | | **2,433** | 1,901
|  | | | 17,300 | | | | 1,994
|  | | | 16,086 | | | | 1,857
|  | | | 16,229 | | | | 1,961
| | |  0.85% | 16,290 |**16,430** |  **1.24%** | | 1,920 | **1,927**

If you look in the [spreadsheet](https://docs.google.com/spreadsheets/d/1WWrbkHtSZennXPrWAXoQs5gyHh1LeS8ck8haFAeXies/edit?usp=sharing), you'll see an improvement in the SQL numbers related. However, I noticed the hot startup was increased by 200ms, which I guess is not associated with your changes.

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
Thank you very much @victorhcunha @JerryAdrianoo! I'm still making changes to this PR so I may need more runs later. Will let you know when it's needed.

**Comment by dantewang** [comment]
ci:report:79824670

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:report:81511232

**Pull request closed without merging**
