### PR TITLE
Lps 74513

### PR DESCRIPTION
**Pull request by shuyangzhou**
Can you try on this solution? Also make sure you test it on windows. let me know the result, thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
@shuyangzhou Got it.

**Comment by shuyangzhou** [comment]
@dantewang sorry, that did not work, I changed to a different way, please try on the latest change. And send me an email for that. I will catch it up tomorrow morning.

**Comment by dantewang** [comment]
@shuyangzhou Sure got it. We're just about to build it.

**Comment by dantewang** [comment]
ci:retest

**Pull request closed without merging**
