### PR TITLE
LPS-116325 ClassLoaderPool

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1899. [See changes here.](https://github.com/dantewang/liferay-portal/compare/7b365bbe7b7f~4...7b365bbe7b7f)

**Pull request closed without merging**
