### PR TITLE
Lps 127055 3 3

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang 

Changes that make SampleSQLBuilder support multiple companies.

/cc @tinatian

Regards
Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@slnn This pull contains some changes in the previous pulls to prepare for DataFactory split, right? If these changes are necessary for the multiple company support, please make these changes using the previous ticket id first, and then the company changes.

**Comment by slnn** [comment]
> @slnn This pull contains some changes in the previous pulls to prepare for DataFactory split, right? If these changes are necessary for the multiple company support, please make these changes using the previous ticket id first, and then the company changes.

Hi @dantewang 

Yes, the AP changes are necessary for the multiple company support, and also needed  by the previous prepare for DataFactory split, but it is not all the changes of AP, how about we do this first and then do the DataFactory split with the previous ticket id?

**Comment by dantewang** [comment]
@slnn It makes this pull big and harder for review. Please try to send the AP changes first, as a dependency of this pull.

cc @tinatian

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Please see:
Part 1: https://github.com/dantewang/liferay-portal/pull/1925
Part 2: https://github.com/dantewang/liferay-portal/pull/1926

**Pull request closed without merging**
