### PR TITLE
LPS-96692 Properly get path from URL

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
ci:test:backend-hypersonic


Liferay Continuous Integration <notifications@github.com> 于 2019年8月5日周一
21:00写道：

**Comment by yuhai** [comment]
ci:test:backend-hypersonic

**Pull request closed without merging**
