### PR TITLE
LPS X Hibernate 7 2 2

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, the pr rebases on https://github.com/dantewang/liferay-portal/pull/2020 (also rebases on the latest master). This is just update. I did temp fix to resolve the StagedExpandoTableStagedModelDataHandlerTest error. I tried to let hibernate can recognize StagedExpandoTableImpl as entity, but I didn't find one good way yet.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Pull request closed without merging**
