### PR TITLE
LPS-109690 Apply petra StringBundler to SampleSQLBuilder directly since it is not be exported

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by slnn** [comment]
This pull worked well with benchmark context.

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85878.

**Pull request closed without merging**
