### PR TITLE
LPS-X Why reflect it when there's getter method for the field?

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
Looks like there were issues on CI yesterday, I triggered echo test suite in https://github.com/zhangyan0701/liferay-portal/pull/472 and checked the results there. 

No related issues found.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Pull request closed without merging**
