### PR TITLE
Verify test 3

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, for https://github.com/dantewang/liferay-portal/pull/1055 test error. I append one addition commit to solve BlogsTrackbacksVerifyProcessTest.testVerify() error. For DLFileEntryMetadataLocalServiceTest and DLServiceVerifyProcessTest error, it looks like Elasticsearch existed issues and they are not related with the fix.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Last commit sent separately: https://github.com/tinatian/liferay-portal/pull/1290

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Rebased in https://github.com/dantewang/liferay-portal/pull/1065

**Pull request closed without merging**
