### PR TITLE
LPS 96118 Replace proxy creation in portal-impl ,portal-kernel and portal-test

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

I filtered and replaced the proxy creation method in portal-impl, portal-kernel, and portal-test. Thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Looks good. I'll wait for more changes from modules to determine whether we send it together or separated since this one is very small.

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test result? Thanks!

**Comment by zhangyan0701** [comment]
Hi @dantewang 

No regressions found in this pull.

**Comment by JanisZhang** [comment]
Hi @dantewang,
This is all the changes and I didn't apply the following situations:

1. Lots of newInstance usages (75%) are called when **activating components**.
2. new instance depends on the parameter provided, it will **generate different interface classes** each time.
3. wrapper, test class

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @dantewang，

Add previously ignored classes, simple change. Thanks！

**Comment by dantewang** [comment]
Please resend based on locations, thanks!

**Pull request closed without merging**
