### PR TITLE
[SD-migration] LPS-99261 portal-security-service-access-policy-service

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
@ChiZelin Please replace usage of ConfigurationProvider with OSGi component configuration (see Preston's change b4ef559d5cb8de2bc0b85e6e79c4938370b71209)

**Pull request closed without merging**
