### PR TITLE
LPS-89497

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/208. [See changes here.](https://github.com/dantewang/liferay-portal/compare/d62f3b0a4711~4...d62f3b0a4711)

**Pull request closed without merging**
