### PR TITLE
LPS-91267 inline part 1+2

### PR DESCRIPTION
**Pull request by dantewang**
cc @slnn Could you run a login test for this PR? Thanks.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by slnn** [comment]
Here are test results on Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | a9a858c | 15859 | 260 | 64.1
PR | - | 16344 | 244 | 58.6

**Pull request closed without merging**
