### PR TITLE
LPS-99548

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1271. [See changes here.](https://github.com/dantewang/liferay-portal/compare/2d65d8a00201~1...2d65d8a00201)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1483. [See changes here.](https://github.com/dantewang/liferay-portal/compare/2d65d8a00201~1...2d65d8a00201)

**Pull request closed without merging**
