### PR TITLE
LPS-98271

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, you might see the test errors about KBArticleStagedModelDataHandlerTest as https://github.com/dantewang/liferay-portal/pull/1209. But it is not related with the fix, please refer to https://github.com/yuhai/liferay-portal/pull/148.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/810.

**Pull request closed without merging**
