### PR TITLE
LPS-144149 https://github.com/liferay-core-infra/liferay-portal/pull/6129/commits/325c39b9977750c7cc49fa8dba0ec8d0f0ce12a4

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:jdk11

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:jdk11

**Comment by zhangyan0701** [comment]
Hi @dantewang I didn't see any regressions here.

**Comment by dantewang** [comment]
cc @rafaprax It passed again here.

**Pull request closed without merging**
