### PR TITLE
LPS-84181 Apply petra StringBundler | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1531. [See changes here.](https://github.com/dantewang/liferay-portal/compare/d0bce8828e73~1...d0bce8828e73)

**Pull request closed without merging**
