### PR TITLE
LPS-103549 Clean up unused deprecations from modules A~D

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Hi @vicnate5, just noticed that the compiling error of class `LicenseManager` in `portal-license-jdk8` was caused by a sub-task of LPS-103156. Since we will eventually remove deprecated things anyway, could you inform people who owns that to update their code to avoid using deprecated classes/methods?

```
build-common-java.compile:
    [javac] Compiling 13 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/license/LicenseManager.java:27: error: cannot find symbol
    [javac] import com.liferay.portal.kernel.io.Base64InputStream;
    [javac]                                    ^
    [javac]   symbol:   class Base64InputStream
    [javac]   location: package com.liferay.portal.kernel.io
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/license/LicenseManager.java:28: error: cannot find symbol
    [javac] import com.liferay.portal.kernel.io.Base64OutputStream;
    [javac]                                    ^
    [javac]   symbol:   class Base64OutputStream
    [javac]   location: package com.liferay.portal.kernel.io
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/license/LicenseManager.java:499: error: cannot find symbol
    [javac] 				new Base64OutputStream(fileOutputStream));
    [javac] 				    ^
    [javac]   symbol:   class Base64OutputStream
    [javac]   location: class LicenseManager
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/license/LicenseManager.java:706: error: cannot find symbol
    [javac] 					new Base64InputStream(fileInputStream));
    [javac] 					    ^
    [javac]   symbol:   class Base64InputStream
    [javac]   location: class LicenseManager
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 errors
[stopwatch] [run.batch.test.action: 7:01.915 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build.xml:129: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release.xml:742: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/ext/7.2.x/build-release-license.xml:5: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:51: Compile failed; see the compiler error output for details.
      [get] Getting: http://test-1-19/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/330159//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20191023092945340.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20191023092945340.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null204202577.properties
```

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/8429. [See changes here.](https://github.com/dantewang/liferay-portal/compare/159d7898a211~3...159d7898a211)

**Comment by vicnate5** [comment]
@dantewang Yes. here is the ticket: https://issues.liferay.com/browse/LPS-103493. Core team is likely taking some ownership of this code in the future so we can prevent this.

**Comment by dantewang** [comment]
Thanks @vicnate5!

Victor Ware <notifications@github.com> 于 2019年10月24日周四 23:41写道：

**Pull request closed without merging**
