### PR TITLE
LPS-114098

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yxingwu The Semantic Versioning failure seems unqiue. Could you double check?

**Comment by yxingwu** [comment]
ci:retest:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1840.

**Pull request closed without merging**
