### PR TITLE
LPS-103019 Use ServiceProxyFactory.newServiceTrackedInstance in Spring managed utils, document-library-spring.xml

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
There is a failure that I am not sure if related, but I only see it in this pr and failed twice in ci:test:default:
In test com.liferay.document.library.repository.capabilities.test.LiferayVersioningCapabilityTest > testLimitsTheNumberOfVersionsPerFileEntry, there is a warning message:
`    [exec] 04:38:06,808 WARN  [com.liferay.document.library.test-executor-thread][FileImpl:466] Unable to extract text from oxHOHdNg
     [exec] org.apache.tika.exception.TikaException: TIKA-198: Illegal IOException from org.apache.tika.parser.executable.ExecutableParser@51d12517`
Can you take a look?

**Comment by zhangyan0701** [comment]
No other related failures.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 I ran the test locally but didn't get such error. Running ci-test again to see if it happens again.

**Comment by zhangyan0701** [comment]
@dantewang , I checked the new result, the warning message was not thrown, looks like it is a flaky of Jenkins.

**Pull request closed without merging**
