### PR TITLE
Lps 113497 4 28

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@slnn Just to confirm: this pull still contains some json files. Are these json only dumped from database (not existing in portal source code)?

**Comment by slnn** [comment]
Hi @dantewang @tinatian 

How about this pull?

I have double-checked portal how to generate these *_editValue.json data during startup.
From the FragmentEntryLinkLocalServiceImpl, 
https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-service/src/main/java/com/liferay/fragment/service/impl/FragmentEntryLinkLocalServiceImpl.java#L171

Portal used these ***FragmentEntryProcessor's getDefaultEditableValuesJSONObject(String html, String configuration)** to  generate these *_editValue.json data for FragmentEntryLinkeModel during startup

https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-entry-processor/fragment-entry-processor-freemarker/src/main/java/com/liferay/fragment/entry/processor/freemarker/FreeMarkerFragmentEntryProcessor.java#L68

https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-entry-processor/fragment-entry-processor-editable/src/main/java/com/liferay/fragment/entry/processor/editable/EditableFragmentEntryProcessor.java#L123

https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-entry-processor/fragment-entry-processor-background-image/src/main/java/com/liferay/fragment/entry/processor/background/image/BackgroundImageFragmentEntryProcessor.java#63


I have tried to invoke these FragmentEntryProcessor's getDefaultEditableValuesJSONObject(String html, String configuration) on SampleSQLBuilder side, please see the last commit of this pull https://github.com/slnn/liferay-portal/pull/546,  but it seems that it needs the osgi.framework.FrameworkUtil, is it possible that use the FrameworkUtil in SampleSQLBuilder side?


Regards
Lily

**Pull request closed without merging**
