### PR TITLE
LPS-103369 pr-1805

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Hi @zhangyan0701 could you take a look at the failure of LocalFile.AppBuilder#ValidateAppLocalization to see whether it's unique?

**Comment by zhangyan0701** [comment]
The failure of test LocalFile.AppBuilder#ValidateAppLocalization is that when append locate `pt-BR` in URL, the page will return to locale en.

Details of the test:
1. locale.prepend.friendly.url.style=3.
2. Login as Test user whose preferred language is en_US.
3. Open URL http://localhost:8080/web/guest/home.
4. Open URL http://localhost:8080/pt-BR/.
5. URL change to http://localhost:8080/en/web/guest and page still displays in English.

It looks like related. @dantewang @yuhai please take a look about this.

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
The failure of test LocalFile.AppBuilder#ValidateAppLocalization happens when add below property in portal-ext file:
`virtual.hosts.default.site.name=`

**Pull request closed without merging**
