### PR TITLE
LPS X Stream portal search api

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Remove Optional usage from BaseModelRetriever
- LPS-X Apply
- LPS-X Remove Stream usage from SearchResponse
- LPS-X Apply
- LPS-X SF, simplify
- LPS-X Fix tests
- LPS-171292 Remove Optional from SearchPermissionFilterContributor and its implementations
- LPS-171292 SF
- LPS-X Remove Stream usages from HighlightFieldBuilder and apply
- LPS-X Remove Stream usages from SearchHitBuilder and SearchHitsBuilder by removing the deprecated methods
- LPS-X Sem Ver

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Functional test failures are unrelated.

**Pull request closed without merging**
