### PR TITLE
LPS-105107 Use the correct syntax to delete the primary key to upgrade database when the database is SQL Server

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:help

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@ChiZelin Hai's fix on Sybase has been sent and your pull will have conflicts if his pull is merged. I will hold this pull until Hai's fix is merged.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1626. [See changes here.](https://github.com/dantewang/liferay-portal/compare/83a1ca41e96b~2...83a1ca41e96b)

**Pull request closed without merging**
