### PR TITLE
LPS-92597

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the PR is based on https://github.com/tinatian/liferay-portal/pull/1291. I add the last commit.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/1311

**Pull request closed without merging**
