### PR TITLE
Lps 74148 part 3 commerce 7 27

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1908. [See changes here.](https://github.com/dantewang/liferay-portal/compare/3fc0e86278ea~1...3fc0e86278ea)

**Pull request closed without merging**
