### PR TITLE
Lps 125473 1 5 v1

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang 

Imitate the usage in DBUpgraderLauncher, I create a URLClassLoader in SampleSQLBuilderLauncher to load SampleSQLBuilder and invoke its main method.

It worked well with JDK8 and ant, I failed to test it with JDK 11 as the build of portal still requires JDK 8.

/cc @tinatian

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1870

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/521. [See changes here.](https://github.com/dantewang/liferay-portal/compare/bda27950f068~7...bda27950f068)

**Pull request closed without merging**
