### PR TITLE
LPS-86461

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang,

For the code fragment (https://github.com/yuhai/liferay-portal/blob/ebad2b9ea81d766a118458f1081c77c632927699/portal-kernel/src/com/liferay/portal/kernel/upgrade/BaseUpgradePortletId.java#L532-L534), 
"primKey != newRootPortletId" means not delete related initPortletDefaultPermissions. And this is only existed on 7.0. Please refer to https://github.com/yuhai/liferay-portal/blob/LPS-86461/portal-impl/src/com/liferay/portal/service/impl/PortletLocalServiceImpl.java#L185. We may not delete the datas.

Please check the related ci:test from https://github.com/yuhai/liferay-portal/pull/113

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @yuhai, @dantewang,

I have been talking to @dacousalr about this ticket and we have some concerns about this solution.

In this case the error is caused because the Portlet is available before the UpgradeBasePortletId is executed. We already solved this issue in other portlets defining a dependency in the Portlet class so that it waits for completing major and minor upgrade processes:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/flags/flags-web/src/main/java/com/liferay/flags/web/internal/portlet/FlagsPortlet.java#L55

Please, take a look at it, we should follow the same rule for Calendar and other portlets where we can reproduce this issue.

Let me know you thoughs,

Thanks.
Best regards:

PS: I  haven't executed tests but the solution implemented in this pull can be problematic if we execute the BaseUpgradePortletId in a fix pack with autoUpgrade = false, the customer could use the Portlet during some time and they could loose some data if they execute the upgrade later.

**Comment by dantewang** [comment]
@achaparro Thanks for pointing it out. Your concern makes sense. Since there is already a convention, should we ask if an SF rule can be added to enforce it?

**Comment by achaparro** [comment]
Hi @dantewang,

Having a SF rule would be great to avoid this kind of issues in the future.

Thanks!

**Pull request closed without merging**
