### PR TITLE
LPS-89497

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/tinatian/liferay-portal/pull/1685. Besides that, I do some change on the key "felix.fileinstall.filename". We allow that the name of file is different from service.pid. When we create one config file in \osgi\configs\, for example, 
The file:
com.liferay.configuration.test.configuration.ConfigurationTestConfiguration-hai.config
it will create one data in Configuraton_ table as the following:

> :org.apache.felix.configadmin.revision:=L"1"
> felix.fileinstall.filename="com.liferay.configuration.test.configuration.ConfigurationTestConfiguration-hai.config"
> name="testhai"
> service.bundleLocation="?"
> service.factoryPid="com.liferay.configuration.test.configuration.ConfigurationTestConfiguration"
> service.pid="com.liferay.configuration.test.configuration.ConfigurationTestConfiguration.f7d49298-4027-4ea7-b8d8-ab88c5c83c0c"

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@dantewang, I check modules-unit-jdk8, modules-compile-jdk8 and modules-semantic-versioning-jdk8, these errors aren't related with the fix.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/204. [See changes here.](https://github.com/dantewang/liferay-portal/compare/12a02bb4da1c~10...12a02bb4da1c)

**Pull request closed without merging**
