### PR TITLE
[deprecation round2] LPS-104401 portal-kernel part6

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1607. [See changes here.](https://github.com/dantewang/liferay-portal/compare/1cd1faef2056~1...1cd1faef2056)

**Pull request closed without merging**
