### PR TITLE
LPS-99222 Move BaseDLAppTestCase to document-library-test-util

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1493. [See changes here.](https://github.com/dantewang/liferay-portal/compare/0fc2e8fac0ed~7...0fc2e8fac0ed)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1494. [See changes here.](https://github.com/dantewang/liferay-portal/compare/c1c6124987b9~7...c1c6124987b9)

**Pull request closed without merging**
