### PR TITLE
LPS-X Fake test.properties

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Hi @jpince @vicnate5 
I keep getting portal-license-jdk8 failures due to various reasons. In this PR it looks like a typo in liferay-release-tool-ee, while in [a previous PR](https://github.com/dantewang/liferay-portal/pull/809) it failed because of a "7.0.0-ga1.zip" file. 

One thing I do notice is, for my PRs of this ticket, portal-license-jdk8 tries to do much more things (build & start portal, etc.) than other PRs. For example, in this PR https://github.com/shuyangzhou/liferay-portal/pull/6791, portal-license-jdk8 finishes without trying to build and start portal. 

There are also two warnings by Tomcat about memory leak of threads executing opening browser for `localhost:8080`.

Could you take a look at this? Thanks!

**Comment by dantewang** [comment]
@jpince @vicnate5
By the way, I'm wondering the following things:

- Why these changes trigger the build&start while others don't? Is there any other change that also triggers the build&start process and pass?
- If the ant failures are not caused by my changes, is there any way to check if my changes break anything in portal-license?

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@jpince @vicnate5

The portal-license-jdk8 also tries to download a file which is 404:

```
     [exec] get-plugins-sdk:
     [exec]       [get] Getting: http://mirrors.lax.liferay.com/releases.liferay.com/portal/plugins-sdk/liferay-plugins-sdk-7.0-1.0.21.zip
     [exec]       [get] To: /opt/dev/projects/github/liferay-portal/dist/liferay-plugins-sdk-7.0-1.0.21.zip
     [exec]       [get] Error opening connection java.io.FileNotFoundException: http://mirrors.lax.liferay.com/releases.liferay.com/portal/plugins-sdk/liferay-plugins-sdk-7.0-1.0.21.zip
     [exec]       [get] Error opening connection java.io.FileNotFoundException: http://mirrors.lax.liferay.com/releases.liferay.com/portal/plugins-sdk/liferay-plugins-sdk-7.0-1.0.21.zip
     [exec]       [get] Error opening connection java.io.FileNotFoundException: http://mirrors.lax.liferay.com/releases.liferay.com/portal/plugins-sdk/liferay-plugins-sdk-7.0-1.0.21.zip
     [exec]       [get] Can't get http://mirrors.lax.liferay.com/releases.liferay.com/portal/plugins-sdk/liferay-plugins-sdk-7.0-1.0.21.zip to /opt/dev/projects/github/liferay-portal/dist/liferay-plugins-sdk-7.0-1.0.21.zip
```

**Comment by jpince** [comment]
@petershin can you please look into this? `     [exec] /opt/dev/projects/github/liferay-release-tool-ee/build-common.xml:507: Can't get http://mirrors.lax.liferay.com/releases.liferay.com/portal/plugins-sdk/liferay-plugins-sdk-7.0-1.0.21.zip to /opt/dev/projects/github/liferay-portal/dist/liferay-plugins-sdk-7.0-1.0.21.zip`
I don't see 7.0-1.0.21 here: http://mirrors.lax.liferay.com/releases.liferay.com/portal/plugins-sdk/ Not sure why it's failing in this pull but nowhere else (that I know of)

@dantewang sorry I forgot to look at this yesterday

**Comment by dantewang** [comment]
@jpince Thanks! From what I see from console output, in other PRs, portal-license-jdk8 ends right after doing a git-diff, while this PR triggers much more operations after that...

**Comment by dantewang** [comment]
@jpince Any update on this failure? It seems to be the only blocker for this PR on CI...

**Comment by jpince** [comment]
@dantewang Chas is on PTO today but should be back tomorrow, he and Peter should be able to look into it more then.

**Comment by CAustin582** [comment]
@dantewang The property override.get.plugins.sdk can be used to skip this target. I don't think most people need the SDK anyway, so I've switched the default value to true. In case you ever do need it, I also changed the target to pull this file from Maven instead of files.liferay.com, so it should work regardless. Let me know if you're still having issues with it.

**Comment by dantewang** [comment]
@CAustin582 Thanks a lot! I'll try it again.

**Pull request closed without merging**
