### PR TITLE
LPS-120256

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/yuhai/liferay-portal/pull/231. (!(ct.aware=*)) can track Stores without ct.aware property. DBStore isn't tracked after the fix in CTStoreFactoryImpl.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1973.

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
