### PR TITLE
LPS-87327

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang,

The issue is however we check and uncheck the "Add Sample Data" in UI, it doesn't take effect after restart.

On 6.2, in setup_wizard.jsp, after we click "finish configuration", it will add sample data if checked.
On 7.0, LPS-54660 changed the behavior. The property "setup.wizard.add.sample.data" only takes effect when connects a new database on startup. It is not related with setup_wizard page. (LPS-85523 documented the property in portal.properties).

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai The change in LPS-54660 is confusing.

Actually, it has nothing to do with setup wizard, not limited to UI, but to every aspect. Even if setup wizard is disabled, the sample data will be added as long as db is new and the property to add sample data is set to true, right?

And Ray's change makes it impossible to make the UI work, because the db is no longer new when we see setup wizard.

If we accept this, then the property shouldn't be called "setup.wizard.add.sample.data", but something like "first.startup.add.sample.data" (or other better names); the util shouldn't be called `SetupWizardSampleDataUtil` either, but `FirstStartupSampleDataUtil` etc.

Could you make it clear in your commit message, and make the changes above and resend? Thanks!

**Comment by yuhai** [comment]
Please see https://github.com/dantewang/liferay-portal/pull/894

**Pull request closed without merging**
