### PR TITLE
LPS-X Remove parallel rendering

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/ChiZeLin/liferay-portal/pull/250. [See changes here.](https://github.com/dantewang/liferay-portal/compare/e3afc453196e~1...e3afc453196e)

**Pull request closed without merging**
