### PR TITLE
LPS-96118  Replace proxy creation in portal-kernel

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

Main Task: LPS-96117 Optimized Proxy creation replacement.
Sub  Task: LPS-96118  Replace proxy creation in portal-kernel.

I replaced the proxy creation method in portal-kernel. 
Thanks for checking!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
Add  LayoutSetLocalServiceStagingAdvice ,as it releated to LayoutSetStagingHandler

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/375

**Pull request closed without merging**
