### PR TITLE
[Bug Fix]LPS-145031

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the [requirement](https://github.com/dantewang/liferay-portal/pull/2136#issuecomment-1011059965).

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the results?

**Comment by Hijky** [comment]
I will continue to review the test result tomorrow.

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Pull request closed without merging**
