### PR TITLE
LPS-81891 Moving showEditor to its original place

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @dantewang,

With these changes the editors are no longer rendered for each comment. Now they will be fetched on demand when the user clicks the `reply` and `edit` buttons.

If you are happy with the performance please let me know and I will forward to Sergio.

Regards

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn Please run tests on Blog

**Comment by slnn** [comment]
Test results on Blog please see:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Portal CPU % | Old Gen GC Times | Young Gen GC Times
-- | -- | -- | -- | -- | -- | -- | --
BaseLine | ac9f4a4 | 11076 | 843 | 645 | 91,84,84 | 40 | 1210
PR-677: | - | 12629 | 56.6 | 163 | 81,86,87 | 24 | 1113

**Comment by dantewang** [comment]
@4lejandrito The test result already shows a 14% performance improvement, and there's still space to push harder (see Portal CPU %). It also greatly improves GC.

Please forward, thank you very much!

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
