### PR TITLE
LPS 142279

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-142278
- LPS-142279 Move _getLibDir to ClassUtil as a public method "getParentDir", and replace ClassUtil.getParentPath usages

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the results when they come out? Please ignore the unit test failure of ClassUtilTest.

**Comment by zhangyan0701** [comment]
No related issue found.

**Pull request closed without merging**
