### PR TITLE
LPS-78581 PortletSession.isNew: throws IllegalStateException when called on invalidated session

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@ngriffin7a Hey Neil, could you try this change on top the portlet3 branch to see if it fixes the issue (and TCK test cases) of https://issues.liferay.com/browse/LPS-77746?

**Comment by ngriffin7a** [comment]
@dantewang I'm in the middle of a large refactor of PortletRequestImpl.java right now which would make it difficult for me to test this. Were you able to test to see if this fixes https://issues.liferay.com/browse/LPS-77746 on your system? If you are working with the liferay-portlet3 branch of my portals-pluto repository, then you should be able to test the V3HeaderPortletTests locally.

**Comment by ngriffin7a** [comment]
@dantewang FYI, I just pushed my large refactor of PortletRequestImpl.java to https://github.com/ngriffin7a/liferay-portal/tree/portlet3

**Comment by dantewang** [comment]
@ngriffin7a I manually deployed the test portlet and saw the 3 test cases mentioned in the LPS-77746 showed success.

**Pull request closed without merging**
