### PR TITLE
LPS-111104 upgrade log4j2

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@tinatian

**I think the main stream of this pull looks OK, alhough it contains many implementation detail issues, like config file handling.**

The major challenges of the upgrading are the brand new "LoggerContext" concept and the immutable configurations in Log4J 2.

When using Log4J 1, all loggers are registered in a single "repository", and we can supply new configurations into this "repository" to add or update loggers.

When using Log4J 2, we can't do this because
1. Configuration classes are immutable, and reconfiguring APIs "replace" instead of "updating" the configs. If loggers are in the same context, reconfigure will be hard and heavy.
2. LoggerContext -- each OSGi bundle should have its own LoggerContext by design.

So this pull takes the one LoggerContext per bundle way.

Core will have a LoggerContext created by `Log4JUtil`; each OSGi bundle will have a LoggerContext managed by `Log4jExtenderBundleActivator`. Reconfiguring happens within each LoggerContext, so it's much easier & lighter to do the configuration replacement.
 I'll try to split the pull but it may not be easy -- as soon as we introduce the new version as dependency, everything will be broken.

A major problem now exists in `LogAssertionTestRule`. It installs an appender to the root logger on `beforeClass`, and removes it on `afterClass`. However, in the separated `LoggerContext` environment, it's no-go to install the appender to root logger of every `LoggerContext`.

**Comment by dantewang** [comment]
@yuhai I can successfully build your pull, but get exceptions when starting portal. 

The first one:

```
2020-07-24 16:31:35.850 INFO  [SCR Component Actor][QuartzSchemaManager:57] java.sql.SQLSyntaxErrorException: Table 'lportal.QUARTZ_JOB_DETAILS' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'lportal.QUARTZ_JOB_DETAILS' doesn't exist
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:138) ~[mariadb.jar:?]
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106) ~[mariadb.jar:?]
	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:268) ~[mariadb.jar:?]
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:296) ~[mariadb.jar:?]
	at org.mariadb.jdbc.MySQLStatement.executeQuery(MySQLStatement.java:349) ~[mariadb.jar:?]
	at org.mariadb.jdbc.MySQLPreparedStatement.executeQuery(MySQLPreparedStatement.java:104) ~[mariadb.jar:?]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[hikaricp.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[hikaricp.jar:?]
	at com.liferay.portal.scheduler.quartz.internal.QuartzSchemaManager.activate(QuartzSchemaManager.java:49) [bundleFile:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:756) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$1.run(AbstractComponentManager.java:456) [bundleFile:?]
	at org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:113) [bundleFile:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.mariadb.jdbc.internal.common.QueryException: Table 'lportal.QUARTZ_JOB_DETAILS' doesn't exist
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:995) ~[mariadb.jar:?]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1050) ~[mariadb.jar:?]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1030) ~[mariadb.jar:?]
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:289) ~[mariadb.jar:?]
	... 24 more
```

```
16:31:52.411 [main] ERROR com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterHelper - Unable to initialize filter com.liferay.portal.servlet.filters.sso.opensso.OpenSSOFilter
java.lang.ClassNotFoundException: com.liferay.portal.servlet.filters.sso.opensso.OpenSSOFilter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365) ~[catalina.jar:9.0.33]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188) ~[catalina.jar:9.0.33]
	at com.liferay.portal.kernel.util.InstanceFactory.newInstance(InstanceFactory.java:56) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.InstanceFactory.newInstance(InstanceFactory.java:27) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterHelper.initFilter(InvokerFilterHelper.java:319) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterHelper.readLiferayFilterWebXML(InvokerFilterHelper.java:375) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterHelper.init(InvokerFilterHelper.java:94) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doPortalInit(InvokerFilter.java:183) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.init(InvokerFilter.java:128) [portal-kernel.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4538) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) [catalina.jar:9.0.33]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631) [catalina.jar:9.0.33]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1831) [catalina.jar:9.0.33]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.33]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) [?:1.8.0_181]
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526) [catalina.jar:9.0.33]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425) [catalina.jar:9.0.33]
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576) [catalina.jar:9.0.33]
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [catalina.jar:9.0.33]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.33]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_181]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) [catalina.jar:9.0.33]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.33]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:633) [catalina.jar:9.0.33]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343) [bootstrap.jar:9.0.33]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474) [bootstrap.jar:9.0.33]
```

Did you also get these errors? If so, do you know the reason?

**Comment by yuhai** [comment]
@dantewang, I also got these errors. I ignored the errors because these seemed unrelated with the PR. I will check these errors.

**Comment by dantewang** [comment]
@yuhai When you fix the errors, please resend the pull and include the unit test you sent earlier -- it should test Liferay's API, so you shouldn't need to change it much between before & after applying Log4J 2.

**Comment by yuhai** [comment]
@dantewang, ok, got it.

**Pull request closed without merging**
