### PR TITLE
LPS-52121 Add flash magic bytes protection

### PR DESCRIPTION
**Pull request by topolik**
Hi Dante,

I'd like to ask you for some standard performance tests. MHan wants to make sure there's no penalty.

This functionality relates to DocLib file downloads.

Thank you!

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn Hi Lily, please run this pull request on DocumentLibrary test.

**Comment by slnn** [comment]
Hi all,
Here is the test result of this pull request on Document Library:
From the results, this pull request did not make performance regression on Document Library:

Portal Version| Git ID| Session Count| Mean Time of Login| Mean Time of Add DL File|
------------ | ------------- | ------------- | ------------- | ------------- | -------------
Base Line |188d32a|7369|168|699
PR-125 |7b4deda|7419|157|694

*Explanation of columns:*
  __Portal Version__: *a description about the git id column.*
  __Git ID__: *the revision with which the test is ran.*
  __Session Count__:*it is the "virtual user" in our performance whitepaper, which represents how    much load we generate. We take it as the performance score.*
  __Mean Time__: *the average response time of a step in the test.*

**Comment by dantewang** [comment]
@topolik please note that the changes might not be hit by our doclib test.

**Comment by topolik** [comment]
OK, thank you!

**Pull request closed without merging**
