### PR TITLE
[portal-test-integration] LPS-102458 InjectTestRule

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
@ChiZeLin rebase conflict, please resend.

**Pull request closed without merging**
