### PR TITLE
LPS-X Hibernate 2022-2-22

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-128873 Upgrade to Hibernate-core 5.6.3.Final and add required dependencies
- LPS-128873 Auto SF
- LPS-X Apply LPS-100343 for Hibernate 5: check in original class
- LPS-X Apply LPS-100343 for Hibernate 5: instead of patching for Hibernate 3, patch for Hibernate 5 now
- LPS-X Apply LPS-100343 for Hibernate 5: FAKE GRADLE CACHE
- LPS-X Apply LPS-100343 for Hibernate 5: apply
- LPS-X build-lib-versions
- LPS-X Migrate custom types, we should implement UserType rather than CompositeUserType. CompositeUserType is just a workaround to fix LPS-17984, now we are upgrading to hibernate 5.X, no longer need the workaround anymore.
- LPS-X Migrate StringClobType, it is replaced by MaterializedClobType in Hibernate 4; MaterializedClobType#isEqual(Object, Object) method is final so we have to override the type descriptor which this method delegates to.
- LPS-X Migrate LockModeTranslator: org.hibernate.LockMode#parse(String) -> org.hibernate.LockMode#fromExternalForm(String)
- LPS-X Migrate CacheModeTranslator: org.hibernate.CacheMode#parse(String) -> org.hibernate.CacheMode#interpretExternalSetting(String)
- LPS-X Migrate IDGenerator: org.hibernate.engine.SessionImplementor -> org.hibernate.engine.spi.SharedSessionContractImplementor
- LPS-X Migrate SessionFactoryImpl: org.hibernate.engine.SessionFactoryImplementor -> org.hibernate.engine.spi.SessionFactoryImplementor
- LPS-X Migrate event listeners: 1) update packages; 2) avoid using deprecated methods in event listeners
- LPS-X Migrate customized property accessors: PropertyAccessor -> PropertyAccessStrategy that works as factory of PropertyAccess
- LPS-X Migrate SessionImpl: 1) Session#close() in Hibernate 5 no longer returns Connection, return null here to quick fail; 2) SessionFactoryImplementor#getEntityPersister(String) -> MetamodelImplementor#entityPersister(Class); 3) constructor of EntityKey
- LPS-X Migrate: remove FieldInterceptionHelperUtil as the bytecode instrumentation code has been removed from Hibernate and replaced by another infrastructure, see HHH-10280
- LPS-X Migrate PortalHibernateConfiguration: move logic to CTModelIntegrator
- LPS-X Migrate PortalHibernateConfiguration: move event listeners logic to integrator
- LPS-X Migrate PortalHibernateConfiguration: move newConfiguration logic to afterPropertiesSet and buildSessionFactory
- LPS-X Migrate PortalHibernateConfiguration: remove the optimization for QueryPlanCache and related property. The related Hibernate issue HHH-4959 has been fixed since 5.2.6, so this particular optimization should not be needed for now.
- LPS-X Migrate PortalHibernateConfiguration: move this to buildSessionFactory, as it needs the Configuration (LocalSessionFactoryBuilder)
- LPS-X Migrate PortalHibernateConfiguration: Remove deprecated property, use new property
- LPS-X Migrate PortalHibernateConfiguration: remove Javassist related code since Hibernate only uses ByteBuddy since 5.6.3
- LPS-X Update usage of PortalHibernateConfiguration
- LPS-X Migrate: use default DialectResolver as fallback. The proper way to integrate into Hibernate is to customize the DialectFactory service during creating of session factory, but in Liferay there are code depending on the DialectDetector to determine database type outside Hibernate, executed even before initialization of Hibernate. If we go with the Hibernate native way, the execution order during startup needs to be adjusted which would be a big change.
- LPS-X Migrate: update packages to org.springframework.orm.hibernate5
- LPS-X Migrate: use SessionBuilder from SessionFactory to create session from provided connection
- LPS-X Migrate: package name
- LPS-X Hibernate 5 defaults to ByteBuddy as byte code tool, set it to Javassist to avoid introducing new dependency
- LPS-X Migrate: portal-spring-extender-impl; the javax.persistence-api is required for compiling as Hibernate 5 SessionFactory extends javax.persistence.EntityManagerFactory
- LPS-X Migrate: portal-lock-service; the javax.persistence-api is required for compiling as some Hibernate 5 Exceptions extend javax.persistence.PersistenceException
- LPS-X Migrate: StatisticsService
- LPS-X Migrate VerifySessionFactoryWrapper: org.hibernate.internal.SessionFactoryImpl#getAllClassMetadata() -> org.hibernate.internal.SessionFactoryImpl#getMetamodel()
- LPS-X Fix zero based positional query parameters https://hibernate.atlassian.net/browse/HHH-13414
- LPS-X Fix no transaction issue
- LPS-X Fix compile for test
- LPS-X export-import-test-util
- LPS-X Fix compile for aspectj-hibernate-stale-object-state
- LPS-X Fix compile for aspectj-hibernate-unexpected-row-count
- LPS-X Fix, auto flush is not working for portlet session as it is considered not in active transaction, add logic to check spring's thread local as what's did in hibernate 3.6
- LPS-X Fix exception check in LockLocalServiceTest
- LPS-X Fix log assertion by adding expected log on BatchingBatch because SQLExceptions in BatchingBatch are logged twice -- see https://github.com/hibernate/hibernate-orm/pull/1544
- LPS-X When the error "Row was updated or deleted by another transaction" happened, hibernate.core-3.6.10 throw StaleObjectStateException(refer to AbstractEntityPersister.check()). However, hibernate-core-5.5.2 throw StaleStateException(refer to Expectations#BasicExpectation.checkBatched()).
- LPS-X Fix LockLocalServiceTest: Now throws a PersistenceException containing a ConstraintViolationException
- LPS-X Migrate test
- LPS-X Fix failure of ViewCountEntryLocalServiceTest caused by double logging (BatchingBatch)
- LPS-X Set StagedExpandoColumnImpl and StagedExpandoTableImpl to entityPersisterMap of MetamodelImpl class. When contains(object) of SessionImpl executes, it won't throws exception and make transaction for rollbackOnly if the object is StagedExpandoColumnImpl or StagedExpandoTableImpl. The commit will be reverted after removing staging.
- LPS-X Auto SF
- LPS-X Workaround: solve Hibernate lazy proxy issue "java.lang.NoClassDefFoundError: org/hibernate/proxy/HibernateProxy" during portal startup.
- LPS-X Override the method to use LegacyLimitHandler so that it can invoke our SQLServerLimitStringUtil.getLimitString() to generate the sql. Otherwise, it will use SQLServer2005LimitHandler. This will cause JournalFolderServiceImpl.getFoldersAndArticles() generated sql parse failed. But LegacyLimitHandler is deprecated, only LegacyLimitHandler may invoke the getLimitString() method when processing sql.
- LPS-X PostgreSQLDialect was deprecated by PostgreSQL82Dialect. In addition, hibernate 5.5.2 provides one class to return different dialects based on different database versions, please see org.hibernate.dialect.Database. In our case, it will return PostgreSQL10Dialect, and PostgreSQL10Dialect extends PostgreSQL82Dialect. So use PostgreSQL10Dialect as the condition.
- LPS-X When transaction Callback executes, TransactionDefinition is PROPAGATION_SUPPORTS and autoCommit of connection is true. For POSTGRESQL, at that time, when resultSet.getClob() executes, the error "org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode." will happen. The reason is that the autoCommit of connection is true. Please see org.postgresql.largeobject.LargeObjectManager.open(). For example, the issue will happen when CompanyLocalServiceImpl#registerCompany executes. The commit sets SqlTypeDescriptor when the database is POSTGRESQL. And then only copy DEFAULT of org.hibernate.type.descriptor.sql.ClobTypeDescriptor as one subClass and let subClass to replace DEFAULT(no logic change). The next commit will add the fix in the subClass.
- LPS-X Set autoCommit of connection for false when getClob() executes to avoid the issue happening.
- LPS-X SemVer

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@vincate5 Could you review the latest results? Thanks!

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by zhangyan0701** [comment]
There are some integration test failures seems related:

- [com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest](https://testray.liferay.com/home/-/testray/case_results/1617718681)

- [com.liferay.portlet.expando.service.persistence.test.ExpandoColumnPersistenceTest](https://testray.liferay.com/home/-/testray/case_results/1617720143)

- [com.liferay.portlet.expando.service.persistence.test.ExpandoTablePersistenceTest](https://testray.liferay.com/home/-/testray/case_results/1617720156)

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

@yuhai I remember you have taken care of Expando related failures... Could you check whether this pull contains your fix, and whether the test failures are what you've worked on? If they are new, you can leave them to me.

**Comment by yuhai** [comment]
> @zhangyan0701 Thanks!
> 
> @yuhai I remember you have taken care of Expando related failures... Could you check whether this pull contains your fix, and whether the test failures are what you've worked on? If they are new, you can leave them to me.

@dantewang, ok, I will check.

**Comment by dantewang** [comment]
@zhangyan0701 By the way, are they the only failures that seem to be related?

**Comment by zhangyan0701** [comment]
> @zhangyan0701 By the way, are they the only failures that seem to be related?

Yes, I didn't see other related failures.

**Pull request closed without merging**
