### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1752. [See changes here.](https://github.com/dantewang/liferay-portal/compare/9113e723db79~3...9113e723db79)

**Pull request closed without merging**
