### PR TITLE
LPS-198097 The Javadoc for getDateHeader requires us to parse date strings and return them as a long. Please see the description of LPS-198097 for more details.

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
@zhangyan0701 Could you check the TCK result? See if there's any unique test case failure compared to upstream. Thanks!

**Comment by zhangyan0701** [comment]
@dantewang 

No unique failures in tck tests.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Pull request closed without merging**
