### PR TITLE
LPS-106612 Patch jars for jboss | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**
@dantewang Resend according to https://github.com/brianchandotcom/liferay-portal/pull/83423#issuecomment-575450555

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83427.

**Pull request closed without merging**
