### PR TITLE
LPS-103269 remove unused deprecations from util-taglib

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@dantewang, I applied the fix on master-private, no error happened when startup and ant all.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@yuhai There are several changes that you removed usages in JSPs first. Let's consider them as "deprecations that still have usages" and leave them to second round. This round let's just focus on those which can be easily removed without the need to refactoring usage, unless the usage is also deprecated and no one else is using it.

Please resend a pull with only deprecations without usage (or used by deprecated method/class which is not used by any one).

**Pull request closed without merging**
