### PR TITLE
LPS-97569 Getting the locale directly from the request

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @dantewang,

Getting the locale from the request will be much more performant. I know `PortalUtil` does a lot more things but we use `request.getLocale` in so many places that I believe we are not missing anything important by not using `PortalUtil`.

If you agree please forward to Brian.

Thanks!

**Comment by dantewang** [comment]
@4lejandrito I think it's safe as long as the social bookmarks are used by portlets. Normally, in servlets included by a portlet, `request.getLocale()` should return this locale (which is from `ThemeDisplay`): https://github.com/liferay/liferay-portal/blob/7cef076fa10996aebb712e6eaf254a92fb499f5e/portal-impl/src/com/liferay/portlet/internal/PortletRequestImpl.java#L869

Will forward.

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75107. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Thanks for the info!. I didn't know that.

**Pull request closed without merging**
