### PR TITLE
LPS-160078 Do not use Spring extender service as dependency injection

### PR DESCRIPTION
**Pull request by ling-alan-huang**
```
java.lang.Exception: Found 5 formatting issues:
1: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-currency-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
2: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-price-list-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
3: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-product-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
4: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
5: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/portal/portal-upgrade-test/src/testIntegration/resources/com/liferay/portal/upgrade/test/dependencies/service/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@ling-alan-huang 
```
5: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/portal/portal-upgrade-test/src/testIntegration/resources/com/liferay/portal/upgrade/test/dependencies/service/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
```

This catch should be a false positive, since it's in an integration test..

**Comment by ling-alan-huang** [comment]
Closing. I will resend.

**Comment by ling-alan-huang** [comment]
see: https://github.com/dantewang/liferay-portal/pull/2253

**Pull request closed without merging**
