### PR TITLE
LPS-96227

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang , please refer to ci:test from https://github.com/yuhai/liferay-portal/pull/139

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:messageboards

**Comment by dantewang** [comment]
@yuhai Please verify if the MB functional test failures are related.

**Comment by yuhai** [comment]
@dantewang , they should be not related. The same error also occurred at https://github.com/slnn/liferay-portal/pull/410

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1167. [See changes here.](https://github.com/dantewang/liferay-portal/compare/900081d5cc36~2...900081d5cc36) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/411. [See changes here.](https://github.com/dantewang/liferay-portal/compare/900081d5cc36~2...900081d5cc36) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1412. [See changes here.](https://github.com/dantewang/liferay-portal/compare/b9d91cee1dff~2...b9d91cee1dff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
