### PR TITLE
LPS-124222 Patch daisydiff.jar

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1845. [See changes here.](https://github.com/dantewang/liferay-portal/compare/4a36e751ef06~4...4a36e751ef06)

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1846. [See changes here.](https://github.com/dantewang/liferay-portal/compare/fed6feef63fb~2...fed6feef63fb)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2084. [See changes here.](https://github.com/dantewang/liferay-portal/compare/fed6feef63fb~2...fed6feef63fb)

**Pull request closed without merging**
