### PR TITLE
Lps 131273 6 9

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
cc @tinatian @shuyangzhou Forwarding to Brian as per https://github.com/brianchandotcom/liferay-portal/pull/102813#issuecomment-855166056 and https://github.com/tinatian/liferay-portal/pull/2258#issuecomment-856959653

**Pull request closed without merging**
