### PR TITLE
LPS-102247 Move DLTestUtil

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1509. [See changes here.](https://github.com/dantewang/liferay-portal/compare/89883938db96~2...89883938db96)

**Pull request closed without merging**
