### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/dantewang/liferay-portal/pull/1735. I merge the previous mentioned codes.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Does `ResourceActionDefinitionTest` pass with your Commerce changes? Also, please make sure your changes doesn't break any function in Commerce. Ask Commerce guys to test and review this part separately since it's just clean up.

I'll remove your Commerce changes from this pull and run CI.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1743.

**Pull request closed without merging**
