### PR TITLE
LPS-108235 Get parameter from servletRequest if the value of the parameter haven't be found before here

### PR DESCRIPTION
**Pull request by ChiZelin**
@dantewang 
A parameter named action will be added by [this hidden input field](https://github.com/apache/portals-pluto/blob/eb0938238ec12e4b9c72c41a2babb48b6c4686fb/portlet-tck_3.0/V2PortletTagLibraryTests2/src/main/webapp/WEB-INF/jsp/PortletTagLibraryTests2_SPEC2_26_IncludeJSPRender.jsp#L646).

After the form is submitted, we want to get that parameter at [this line](https://github.com/apache/portals-pluto/blob/eb0938238ec12e4b9c72c41a2babb48b6c4686fb/portlet-tck_3.0/V2PortletTagLibraryTests2/src/main/java/javax/portlet/tck/portlets/PortletTagLibraryTests2_SPEC2_26_IncludeJSPRender.java#L76).

But we get null actually. So the test failed.

CI result: https://github.com/ChiZelin/liferay-portal/pull/256

### CODE REVIEW

**Comment by ChiZelin** [comment]
I tested V2PortletTagLibraryTests2_SPEC2_26_IncludeJSPRender_actionURL20 locally. It succeeded.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@ChiZelin Did you check why the parameter can not be fetched by `NamespaceServletRequest#getParameter`? Is there any problem in our parameter handling?

**Comment by dantewang** [comment]
@vicnate5 ci:test:tck does not work now, is it a known issue? See https://github.com/ChiZelin/liferay-portal/pull/256#issuecomment-621510691

**Comment by ChiZelin** [comment]
> @ChiZelin Did you check why the parameter can not be fetched by `NamespaceServletRequest#getParameter`? Is there any problem in our parameter handling?

I didn't find the parameter handling in the stack, I just found I can get the parameter from the servletRequest. Let me investigate further.

**Pull request closed without merging**
