### PR TITLE
pull request 143151 LPS 199568

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-199568 Initial checkin
- LPS-199568 Patch ContextController to remove getServletContextDTO(), this can no longer be used in Liferay as we don't register any real HttpServiceRuntime
- LPS-199568 Patch ContextController to remove fireSessionIdChanged(); the call chain originated from ProxyServlet but was never used even in Equinox
- LPS-199568 Patch ContextController to remove RequestInfoDTO collecting from getDispatchTargets() methods,
- LPS-199568 Patch to remove unused method from HttpServletEndpointController interface
- LPS-199568 Patch ContextController to allow extending it without having to call the constructor with parameters
- LPS-199568 Generate patch file
- LPS-199568 Update project file
- LPS-199568 Apply
- LPS-199568 Create LiferayContextController extending and having ContextController, prepare for inlining
- LPS-199568 Inline ContextController methods and SF, except add* methods
- LPS-199568 Inline ContextController.addFilterRegistration() and related code and SF
- LPS-199568 Remove legacyTCCL support, it's for servlet objects registered from HttpService API, which is not supported in Liferay anymore
- LPS-199568 SF
- LPS-199568 Inline ContextController.addListenerRegistration() and related code and SF
- LPS-199568 Inline ContextController.addResourceRegistration() and related code and SF
- LPS-199568 Inline ContextController.addServletRegistration() and related code and SF
- LPS-199568 Use the inlined class
- LPS-199568 Wordsmith
- LPS-199568 Sort
- LPS-199568 Wordsmith
- LPS-199568 Wordsmith/rename
- LPS-199568 Wordsmith
- LPS-199568 Sort by groups?
- LPS-199568 SF
- LPS-199568 Sort?
- LPS-199568 Rename
- LPS-199568 FAKE GRADLE CACHE
- LPS-199568 Fix compile error, this is from 3rd party library class
- LPS-199568 SF, rename back, this object contains not only http session related listeners, but also ones like ServletRequestAttributeListener, so just follow the class name as field name.
- LPS-199568 SF, rename and inline
- LPS-199568 SF, rename
- LPS-199568 SF, simplify
- LPS-199568 SF, rename
- LPS-199568 SF, simplify
- LPS-199568 SF, rename
- LPS-199568 Clean up, Liferay is already on Servlet 3.1+
- LPS-199568 Sort, in Servlet logic, open service trackers for listeners first, then filter, then endpoints; close trackers in reverse order.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look when test finishes? Or ask other office QA to keep an eye, thanks!

**Comment by zhangyan0701** [comment]
@dantewang 

No regressions found.

**Comment by dantewang** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/143371

**Pull request closed without merging**
