### PR TITLE
LPS-84181 Apply petra StringBundler

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1693. [See changes here.](https://github.com/dantewang/liferay-portal/compare/12b89141df65~1...12b89141df65)

**Pull request closed without merging**
