### PR TITLE
Lps 149061 3 15

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang 

Compare with the previous pull, new changes in this pull

1. Remove the unused getJSON() method in interface and implement
- FrontendTokenCategory FrontendTokenCategoryImpl
- FrontendTokenMapping FrontendTokenMappingImpl 
- FrontendTokenSet FrontendTokenSetImpl-

2. Replace all the usage of JSONLocalizer's getJSON(Local) with getJSONObject(local) method

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test

**Comment by dantewang** [comment]
@slnn I think what Tina meant in the end is to directly change `getJSON` to return `JSONObject` instead of `String`. So you just need to update the current usages, and don't need to touch those unused ones.

**Comment by slnn** [comment]
> @slnn I think what Tina meant in the end is to directly change `getJSON` to return `JSONObject` instead of `String`. So you just need to update the current usages, and don't need to touch those unused ones.

OK, I will drop these changes about removing methods

**Pull request closed without merging**
