### PR TITLE
LPS-101034 Update SampleSQLBuilder

### PR DESCRIPTION
**Pull request by slnn**
This is the fix for upstream about SampleSQLBuilder caused by LPS-101034

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
cc: @tinatian

**Comment by dantewang** [comment]
Fetched

**Comment by tinatian** [comment]
Hi @dantewang,
Please send this to Brian directly and cc me and shuyang.
If we have fix exactly like this, which table columns or api methods changed, need to update our code, please also send to Brian directly and cc us.

Thanks.
Tina.

**Pull request closed without merging**
