### PR TITLE
[deprecation round2] LPS-106324 portal-impl part4

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1655. [See changes here.](https://github.com/dantewang/liferay-portal/compare/25fd163b6389~1...25fd163b6389)

**Pull request closed without merging**
