### PR TITLE
LPS-110862 StringBundler part4

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1789. [See changes here.](https://github.com/dantewang/liferay-portal/compare/49e2896177c0~1...49e2896177c0)

**Pull request closed without merging**
