### PR TITLE
LPS 142278 11 25 2

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-142278 Should download into shielded container lib dir
- LPS-142278 Should copy portal jars from shielded container lib dir in BaseDeployer
- LPS-142278 Apply to calls to *Deployers in build-dist.xml
- LPS-142278 Remove old logic that sets LIFERAY_LIB_PORTAL_DIR by servlet context; shielded container dir is already set this way. Also, this was added by LPS-52665 to resolve JRuby issue when deploying portal using unexploded war - JRuby is no longer used and our customer facing documents never mention using unexploded war now.
- LPS-142278 Remove sysproperty for portal lib dir, this was added by LPS-65693 (a161a2a957de85c3eb6591d7921ca082a628a9a4) for integration tests in core, but these tests have been moved to modules.
- LPS-142278 Remove this, as long as no unit test fails we don't replace it with shielded container lib dir
- LPS-142278 Replace portal lib dir with shielded container lib dir in DirectDeployTask
- LPS-142278 Deprecate LIFERAY_LIB_PORTAL_DIR
- LPS-142278 Remove initialization logic for deprecated properties; this will also fix LPS-142277
- LPS-142278 SF, inline
- LPS-142278 Replace BACK_SLASH with SLASH for shielded container system property, so other properties can benefit from it; the paths obtained by _getLibDir() does not need this.
- LPS-142278 Deprecate WebDirDetector as no one is using it
- LPS-142278 Add integration test

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
The failures in ci:test:environments and ci:test:default are unrelated.

Manual testing passed with the changes of this PR, see details in ticket https://issues.liferay.com/browse/LRQA-71852.

**Pull request closed without merging**
