### PR TITLE
Vii api performance

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
2023-08-29 10:35:11.038 INFO  [com.liferay.headless.admin.user.test-executor-thread][AddUsersByVIIAPITest:169] Single thread added 100 users, used 67896ms
2023-08-29 10:35:11.039 INFO  [com.liferay.headless.admin.user.test-executor-thread][AddUsersByVIIAPITest:176] Average speed : 1.47 tps


2023-08-29 10:38:10.040 INFO  [com.liferay.headless.admin.user.test-executor-thread][AddUsersByVIIAPITest:140] 10 threads each added 10 users, used 13714ms
2023-08-29 10:38:10.040 INFO  [com.liferay.headless.admin.user.test-executor-thread][AddUsersByVIIAPITest:147] Average speed : 7.29 tps

**Comment by slnn** [comment]
Update: increase the expire time for the Bearer token, the default value is 600 seconds, it is not enough for large data cout, such as total 10000 users

**Comment by shuyangzhou** [comment]
See https://github.com/dantewang/liferay-portal/pull/2320

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
