### PR TITLE
LPS-111235 run CI

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Jenkins Results:
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/386720/

The segments integration test failures seems related:
Error in log:
```
[exec] com.liferay.segments.odata.matcher.test.SegmentsEntryODataMatcherTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.segments.test [1070]
     [exec]       Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=9.0))"
```
It may related to the version change of com.fasterxml.jackson.

**Comment by dantewang** [comment]
@yxingwu @jesseyeh-liferay The integration error seems to be unique, see Summer's comment. Please look into it, thanks.

**Comment by jesseyeh-liferay** [comment]
@yxingwu 
I used the workaround from [LPS-98289](https://issues.liferay.com/browse/LPS-98289) and created a new PR: https://github.com/dantewang/liferay-portal/pull/1593. I'm not sure if this is the correct approach to resolve the CI test failures, but I was able to successfully run the tests locally using it.

**Pull request closed without merging**
