### PR TITLE
LPS-121111

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I rebase https://github.com/dantewang/liferay-portal/pull/1772. The pr includes LPS-117531 and LPS-121111. Please refer to ci:test result from https://github.com/yuhai/liferay-portal/pull/235

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@dantewang, I find I lost one replace when working on LPS-112056 . I just append one commit to the last.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@yuhai Please resend LPS-117531 first. Thanks!

**Pull request closed without merging**
