### PR TITLE
LPS-117531 clean

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
@dantewang, I tested the two cases.
1. Create one KaleoDefinitionVersion in UI.
2. Upgrade 7.0 to master. If upgrade from 7.0 to 7.2, the logic is necessary. Since we did some changes (move model-resource to service module) and the logic is not necessary on master.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the CI results?
@yuhai Please double check the changes if there are relevant failures. Also, you removed read and check logic from Kaleo's upgrade process because when the upgrade is registered, the model resource actions must have been loaded (read and checked). Then I think we can also clean up other upgrades? I saw in the previous LPS-117531 pull that DDM, Journal, and some other upgrades also have this read and check logic.

**Comment by yuhai** [comment]
@dantewang, I will check these.

**Comment by zhangyan0701** [comment]
@dantewang Sorry for the late, I will check the CI results tomorrow.

**Comment by zhangyan0701** [comment]
Most tests failed at Terms of Use page:
after1

And some exceptions in log:
`     [exec] 10:12:38,826 ERROR [http-nio-8080-exec-8][IncludeTag:128] Current URL /c generates exception: javax.servlet.ServletException: java.lang.ExceptionInInitializerError
     [exec] com.liferay.portal.kernel.exception.SystemException: The base properties file was not found for portlet

     [exec] 10:14:42,530 ERROR [http-nio-8080-exec-11][IncludeTag:128] Current URL /web/guest generates exception: java.lang.NoClassDefFoundError: Could not initialize class com.liferay.journal.configuration.JournalServiceConfigurationValues
     [exec] java.lang.NoClassDefFoundError: Could not initialize class com.liferay.journal.configuration.JournalServiceConfigurationValues`

Expected Terms of Use page:
expected

@yuhai Please take a look at, thanks!

**Comment by yuhai** [comment]
@zhangyan0701, the issue looks unrelated with the pr, thanks.

**Comment by dantewang** [comment]
I didn't send https://github.com/dantewang/liferay-portal/pull/1795/commits/9cd2aad9fd309c30d8d8a3b0171e057c2b426a3d.

**Pull request closed without merging**
