### PR TITLE
LPS-125170

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I rebase the tina's [pr](https://github.com/dantewang/liferay-portal/pull/1853) and resend it.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Please rearrange the commits and resend:
1. don't keep Tina's change https://github.com/dantewang/liferay-portal/pull/1857/commits/45de288b170a01eac6058f0d1337dab1f3ffb9b3; instead, make a separate commit before adding the isolation level support to indicate that the queuing message listener should only care about serial background tasks without replying on existence of `lockKey` in the message. For example, you can query the executor and check its `isSerial()` and shortcut early when it's not.
2. Please put the changes to send the `lockKey` and `isolationLevel` in the same commit (so there's no separate https://github.com/dantewang/liferay-portal/pull/1857/commits/7e5cf172d94c11d139ab30333d12d487cb5b3a46).
3. Please review whether you still need https://github.com/dantewang/liferay-portal/pull/1857/commits/33c4093f163ee6abf35998d93ad69ae7d6a9daae after 1 & 2.

**Comment by yuhai** [comment]
@dantewang, got it, will do this.

**Pull request closed without merging**
