### PR TITLE
LPS-X Cache com.github.yuchi.semver.Range to avoid the heavy constructor

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
```
java.lang.RuntimeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal.Lock_' doesn't exist
```
Seems irrelevant.

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
The smoke test failure also shows up in https://github.com/shuyangzhou/liferay-portal/pull/6317

**Comment by slnn** [comment]
Test results on Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 18cf211 | 5020 | 125 | 410
PR | - | 5235 | 72.6 | 308

**Pull request closed without merging**
