### PR TITLE
[SD-migration] LPS-99123 mobile-device-rules-service

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1265. [See changes here.](https://github.com/dantewang/liferay-portal/compare/488794915979~1...488794915979)

**Pull request closed without merging**
