### PR TITLE
Integration Test Homework | master

### PR DESCRIPTION
**Pull request by Tim-Cao**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Tim-Cao/liferay-portal/pull/313. [See changes here.](https://github.com/dantewang/liferay-portal/compare/4c9c046889eb~1...4c9c046889eb)

**Comment by Tim-Cao** [comment]
@dantewang  Thanks. I learned a lot!

**Pull request closed without merging**
