### PR TITLE
Lps 149061 3 17

### PR DESCRIPTION
**Pull request by slnn**
Clean the commits and update the semantic version in portal-kernel/src/com/liferay/portal/kernel/json/packageinfo

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@GinsonRen Thanks!

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/478

**Comment by dantewang** [comment]
@zhangyan0701 I sent to https://github.com/liferay-core-infra/liferay-portal/pull/478, stopping the CI here.

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
