### PR TITLE
LPS-86836 Escape liferay home path when initializing Log4J

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Hi @jpince Is there anything wrong with CI? So many failures here...

**Comment by jpince** [comment]
@dantewang yes, there are a lot of issues at head right now failing functional, functional-upgrade, integration, and modules-integration. We're trying to diagnose and resolve right now.

**Pull request closed without merging**
