### PR TITLE
LPS 147815  Replace proxy created with ClassLoaderBeanHandler

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang，

Main Task: LPS-96117    Optimized Proxy creation replacement
Sub Task：LPS-147815  Replace proxy created with ClassLoaderBeanHandler

These classes are wrapper. We replaced with an optimized proxy creation function rather than using ASMWrapperUtil as ClassLoaderBeanHandler will reset ContextClassLoader during invoke function.

Thanks for checking！

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang Conflict as AxisExtender is removed from portal. Please resend.

**Pull request closed without merging**
