### PR TITLE
[deprecation round2] LPS-104913 modules part4

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@ChiZeLin Please split fixing usage and removing deprecation into separate commits and resend. By the way, in your first commit you removed a thing from template context, but I can see the key in some soy template files. Please double check.

**Pull request closed without merging**
