### PR TITLE
[Deprecations] LPS-106167 portal-kernel part10

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by yuhai** [comment]
@dantewang, I check the source-format-jdk8, semantic-versioning-jdk8, modules-unit-jdk8, modules-integration-mysql57-jdk8 and modules-compile-jdk8. These errors aren't related with the fix.

**Pull request closed without merging**
