### PR TITLE
LPS-160078 Do not use Spring extender service as dependency injection

### PR DESCRIPTION
**Pull request by ling-alan-huang**
```
java.lang.Exception: Found 4 formatting issues:
1: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-currency-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
2: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-price-list-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
3: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-product-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
4: Do not use Spring extender service as a dependency injection, use DS instead: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@dantewang without [d3322cb](https://github.com/dantewang/liferay-portal/pull/2253/commits/d3322cbb3aa5c0749eedfb0b3d016d9e1d2e750d) `ci:test:sf` will fail.

**Comment by dantewang** [comment]
@ling-alan-huang Yeah this is what we wanted, thank you!

**Comment by ling-alan-huang** [comment]
```
java.lang.Exception: Found 3 formatting issues:
1: Do not use Spring extender service as a dependency injection, use DS instead: /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-currency-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
2: Do not use Spring extender service as a dependency injection, use DS instead: /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-product-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)
3: Do not use Spring extender service as a dependency injection, use DS instead: /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-service/src/main/resources/META-INF/spring/module-spring.xml (SourceCheck:XMLSpringExtenderServiceCheck)

```

**Comment by dantewang** [comment]
@ling-alan-huang Yes, these are the only ones left.

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/1384

**Pull request closed without merging**
