### PR TITLE
LPS-129844 Remove guava?

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@vicnate5 @zhangyan0701 could you scan the results? This removes Google Guava dependency from lib/development. I didn't find anything in core directly depending on Guava so I removed it and let Ci check.

**Comment by vicnate5** [comment]
@dantewang We have a dependency on this for our Jenkins/test code: https://github.com/liferay/liferay-portal/blob/7a0ca52f73c9537da5e4867a228d103eaa3264fe/modules/test/jenkins-results-parser/src/main/java/com/liferay/jenkins/results/parser/JenkinsResultsParserUtil.java#L18

This code is used for restarting the app server on some of our poshi tests:
```
     [exec]     stop-app-server:
     [exec]     [beanshell] Securing standard error and out
     [exec]      [parallel] Exception in thread "Thread-2" java.lang.NoClassDefFoundError: com/google/common/io/CountingInputStream
     [exec]      [parallel] 	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil$5.run(JenkinsResultsParserUtil.java:3529)
     [exec]      [parallel] 	at java.lang.Thread.run(Thread.java:745)
     [exec]      [parallel] Caused by: java.lang.ClassNotFoundException: com.google.common.io.CountingInputStream
     [exec]      [parallel] 	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
     [exec]      [parallel] 	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1323)
     [exec]      [parallel] 	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1076)
     [exec]      [parallel] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]      [parallel] 	... 2 more
````
https://testray.liferay.com/reports/production/logs/2021-04/test-1-14/test-portal-acceptance-pullrequest(master)/8000/functional-tomcat90-sqlserver2019-jdk8/0/8/jenkins-console.txt.gz

FYI @pyoo47

**Comment by dantewang** [comment]
@vicnate5 Thanks! I'll just upgrade this for now.

**Pull request closed without merging**
