### PR TITLE
LPS-116282

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1883. [See changes here.](https://github.com/dantewang/liferay-portal/compare/01813db07c9c~5...01813db07c9c)

**Pull request closed without merging**
