### PR TITLE
LPS-89497

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/yuhai/liferay-portal/pull/208#issuecomment-587288432 requirement.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1719. [See changes here.](https://github.com/dantewang/liferay-portal/compare/41ddcd00ae6b~3...41ddcd00ae6b)

**Comment by yuhai** [comment]
just saw your changes. Thanks @dantewang

**Pull request closed without merging**
