### PR TITLE
LPS-52817 Using TwelveMonkeys IO libraries

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @dantewang 

This pull replaces the processing of images using ImageMagick by TwelveMonkeys. Could we run some performance tests to see if this has any impact in the performance tests? 
Specially the areas that might be affected are anything related with uploading images that has some processing (like thumbnails when uploading images in Documents and Media or the cropping of the user avatar)

Thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn

**Comment by dantewang** [comment]
@sergiogonzalez Please note that our test case does cover Document Library uploads, but it doesn't upload image files; instead, we are uploading raw bytes.

cc @shuyangzhou

**Comment by slnn** [comment]
Hi @sergiogonzalez,
Here is the test result on DL, from the test results, this Pull did not impact performance on DL:

Portal Version|	Git ID|Session Count|Mean Time(Login)|Mean Time(Add DL File)
------------ | ------------- | ------------ | ------------- |------------ 
On-Pull|4e587694|2672|61.6|452
BaseLine|	d697042|2706|61.0|459

cc @shuyangzhou @dantewang

**Comment by sergiogonzalez** [comment]
thx guys for testing this @dantewang @slnn @shuyangzhou :)

**Pull request closed without merging**
