### PR TITLE
LPS 161990

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-161990 Return null if the content type can not be determined (overriding Tika's default behavior which returns application/octet-stream
- LPS-151990 Also populate default types into _contentTypes

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:tck

**Comment by zhangyan0701** [comment]
There are some test failures in [com.liferay.portal.tika.test.MimeTypesImplTest](https://testray.liferay.com/home/-/testray/case_results/1969087251):
```
     [exec] com.liferay.portal.tika.test.MimeTypesImplTest > testOdt FAILED
     [exec]     org.junit.ComparisonFailure: expected:<application/[]vnd.oasis.opendocume...> but was:<application/[x-]vnd.oasis.opendocume...>
```

```
     [exec] com.liferay.portal.tika.test.MimeTypesImplTest > testPdf FAILED
     [exec]     org.junit.ComparisonFailure: expected:<application/[]pdf> but was:<application/[x-]pdf>
```

```
     [exec] com.liferay.portal.tika.test.MimeTypesImplTest > testRtf FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[application]/rtf> but was:<[text]/rtf>
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-32/test-portal-acceptance-pullrequest(master)/5633/modules-integration-mysql57-jdk8/0/10/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
