### PR TITLE
LPS-96692

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1473. [See changes here.](https://github.com/dantewang/liferay-portal/compare/de6525308d66~3...de6525308d66)

**Pull request closed without merging**
