### PR TITLE
LPS-129449 Make SampleSQLBuilder generate data for Commerce only when…

### PR DESCRIPTION
**Pull request by slnn**
… setting related properties

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Hi @dantewang @tinatian

On the head of master, SampleSQLBuilder will generated Commerce related data always no matter if user set related property.
 This pull just make SampleSQLBuilder generate commerce related data when commerce related property be setted.

By the way, NoSuchUserException appeared during portal startup with the data generated by SampleSQLBuilder, it caused by https://issues.liferay.com/browse/COMMERCE-4506, it seems that the logic of generating Commerce related data needs to be updated. 

`2021-03-20 01:18:15.229 ERROR [Portal Dependency Manager Component Executor--1][VerifyProcessTrackerOSGiCommands:297] com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the primary key 0
com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the primary key 0
	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:74)
	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands.executeVerifyProcesses(VerifyProcessTrackerOSGiCommands.java:294)
	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands$1.run(VerifyProcessTrackerOSGiCommands.java:346)
	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134)
	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands.executeVerifyProcesses(VerifyProcessTrackerOSGiCommands.java:341)
	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands._execute(VerifyProcessTrackerOSGiCommands.java:395)
	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands.access$200(VerifyProcessTrackerOSGiCommands.java:80)
	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands$VerifyServiceTrackerMapListener.keyEmitted(VerifyProcessTrackerOSGiCommands.java:470)
	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands$VerifyServiceTrackerMapListener.keyEmitted(VerifyProcessTrackerOSGiCommands.java:459)
	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:209)
	at com.liferay.osgi.service.tracker.collections.map.PropertyServiceReferenceMapper.map(PropertyServiceReferenceMapper.java:50)
	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:241)
	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:959)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168)
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:959)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168)
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at com.liferay.portal.spring.extender.internal.bean.ApplicationContextServicePublisherUtil._registerService(ApplicationContextServicePublisherUtil.java:174)
	at com.liferay.portal.spring.extender.internal.bean.ApplicationContextServicePublisherUtil.lambda$registerContext$0(ApplicationContextServicePublisherUtil.java:65)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at com.liferay.portal.spring.extender.internal.bean.ApplicationContextServicePublisherUtil.registerContext(ApplicationContextServicePublisherUtil.java:61)
	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator.start(ModuleApplicationContextRegistrator.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:157)
	at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:112)
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:638)
	at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:1783)
	at org.apache.felix.dm.impl.ComponentImpl.invokeStart(ComponentImpl.java:1281)
	at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1232)
	at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166)
	at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1337)
	at org.apache.felix.dm.impl.ComponentImpl.lambda$handleEvent$6(ComponentImpl.java:565)
	at org.apache.felix.dm.impl.DispatchExecutor.runTask(DispatchExecutor.java:182)
	at org.apache.felix.dm.impl.DispatchExecutor.run(DispatchExecutor.java:165)
	at org.apache.felix.dm.impl.DispatchExecutor.execute(DispatchExecutor.java:148)
	at org.apache.felix.dm.impl.DispatchExecutor.execute(DispatchExecutor.java:120)
	at org.apache.felix.dm.impl.ComponentImpl.schedule(ComponentImpl.java:1927)
	at org.apache.felix.dm.impl.ComponentImpl.handleEvent(ComponentImpl.java:561)
	at org.apache.felix.dm.impl.ServiceDependencyImpl.addedService(ServiceDependencyImpl.java:276)
	at org.apache.felix.dm.tracker.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1283)
	at org.apache.felix.dm.tracker.ServiceTracker$Tracked$2.execute(ServiceTracker.java:1399)
	at org.apache.felix.dm.tracker.ServiceTracker$Tracked$1.run(ServiceTracker.java:1196)
	at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
	at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
	at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
	at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChangedHideAspects(ServiceTracker.java:1202)
	at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1057)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at com.liferay.portal.spring.extender.internal.bean.ApplicationContextServicePublisherUtil._registerService(ApplicationContextServicePublisherUtil.java:174)
	at com.liferay.portal.spring.extender.internal.bean.ApplicationContextServicePublisherUtil.lambda$registerContext$0(ApplicationContextServicePublisherUtil.java:65)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at com.liferay.portal.spring.extender.internal.bean.ApplicationContextServicePublisherUtil.registerContext(ApplicationContextServicePublisherUtil.java:61)
	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator.start(ModuleApplicationContextRegistrator.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:157)
	at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:112)
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:638)
	at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:1783)
	at org.apache.felix.dm.impl.ComponentImpl.invokeStart(ComponentImpl.java:1281)
	at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1232)
	at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166)
	at org.apache.felix.dm.impl.ComponentImpl.lambda$start$2(ComponentImpl.java:502)
	at org.apache.felix.dm.impl.DispatchExecutor.runTask(DispatchExecutor.java:182)
	at org.apache.felix.dm.impl.DispatchExecutor.run(DispatchExecutor.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the primary key 0
	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:8638)
	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:8654)
	at com.liferay.portal.service.base.UserLocalServiceBaseImpl.getUser(UserLocalServiceBaseImpl.java:344)
	at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
	at com.sun.proxy.$Proxy1146.getUser(Unknown Source)
	at com.liferay.portal.kernel.service.UserLocalServiceWrapper.getUser(UserLocalServiceWrapper.java:1964)
	at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
	at com.sun.proxy.$Proxy1147.getUser(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy42.getUser(Unknown Source)
	at com.liferay.commerce.price.list.service.impl.CommercePriceListLocalServiceImpl.addCommercePriceList(CommercePriceListLocalServiceImpl.java:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:64)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:80)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy1573.addCommercePriceList(Unknown Source)
	at com.liferay.commerce.price.list.service.impl.CommercePriceListLocalServiceImpl.addCatalogBaseCommercePriceList(CommercePriceListLocalServiceImpl.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:80)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy1573.addCatalogBaseCommercePriceList(Unknown Source)
	at com.liferay.commerce.price.list.internal.helper.CommerceBasePriceListHelper._addCatalogBaseCommercePriceList(CommerceBasePriceListHelper.java:108)
	at com.liferay.commerce.price.list.internal.helper.CommerceBasePriceListHelper.addCatalogBaseCommercePriceList(CommerceBasePriceListHelper.java:65)
	at com.liferay.commerce.price.list.internal.verify.CommercePriceListServiceVerifyProcess.verifyBasePriceLists(CommercePriceListServiceVerifyProcess.java:56)
	at com.liferay.commerce.price.list.internal.verify.CommercePriceListServiceVerifyProcess.doVerify(CommercePriceListServiceVerifyProcess.java:42)
	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:71)
	... 122 more`

/cc @GinsonRen

Regards
Lily

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9876

**Pull request closed without merging**
