### PR TITLE
Lps 125421 1 4 v1

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang 

I moved all the translate sql processes from the build file to java, but we need to pass a module list to SampleSQLBuilder to specify which module's generic SQL templates will be translated.

Benchmark side changes please see: https://github.com/dantewang/liferay-benchmark-ee/pull/455

I also try another way to do the move avoid the module list,  please see way2: https://github.com/dantewang/liferay-portal/pull/1859

Which one do you prefer? Currently, the way1 in this pull worked well, but way2 caused some other issues and I'm still working on it.

/cc  @tinatian

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@slnn The module list can be a part of SampleSQLBuilder and doesn't need to
be customized without modifying SampleSQLBuilder.

Liferay Continuous Integration <notifications@github.com> 于 2021年1月4日周一
23:06写道：

**Comment by dantewang** [comment]
@slnn Or actually, you should only have access to the jars in the classpath built in benchmarks/build.xml, right? Then you don't need a list I think, because all the *-services jars in the classpath should need sql transformation.

**Comment by dantewang** [comment]
@slnn Let's go with your solution v2.

**Pull request closed without merging**
