### PR TITLE
LPS-103392 remove unused deprecations from util-java

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I don't find any usage in other parts. The pull only removes these deprecations without changing usage.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1351. [See changes here.](https://github.com/dantewang/liferay-portal/compare/ac905af785c0~2...ac905af785c0)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/8419. [See changes here.](https://github.com/dantewang/liferay-portal/compare/ac905af785c0~2...ac905af785c0)

**Pull request closed without merging**
