### PR TITLE
[portal-test-integration] LPS-102243

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Testing at https://github.com/dantewang/liferay-portal/pull/1435

**Pull request closed without merging**
