### PR TITLE
[deprecation round2] LPS-104401 portal-kernel part6

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@ChiZeLin See https://github.com/tinatian/liferay-portal/pull/1598, I didn't include the StringPool related changes since there are generated JSPs. Let's revisit it later.

**Pull request closed without merging**
