### PR TITLE
[DS-migration] LPS-98429 site-service

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
@dantewang force-pushed to remove spring.extender.api gradle references

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/817.

**Pull request closed without merging**
