### PR TITLE
[SD-migration] LPS-99323 wiki-service

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
@ChiZeLin Please resend. 1) Pass in BundleContext in activate(); 2) Replace ConfigurationProvider

**Pull request closed without merging**
