### PR TITLE
LPS-111215 Apply petra UnsyncStringWriter part1

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@ChiZelin reopen, this SF error is not related to your change.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1581. [See changes here.](https://github.com/dantewang/liferay-portal/compare/f235b97a4bb9~2...f235b97a4bb9)

**Pull request closed without merging**
