### PR TITLE
[PowerMock ] LPS-150071 Remove PowerMock in modules portal-osgi-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

This pull is to remove the PowerMock in modules. portal-osgi-web.  Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@JanisZhang As SF said, you forget ticket ID in the commit messages. Please force push.
By the way, the last one `WebXMLDefinitionLoaderTest` does not really use the mocked objects, so you just removed them, right?

**Comment by JanisZhang** [comment]
Yes, these are unused fields.

**Comment by dantewang** [comment]
@JanisZhang Forwarded.

See https://github.com/liferay-core-infra/liferay-portal/pull/494/commits/01938c2569ea68c327f1e649c094e5aea75f244a, I would prefer dummy proxy as it's not mocking any logic and the readability remains same.

Using `assertSame` ensures the implementation to be with a pair of simple setter/getter call without any extra logic, which I think is more strict.

**Pull request closed without merging**
