### PR TITLE
[PowerMock] LPS 151361 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

This pr is to remove powermock usages present in `BaseDDMTestCase`  and its related class located in `dynamic-data-mapping-test`.

The threw error like 

> com.liferay.dynamic.data.mapping.util.DDMFormTemplateSynchonizerTest > testAddRequiredFieldsIfTheyWereAddedInStructureAndModeIsCreate FAILED
    org.mockito.exceptions.misusing.InvalidUseOfMatchersException:
    Misplaced argument matcher detected here:

maybe caused by the `@Mock` annotation in `BaseDDMTestCase`, the fields init failed by using `@mock`  after removed `@RunWith(PowerMockRunner.class)`. 

https://issues.liferay.com/browse/LPS-151361 

Thanks for checking.

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang Nice! If all the modified unit tests passes you can send it to liferay-core-infra.

**Comment by JanisZhang** [comment]
Ok, I will double check and send to core infra. Thanks!

**Pull request closed without merging**
