### PR TITLE
Lps 69343 11 8

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
This pull contains https://github.com/dantewang/liferay-portal/pull/1389

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1581. [See changes here.](https://github.com/dantewang/liferay-portal/compare/38329acf1457~4...38329acf1457)

**Pull request closed without merging**
