### PR TITLE
[deprecations] LPS-103553 util-bridges

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, Except modules, portal-kernel, portal-impl, util-java, util-taglib, only util-bridges needs to be handled. portal-test and portal-test-integrations all use deprecations 7.2.x. In util-bridges, only this MVCPortlet class needs to be removed.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/8422.

**Pull request closed without merging**
