### PR TITLE
LPS-92597 upgrade test

### PR DESCRIPTION
**Pull request by yuhai**
The PR is extended from https://github.com/yuhai/liferay-portal/pull/130

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1059. [See changes here.](https://github.com/dantewang/liferay-portal/compare/4047496aa7fd~2...4047496aa7fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1291. [See changes here.](https://github.com/dantewang/liferay-portal/compare/4047496aa7fd~2...4047496aa7fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
