### PR TITLE
LPS-X hibernate 9 13 1

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr based on https://github.com/dantewang/liferay-portal/pull/2071 and rebased on master, upgrade Javassist to 3.28.0-GA.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai We can't keep this commit https://github.com/yuhai/liferay-portal/commit/1f55f186073fdd85a76afda9fa80153357371792 because it causes some customer code to break if the customer war container its own version of HIbernate.
We need to do 1) whether it's still needed to do the fix for JDK11 2) find a proper way to fix it if 1 is true.

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
resend it to https://github.com/dantewang/liferay-portal/pull/2090

**Pull request closed without merging**
