### PR TITLE
LPS-96274 Avoiding duplicate components

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @dantewang,

If you are happy with the results please forward to @patriciajeanperez. It is possible that functional tests are affected by these changes.

Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

I just pushed another commit fixing that horrible error!

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:messageboards

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please run MB tests for this. Thanks!

**Comment by dantewang** [comment]
@4lejandrito The complete test process is delayed due to electricity issues in our server room. The full result should be out tomorrow.

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
Hi @dantewang, I tested this pull and discovered that when you add a thread reply, it will not save as a reply. It will replace the thread content instead.

When a different user/guest replies to a thread, they will get an error that says "You do not have required permissions." I didn't see any console or browser errors.



@4lejandrito

**Comment by dantewang** [comment]
Thanks @patriciajeanperez 

@4lejandrito Due to server room electricity issues on our side, we haven't finished performance tests on this pull. We'll wait for your update since there are functional issues. Thanks!

**Comment by 4lejandrito** [comment]
Hi guys,

I'll be out of the office til Monday.

Even if there are potential functional issues I recommend you guys go ahead with the performance testing (unless those issues affect you directly) so that I have all the info on Monday.

Thanks!

**Comment by 4lejandrito** [comment]
I can reproduce the issue, looking into it right now. Thanks a lot @patriciajeanperez!

**Comment by 4lejandrito** [comment]
See https://github.com/dantewang/liferay-portal/pull/1168.

**Pull request closed without merging**
