### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@yuhai Sorry I forgot to say about one thing last time. Please don't add the "hasResourceTag()" method. This method just opens the file as XML document and see if there's certain tag. But we can just call "read*()" because when there's no such tag the read method will just return silently.

So it should be:

- When in spring-extender, read model resources, then read any existing portlet resources -- the latter will be disabled in "strict mode" we want to add in the future; (`readModelResources()` and `readPortletResources()`)
- When in portlet tracker, read model resources (which will be disabled in strict mode), and portlet resources per portlet deployment; (`readPortletResource()`, `readModelResources()`)
- When in war handling, it should be like what's in portlet tracker, just we don't apply strict mode in the future here; (`readPortletResource()`, `readModelResources()`)
- When in core (ResourceActionsImpl.afterPropertiesSet) just read both. (`readPortletResources()`, `readModelResources()`)

Please also re-arrange the commits to be more clear that we're directly adding these APIs and applying. Reduce middle-state commits as long as they are not important.

**Comment by yuhai** [comment]
@dantewang, got it

**Pull request closed without merging**
