### PR TITLE
LPS-X Hibernate Reabse 7-29

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results once they finish? Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Seems network issue:
[beanshell] java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.UnknownHostException: test-1-30.liferay.com

Will try one more time.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Failures in ci:test:relevant should be flaky. They passed in ci:test:default.

**Comment by zhangyan0701** [comment]
**Unique failures in ci:test:**

### **1. Portal failed to connect to PostgreSQL.**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1550991082&testrayRunId=1550991341
Full Jenkins console: https://testray.liferay.com/reports/production/logs/2021-08/test-1-29/test-portal-acceptance-pullrequest(master)/45/functional-tomcat90-postgresql11-jdk8/0/11/jenkins-console.txt.gz
```
 [parallel] 2021-08-02 09:12:17.679 INFO  [main][DialectDetector:164] Using dialect org.hibernate.dialect.PostgreSQL10Dialect for PostgreSQL 11.2
 [parallel] 2021-08-02 09:12:17.688 ERROR [main][PortalContextLoaderListener:69] java.lang.NullPointerException
 [parallel] java.lang.NullPointerException: null
```

**In upgrade tests, error in upgrade log:**
Full Jenkins console: https://testray.liferay.com/reports/production/logs/2021-08/test-1-29/test-portal-acceptance-pullrequest(master)/45/functional-tomcat90-postgresql11-jdk8/0/6/jenkins-console.txt.gz
```
     [java] 2021-08-02 09:48:00.601 INFO  [main][DialectDetector:164] Using dialect org.hibernate.dialect.PostgreSQL10Dialect for PostgreSQL 11.2
     [java] java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown dialect type org.hibernate.dialect.PostgreSQL10Dialect
```
### **2. Web Content is not available with SQLServer.**
https://testray.liferay.com/home/-/testray/case_results/1550993057
Full portal log: https://testray.liferay.com/reports/production/logs/2021-08/test-1-29/test-portal-acceptance-pullrequest(master)/45/functional-tomcat90-sqlserver2017-jdk8/0/6/liferay-log.txt.gz

webcontent

```
2021-08-02 10:14:33.863 ERROR [http-nio-8080-exec-1][PortletRequestDispatcherImpl:304] Unable to dispatch request: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.RuntimeException: Failed to parse sql for (  SELECT DIST top(?)INCT folderId AS modelFolderId, '' AS articleId, JournalFolder.name AS title, 0 AS version, 1 AS modelFolder, JournalFolder.createDate AS displayDate, JournalFolder.modifiedDate AS modifiedDate FROM JournalFolder WHERE (JournalFolder.groupId = ?) AND (JournalFolder.status != ?)  AND JournalFolder.parentFolderId = ?    ) UNION ALL (  SELECT JournalArticle.folderId AS modelFolderId, JournalArticle.articleId AS articleId, JournalArticleLocalization.title AS title, JournalArticle.version AS version, 0 AS modelFolder, JournalArticle.displayDate AS displayDate, JournalArticle.modifiedDate AS modifiedDate FROM (SELECT JournalArticle.groupId AS groupId, JournalArticle.articleId AS articleId, MAX(JournalArticle.version) AS version FROM JournalArticle WHERE (JournalArticle.groupId = ?) AND (JournalArticle.classNameId = 0) AND (  (JournalArticle.status != ?))  AND JournalArticle.folderId = ?  GROUP BY JournalArticle.groupId, JournalArticle.folderId, JournalArticle.articleId) TEMP_TABLE INNER JOIN JournalArticle ON (TEMP_TABLE.groupId = JournalArticle.groupId) AND (TEMP_TABLE.articleId = JournalArticle.articleId) AND (TEMP_TABLE.version = JournalArticle.version) LEFT JOIN JournalArticleLocalization ON (JournalArticle.id_ = JournalArticleLocalization.articlePK) AND (JournalArticleLocalization.languageId = ?)   ) ORDER BY modelFolder DESC, modifiedDate DESC
```

### **3. Upgrade failed with SQLServer.**
https://testray.liferay.com/home/-/testray/case_results/1550993048
Full Jenkins log: https://testray.liferay.com/reports/production/logs/2021-08/test-1-29/test-portal-acceptance-pullrequest(master)/45/functional-tomcat90-sqlserver2017-jdk8/0/2/jenkins-console.txt.gz

     **[java] 2021-08-02 00:29:36.381 ERROR [Portal Dependency Manager Component Executor--1][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.asset.display.page.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute query**

### **4. Missing Plus icon in Fragment Collection with SQLServer.**
https://testray.liferay.com/home/-/testray/case_results/1550993073
Full portal log: https://testray.liferay.com/reports/production/logs/2021-08/test-1-29/test-portal-acceptance-pullrequest(master)/45/functional-tomcat90-sqlserver2019-jdk8/0/0/liferay-log.txt.gz

fragments
```
2021-08-02 20:17:30.155 ERROR [http-nio-8080-exec-15][IncludeTag:128] Current URL /group/test-site-name/~/control_panel/manage/-/fragments/fragment_collection/56448?p_p_auth=xSCVQip8 generates exception: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.RuntimeException: Failed to parse sql for (  SELECT DIST top(?)INCT FragmentComposition.fragmentCompositionId AS fragmentCompositionId, 0 AS fragmentEntryId, FragmentComposition.createDate AS createDate, FragmentComposition.name AS name FROM FragmentComposition WHERE (FragmentComposition.groupId = ?) AND (FragmentComposition.fragmentCollectionId = ?) AND (FragmentComposition.status != ?)   ) UNION ALL (  SELECT DISTINCT 0 AS fragmentCompositionId, FragmentEntry.fragmentEntryId AS fragmentEntryId, FragmentEntry.createDate AS createDate, FragmentEntry.name AS name FROM FragmentEntry WHERE (FragmentEntry.groupId = ?) AND (FragmentEntry.fragmentCollectionId = ?) AND ((FragmentEntry.head = 1) OR (FragmentEntry.headId = FragmentEntry.fragmentEntryId)) AND (FragmentEntry.status != ?)   ) ORDER BY createDate ASC
```

### **5. Page Templates is not ready.**
https://testray.liferay.com/home/-/testray/case_results/1550992479
Full portal log: https://testray.liferay.com/reports/production/logs/2021-08/test-1-29/test-portal-acceptance-pullrequest(master)/45/functional-tomcat90-mysql57-jdk8/9/23/liferay-log.txt.gz
Page Templates
```
2021-08-02 09:16:11.028 ERROR [default-14][BatchingBatch:130] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20100-com.liferay.portal.kernel.model.LayoutPrototype-4-com.life' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-02 09:16:11.040 ERROR [default-14][SqlExceptionHelper:142] Duplicate entry '20100-com.liferay.portal.kernel.model.LayoutPrototype-4-com.life' for key 'IX_A9FF4B2C'
2021-08-02 09:16:11.054 ERROR [Portal Dependency Manager Component Executor--1][PortletTracker:406] Portlet com_liferay_layout_page_template_admin_web_portlet_LayoutPageTemplatesPortlet from com.liferay.layout.page.template.admin.web_2.0.19 [1021] failed to initialize
com.liferay.portal.kernel.exception.PortalException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch
```

### **6. Some integration tests failed.**
a. [com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest](https://testray.liferay.com/home/-/testray/case_results/1550994108)
b. [com.liferay.portlet.expando.service.persistence.test.ExpandoColumnPersistenceTest](https://testray.liferay.com/home/-/testray/case_results/1550995113)
c. [com.liferay.portlet.expando.service.persistence.test.ExpandoTablePersistenceTest](https://testray.liferay.com/home/-/testray/case_results/1550995129)

**Pull request closed without merging**
