### PR TITLE
Spi

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, si:test:sf is passed and ci:test:relevant is running from https://github.com/yuhai/liferay-portal/pull/211

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@yuhai 
Could you rearrange the commits, taking relationship of code logic into consideration? Basically we remove usages first, and then deprecate a class. I would like to see the first commits to clean up whatever integrates the portal resiliency feature into portal. After cleaning up such logic, you should be left with a lot of unused classes in portal resiliency packages, which you can directly remove or deprecate.
Also, please add the properties you removed to VerifyProperties and document breaking change.

Thanks

**Comment by yuhai** [comment]
@dantewang, I will do this.

**Pull request closed without merging**
