### PR TITLE
LPS-162830 Support automatic registration of ConfigurationBeanDeclaration services

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-162830](https://issues.liferay.com/browse/LPS-162830).

@dantewang I spoke with @tinatian about these changes causing `SpringExtenderDependencyManagerTest` to time out waiting for the countdown latch. She recommended I send them your way to investigate a test fix. Please let me know if you have any questions. Thank you!

/cc @pei-jung

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @drewbrokke I was unable to lock down the root cause in today, but I did notice something wrong.

So the test logic in `_captureLog` ensures the `UnavailableComponentScanner`'s scanning thread is not running by changing configuration and using logger output. For example, on my machine, the component is not started by default. When running the test logic,

1. Config the logger and setup a custom list as a listener to listen for log entry appending;
2. Set the configuration to `interval=1` to trigger activation of the component;
3. The component's `activate` method will start the scanner thread;
4. After the first run of scanning is done, a log (either info or warn) will be appended; this log is not about "stopping the thread";
5. The listener sets the configuration to empty to trigger deactivation of the component, saves the logging thread (which is exactly the scanner thread) for further waiting, and unlocks the count down latch;
6. The component's deactivate method interrupts the scanner thread;
7. The test waits the scanner thread to join

The problem is that, on this pull request, the behavior changes.

Setting configuration to `interval=1` does trigger the activation of the component. However, when `ConfigurationManager$UpdateConfiguration` executes, it determines that the bundle location is changed. So a `CM_LOCATION_CHANGED` event is fired. As a result, right after SCR activates the component, it receives the `CM_LOCATION_CHANGED` event and deletes the configuration and deactivates the component. This happens so quick, so that the component's scanner thread doesn't have any chance to output the log entry the test expects; instead, the test's listener only gets the `stopping the thread` log message.

And I took a look at the location change. The original bundle location is `null`, and the new location is `/path-to-tomcat/osgi/portal/com.liferay.portal.configuration.settings.jar`.

I may not be able to find more before my day ends. Based on the above findings, could you double check your logic to see why the location is changed?


By the way, on master, when modifying the configuration, `ConfigurationBeanManagedService.updated` is not called; while on this pull, it's called. It seems that all configurations will come with a `ConfigurationBeanManagedService`? Is that expected?

**Comment by dantewang** [comment]
cc @tinatian

**Comment by drewbrokke** [comment]
This was just a shot in the dark, but changing the setup to this seemed to resolve the issue:
```
		_unavailableComponentScannerConfiguration =
			_configurationAdmin.getConfiguration(
				"com.liferay.portal.osgi.debug.spring.extender.internal." +
					"configuration.UnavailableComponentScannerConfiguration",
				StringPool.QUESTION);
```

**Comment by drewbrokke** [comment]
@dantewang @tinatian FYI see my comment above.

**Comment by dantewang** [comment]
@drewbrokke 

Looking at the JavaDoc:

```
Get an existing Configuration object from the persistent store, or create a new Configuration object.
If a Configuration with this PID already exists in Configuration Admin service return it. The location parameter is ignored in this case though it is still used for a security check.
Else, return a new Configuration object. This new object is bound to the location and the properties are set to null. If the location parameter is null, it will be set when a Managed Service with the corresponding PID is registered for the first time. If the location starts with ? then the configuration is bound to all targets that are registered with the corresponding PID.
```

So I think this is the case. When there's a managed service for the configuration, which is the new behavior with this PR, there will be a location change internally in config admin. This change caused the issue I saw during debugging. If the location provided is "?", then it will not be changed.

My concern is that I'm not sure whether this `null` in the test is a protection on-purpose. 

@tinatian

**Comment by drewbrokke** [comment]
@dantewang it's a good question - I am not sure. My original plan was to provide an opt-out for cases where a ManagedService is not desired, but since we don't often restrict configs by location in the portal context, I decided to go for simplicity.

I cannot speak to the intention of the `null` in the test case. If it's incidental then this should be an ok change, but if it's on-purpose then we should probably re-implement some sort of opt-out.

**Comment by dantewang** [comment]
@drewbrokke I will close this PR for now, as long as the change doesn't introduce other issue, I think it's OK to modify the test in this way.

**Pull request closed without merging**
