### PR TITLE
Lps 61495 reupdate ftl 1 14

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by dantewang** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by slnn** [comment]
ci:retest

**Comment by dantewang** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/2338. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
