### PR TITLE
LPS-84181 Apply petra StringBundler to classes directly

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1741. [See changes here.](https://github.com/dantewang/liferay-portal/compare/da4c05608e6b~1...da4c05608e6b)

**Pull request closed without merging**
