### PR TITLE
Lps 105694 8 12 1

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/493. [See changes here.](https://github.com/dantewang/liferay-portal/compare/fb2956e6934d~5...fb2956e6934d)

**Pull request closed without merging**
