### PR TITLE
LPS 137136 jdom 8 11 2

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-137136 Update rometools to 1.16.0
- LPS-137136 Replace Liferay patched Rome 1.0 usages with Rometools
- LPS-137136 Remove rome.jar
- LPS-137136 Replace jdom usages with jdom2
- LPS-137136 Remove jdom.jar
- LPS-137136 Don't import jdom 1 in these modules
- LPS-137136 Remove the patch module for old Rome

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results?

**Comment by zhangyan0701** [comment]
@dantewang 

No related failures.

**Pull request closed without merging**
