### PR TITLE
TCK3-CI 4-9

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@vsingleton @michaelhashimoto Hey guys, the env var "MAVEN_HOME" seems to be missing on CI. Any idea?

**Comment by dantewang** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test:tck

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
ci:close

**Comment by michaelhashimoto** [comment]
I'm trying this out here:
https://github.com/michaelhashimoto/liferay-portal/pull/1210

**Comment by michaelhashimoto** [comment]
Hi Dante & Vernon,

I'm sorry, I think there were some updates that I had not considered.

I'm looking to make these updates related to the errors seen in these test
runs in these tickets:
https://issues.liferay.com/browse/LRQA-40155
https://issues.liferay.com/browse/LRQA-40144

I'm testing these changes out here:
https://github.com/michaelhashimoto/liferay-portal/pull/1210

I'll let you know when we have updates merged into upstream.

Thanks for your understanding!

-Michael

**Pull request closed without merging**
