### PR TITLE
[StringBundler] LPS-84182 Apply Petra-String StringBundler to method argument and return value part2

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@ChiZelin Could you double check whether the package of `AssetEntryFinderImpl` is exported? If not, maybe we can directly replace the usage, not keeping deprecated versions.

**Comment by ChiZelin** [comment]
Please see https://github.com/dantewang/liferay-portal/pull/1545

**Pull request closed without merging**
