### PR TITLE
LPS LPS 142278 portal lib

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-142278 Should download into shielded container lib dir
- LPS-142278 Should copy portal jars from shielded container lib dir in BaseDeployer
- LPS-142278 Apply to calls to *Deployers in build-dist.xml
- LPS-142278 Remove old logic that sets LIFERAY_LIB_PORTAL_DIR by servlet context; shielded container dir is already set this way. Also, this was added by LPS-52665 to resolve JRuby issue when deploying portal using unexploded war - JRuby is no longer used and our customer facing documents never mention using unexploded war now.
- LPS-142278 Remove sysproperty for portal lib dir, this was added by LPS-65693 (a161a2a957de85c3eb6591d7921ca082a628a9a4) for integration tests in core, but these tests have been moved to modules.
- LPS-142278 Can we also remove this one?
- LPS-142278 Deprecate portal lib dir

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@zhangyan0701 Could you help review the test results of ci-test-default and ci-test-environments? Thanks!

**Comment by zhangyan0701** [comment]
Have checked the results of ci-test-default and ci-test-environments, no related failures found.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Pull request closed without merging**
