### PR TITLE
LPS-124222 Patch daisydiff.jar | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**
@dantewang https://github.com/brianchandotcom/liferay-portal/pull/97361#issuecomment-754781116

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
@dantewang I tested it locally and it worked well.

**Comment by dantewang** [comment]
@ChiZeLin Wrong symbolic name, see other patch modules, please resend.

**Pull request closed without merging**
