### PR TITLE
LPS-91938 packageinfo

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@slnn Could you please run this pull on all test cases? Thanks!

**Comment by dantewang** [comment]
ci:test

**Comment by slnn** [comment]
Here are test results:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 7cc2774 | 15925 | 260 | 64.2 | -
PR-1046 | - | 16044 | 263 | 65.4 | 0.7472527473

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 7cc2774 | 20681 | 393 | 151 | -
PR-1046 | - | 20630 | 405 | 151 | -0.2466031623

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 7cc2774 | 7648 | 154 | 319 | -
PR-1046 | - | 7769 | 154 | 318 | 1.582112971

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 7cc2774 | 5270 | 58.3 | 253 | -
PR-1046 | - | 5240 | 76.6 | 288 | -0.569259962

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 7cc2774 | 8496 | 270 | 628 | -
PR-1046 | - | 8778 | 285 | 613 | 3.31920904

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 7cc2774 | 9214 | 145 | 157 | -
PR-1046 | - | 9251 | 132 | 154 | 0.4015628392

**Pull request closed without merging**
