### PR TITLE
Inline Http Servlet - Dev branch

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
Commits before https://github.com/dantewang/liferay-portal/pull/2305/commits/16d71c4bf0e6a13c8ef9724f508d2e0c2931a71a passed tests before.

**Comment by dantewang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
There is one failure seems related.
Test [portal-license-smoke-mysql57-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2363663098) failed with bellow error:
```
check-license:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7046: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7080: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12717: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-common.xml:1072: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-common.xml:444: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-common.xml:452: File does not contain enterprise copyright information: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-http-servlet/src/main/java/com/liferay/portal/osgi/web/http/servlet/ExtendedHttpService.java
```
Full Jenkins console:
https://testray.liferay.com/reports/production/logs/2023-06/test-1-40/test-portal-acceptance-pullrequest(master)/3740/portal-license-smoke-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 I see. This one itself can be ignored, but does it prevent other license related tests from running? If so, I'll add the Liferay copyright part to bypass it.

**Comment by zhangyan0701** [comment]
@dantewang There is no other license related tests running on acceptance, I will trigger license test suite and check if there are broken tests.

**Comment by zhangyan0701** [comment]
ci:test:license

**Comment by dantewang** [comment]
ci:test

Force pushed: 2023-06-30 11:24

@zhangyan0701 Let's skip license test failures for now.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Comment by dantewang** [comment]
ci:test

Force pushed: 2023-07-03 15:13

Additional commits:
LPS-184766 Public Package: move session listener registration into the HttpServletService tracker so that we don't need to expose HttpSessionTrackerUtil
LPS-184766 Split into -api and -impl modules

**Comment by liuxingye** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test

Force pushed: 2023-07-04 13:05

New commits:

LPS-184766 Activator: Simplify, Liferay always use Servlet 3.0+
LPS-184766 Activator: Use HashMap(Dictionary)Builder to clean up
LPS-184766 Activator: SF, inner class to buy space
LPS-184766 Activator: SF, remove unused parameter in HttpTuple and in… 
LPS-184766 SF, remove unused class
LPS-184766 HttpServiceRuntimeImpl: SF, inline
LPS-184766 Activator: Use an alternative way to get the service.id se… 
LPS-184766 Activator & HttpTuple: Make HttpTuple to take an array of … 
LPS-184766 Activator & HttpServiceRuntimeImpl: Move default servlet c…

**Comment by liuxingye** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test:environments

@liuxingye Triggering a ci-test-environments run for better coverage on other app servers.

**Comment by liuxingye** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test

Force pushed 2023-7-17 14:33

LPS-184766 SF, no need to be a list
LPS-184766 SF, rename HttpTuple to HttpServiceBag and move
LPS-184766 Clean up, remove interfaces that are not part of the whiteboard spec

**Comment by dantewang** [comment]
ci:test:environments

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:test

LPS-184766 HttpServiceRuntimeImpl: SF, split implementation of HttpSe… 
LPS-184766 HttpServiceRuntimeController: Use generic to simplify cent… 
LPS-184766 HttpServiceRuntimeController: SF, move ServiceTrackerCusto… 
LPS-184766 HttpServiceRuntimeController: Move HttpService related log… 
LPS-184766 HttpServiceImpl: SF, use ConcurrentHashMap
LPS-184766 HttpServiceImpl: SF, no need to use Map with Bundle as key

**Comment by dantewang** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test

LPS-184766 HttpServiceRuntimeController & ContextController: SF, remo… 
LPS-184766 Const: clean up constants, move or replace.

**Comment by dantewang** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
Force pushed only.

A experimental PR is at https://github.com/dantewang/liferay-portal/pull/2309, please check that one instead, thanks!

**Pull request closed without merging**
