### PR TITLE
LPS 184766 Inline Equinox Http Dev New test 1

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-184766 Create project files
- LPS-184766 Copy over Equinox Http Servlet source code (version 1.2.2.v20211118-0920.LIFERAY-PATCHED-1), no change
- LPS-184766 Move packages, no logic change
- LPS-184766 Add SF suppressions
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet and com.liferay.portal.osgi.web.http.servlet.context
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal
- LPS-184766 Rename Activator to HttpServletBundleActivator and add it to bnd.bnd
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.context
- LPS-184766 SF and modify StringPlus to return String[] to fit most of its usages; this also prepares for the next commit.
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.customizer
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.error (unused classes are removed)
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.registration
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.servlet
- LPS-184766 SF, remove BooleanPlus and use GetterUtil instead
- LPS-184766 SF, remove ServiceProperties.parseBoolean() and use GetterUtil instead
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.util (unused classes are removed)
- LPS-184766 SF, logging
- LPS-184766 SF, inline
- LPS-184766 SF, use HashMapDictionary and HashMapDictionaryBuilder
- LPS-184766 SF, use ReflectionUtil#throwException
- LPS-184766 SF, clean up
- LPS-184766 Apply, make portal-osgi-web-wab-extender depend on portal-osgi-web-http-servlet
- LPS-184766 Fix CI failures on JDK11: manually add imports that are in the original jar, but not automatically calculated when building the inlined module
- LPS-184766 Activator: Remove code that manually registers ProxyServlet; only register it via OSGi
- LPS-184766 Activator: Remove registered but unused OSGi service properties
- LPS-184766 Activator: Remove internal property, it's not part of the public standard nor used by Liferay
- LPS-184766 Activator: Simplify, track HttpServiceServlet directly
- LPS-184766 Activator: Simplify, use anonymous class
- LPS-184766 Activator: Change constant content
- LPS-184766 Activator: Move package, no logic change
- LPS-184766 Activator & Public Package: add a new interface to register the endpoint, register ProxyServlet internally, and remove HttpServiceServlet which extends the internal class
- LPS-184766 Activator & Public Package: move session listener registration into the HttpServletService tracker so that we don't need to expose HttpSessionTrackerUtil
- LPS-184766 Split into -api and -impl modules
- LPS-184766 Activator: Use HashMap(Dictionary)Builder to clean up
- LPS-184766 Activator: SF, inner class to buy space
- LPS-184766 Activator: SF, remove unused parameter in HttpTuple and inline in HttpServletImplBundleActivator
- LPS-184766 SF, remove unused class
- LPS-184766 HttpServiceRuntimeImpl: SF, inline
- LPS-184766 Activator: Use an alternative way to get the service.id set by the framework which is required by the Whiteboard spec, prepare for next
- LPS-184766 Activator & HttpTuple: Make HttpTuple to take an array of service registrations and unregister in reverse order when destroy
- LPS-184766 Activator & HttpServiceRuntimeImpl: Move default servlet context helper registration to the activator
- LPS-184766 SF, no need to be a list
- LPS-184766 SF, rename HttpTuple to HttpServiceBag and move
- LPS-184766 Clean up, remove interfaces that are not part of the whiteboard spec
- LPS-184766 HttpServiceRuntimeImpl: SF, split implementation of HttpServiceRuntime and other logic into 2 classes so that we don't pass an impl class everywhere.
- LPS-184766 HttpServiceRuntimeController: Use generic to simplify centralized Failed*DTO recording, and move other DTO logic to HttpServiceRuntimeImpl
- LPS-184766 HttpServiceRuntimeController: SF, move ServiceTrackerCustomizer logic inner class
- LPS-184766 HttpServiceRuntimeController: Move HttpService related logic to HttpServiceImpl, prepare for next
- LPS-184766 HttpServiceImpl: SF, use ConcurrentHashMap
- LPS-184766 HttpServiceImpl: No need to use map with Bundle as key. We registered a service factory instead of a single HttpServiceImpl instance, and each bundle will get its own instance of HttpServiceImpl, so it's naturally managed per bundle.
- LPS-184766 HttpServiceRuntimeController & ContextController: SF, remove unnecessary tracking and consuming bundle context as the support has been removed
- LPS-184766 Const: clean up constants, move or replace.
- LPS-184766 HttpServiceImpl: SF, inline HttpServiceObjectRegistration as inner class
- LPS-184766 HttpServiceRuntimeController: SF, avoid repeatedly calculating ContextControllers based on the same requestURI.
- LPS-184766 HttpServiceRuntimeController: Delegate DispatchTargets lookup to ContextController to avoid duplicated code

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the smoke result? I'll merge the change back to the main PR and run ci-test there if no relevant error in smoke.

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Could you take a look at the smoke result? I'll merge the change back to the main PR and run ci-test there if no relevant error in smoke.

The failure in smoke test is not related.

**Pull request closed without merging**
