### PR TITLE
[Bug] LPS-103369

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I add the last commit to solve the below [issue](https://github.com/dantewang/liferay-portal/pull/1809#issuecomment-732059125). 

1. Set virtual.hosts.default.site.name= in portal-ext.
2. Login as Test user whose preferred language is en_US.
3. Open URL http://localhost:8080/web/guest/home.
4. Open URL http://localhost:8080/zh_CN/.
Result: URL change to http://localhost:8080/en/web/guest and page still displays in English. This is wrong.

The property virtual.hosts.default.site.name explanation
If this property is not set, then the default URL(http://localhost:8080) may be http://localhost:8080/web/guest/home.

When using http://localhost:8080/zh_CN/, during I18nServlet handle twice, it will use homeURL http://localhost:8080/web/guest and this will be handled by I18nFilter. Actually, the logic shouldn't be handled by I18nFilter if URL includes locale. And homeURL should be http://localhost:8080/zh_CN/web/guest.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Why does setting `virtual.hosts.default.site.name` to empty affect the url we request -- which logic does it affect? Why do you do your fix in `getHomeURL` method if the property affects the behavior?

**Comment by yuhai** [comment]
@dantewang, setting the property to empty, after I18nServlet handled twice, it will forward the [index.jsp](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/index.jsp#L29-L64) it will use homeURL as redirectURL, and this will be filter by I18nFilter. I18nFilter will use user Locale when requestedLanguageId is not equal with userLanguageId. Due to the url has included zh locale (zh is not user locale), so the issue happened.

**Pull request closed without merging**
