### PR TITLE
LPS-62006 Rendering a user search happens faster than user indexing can complete

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-62006](https://issues.liferay.com/browse/LPS-62006).<br><br>Hi Dante, Shuyang instructed me to send these changes to you for performance testing.  We essentially switched from using an index search to a database-only search in the user assignments page of the User Groups Admin Portlet.

If everything is satisfactory, please forward to Jorge Ferrer. Thanks!

/cc @shuyangzhou @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by dantewang** [comment]
@slnn

**Comment by slnn** [comment]
Hi all,
Test results on Login:
Portal Version | Session Count |  Mean Time of Log In
------------ | ------------- |-------------
Base Line |10132|243
LPS-62006 | 10074|227

@dantewang @shuyangzhou

**Comment by drewbrokke** [comment]
Sorry, I'm not familiar with the processes over there in performance :)  Are there additional checks to wait for, or do the results mean I'm ok to send to Brian?

**Comment by dantewang** [comment]
Hi Drew,

Sorry I forgot to comment. I think it's ok to send.

Drew Brokke <notifications@github.com>于2016年2月2日周二 07:51写道：

**Pull request closed without merging**
