### PR TITLE
LPS X Remove S3FileCache

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Remove usages of S3FileCache by always return wrapped S3ObjectInputStream
- LPS-X Remove S3FileCache and S3FileCacheCleanUpTest
- LPS-X Remove the S3FileCache related configurations

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:dl-store

**Comment by dantewang** [comment]
ci:test:document

**Comment by dantewang** [comment]
Hi @zhangyan0701, this PR removes the `S3FileCache` so that all file downloads from `S3Store` are direct now. Could you test manually whether this breaks any of the `S3Store` functionality, and update any function test that may be affected as I removed 2 configuration items? Thanks!

**Comment by zhangyan0701** [comment]
There is a test failure seems related:

**[central-requirements-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2021458740) failed with error:**
```
    [junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Incorrect configuration of dependency {testCompile group: "com.amazonaws", name: "aws-java-sdk-s3", version: "1.12.262"} in modules/apps/portal-store/portal-store-s3-test/build.gradle, use one of these instead: "testIntegrationCompile", "testIntegrationRuntime"
    [junit] junit.framework.AssertionFailedError: Incorrect configuration of dependency {testCompile group: "com.amazonaws", name: "aws-java-sdk-s3", version: "1.12.262"} in modules/apps/portal-store/portal-store-s3-test/build.gradle, use one of these instead: "testIntegrationCompile", "testIntegrationRuntime"
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1512)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:68)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:402)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:376)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:374)
```

**One functional test failed due to the groovy script keeps running:** [LocalFile.DocumentLibraryStore#S3ConnectionDoesNotLeakWhenServingFileAsStream](https://testray.liferay.com/home/-/testray/case_results/2021454313)

The script is:
```
			import com.liferay.document.library.kernel.service.DLFileEntryLocalServiceUtil;
			import com.liferay.document.library.kernel.store.DLStoreUtil;
 
			List fileEntries = DLFileEntryLocalServiceUtil.getFileEntries(0,1);
 
			fileEntries.each { fileEntry ->
				(1..60).each {
					try {
						InputStream is = DLStoreUtil.getFileAsStream(fileEntry.getCompanyId(), fileEntry.getRepositoryId(), fileEntry.getName())
					} 
					catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
```
If I force stop it, below error will thrown in console:
`com.liferay.portal.kernel.exception.SystemException: Unable to execute HTTP request: Timeout waiting for connection from pool`

The configs that you removed are still in file https://github.com/dantewang/liferay-portal/blob/LPS-X-Remove-S3FileCache/portal-impl/src/portal-osgi-configuration.properties#L4824, should they be removed from this file as well?

And I send you the changes on tests in https://github.com/dantewang/liferay-portal/pull/2268 in case you want to re-run tests with them.

Manually testing passed on local. The S3 store functionality still works.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks! I'll double check.

**Pull request closed without merging**
