### PR TITLE
Lps 119985 part 1 new

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/501. [See changes here.](https://github.com/dantewang/liferay-portal/compare/23c91f6f8725~4...23c91f6f8725)

**Pull request closed without merging**
