### PR TITLE
LPS-111104

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/214. [See changes here.](https://github.com/dantewang/liferay-portal/compare/5cbf62753551~1...5cbf62753551)

**Pull request closed without merging**
