### PR TITLE
LPS-86868 Only print error stack at debug level

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/870. [See changes here.](https://github.com/dantewang/liferay-portal/compare/6dc60af0ac2a~2...6dc60af0ac2a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1103. [See changes here.](https://github.com/dantewang/liferay-portal/compare/5919d86d3f86~2...5919d86d3f86) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
