### PR TITLE
LPS-98383 Migrate reading-time-service to use DS insteand of Spring

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
@dantewang Pushed packageinfo

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/806.

**Pull request closed without merging**
