### PR TITLE
LPS X Xalan 3

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Remove Xalan package dependency introduced by FreeMarker, which will use Jaxen as XPath engine instead (see https://freemarker.apache.org/docs/xgui_imperative_formal.html) if Xalan is not available.
- LPS-X Remove Xalan dependency introduced by JasperReport by switching to Jaxen as XPath engine, according to https://community.jaspersoft.com/wiki/xml-data-source-very-slow-parse
- LPS-X Remove Xalan dependencies from saml-opensaml-integration. Xalan is not needed, as app-sec team tested in LPS-144760.
- LPS-X Remove Xalan from Gradle class path
- LPS-X Update patch for DaisyDiff to avoid depending on Xalan. Use XML API and Xerces instead.
- LPS-X FAKE GRADLE CACHE
- LPS-X Apply new version of DaisyDiff
- LPS-X Make Xalan compileInclude for XSLTemplate as it's the only module explicitly requiring Xalan; see LPS-89354. Will do security mitigation in another ticket.
- LPS-X Remove Xalan from libs
- LPS-X Remove Xalan from IDE files
- LPS-X Remove Xalan from other files
- LPS-X Update lib versions
- LPS-X Remove Xalan dependencies from saml-opensaml-integration (addition)

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:reports

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:saml

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@zhangyan0701 Could you check the test results? Thanks!

**Comment by zhangyan0701** [comment]
@Hijky Could you take a look at the results?

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Pull request closed without merging**
