### PR TITLE
COMMERCE-4996 Updated changes to commerce data generation

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-4996

### CODE REVIEW

**Comment by dsitu** [comment]
@dantewang Changes and updates for data generation.

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please review this PR first, thanks!

**Comment by slnn** [comment]
Hi @dsitu 

It seems that this pull does not only include the changes for SampleSQLBuilder, but also includes other changes on Commerce APIs, such as `CommerceShipmentItemLocalServiceImpl` and  `CommerceShipmentFDSDataProvider`,  normally, if we want to make SampleSQLBuilder generate sample data for a test case, we only add support on SampleSQLBuilder side, we do not change the logicn in the product code. Do we really need these changes for  `CommerceShipmentItemLocalServiceImpl` and `CommerceShipmentFDSDataProvider`  when add support on SampleSQLBuilder? 


Thanks
Lily

**Comment by dsitu** [comment]
Hey @slnn, I can move the commerce changes into a separate PR.

**Comment by dsitu** [comment]
ci:test:relevant

**Pull request closed without merging**
