### PR TITLE
Lps 105218 7 14

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by slnn** [comment]
Hi @dantewang 

Move these constants that just be used only once back to DataFactory, I have force push the new commit.


Lily

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Pull request closed without merging**
