### PR TITLE
LPS-84316

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang 

Please let me know if you have other concerns.

Please check the performance test result with the fix: https://github.com/slnn/liferay-portal/pull/328

Thanks,
Hai

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai I'll wait for this test:relevant to finish. But could you split your first commit into two and resend:
1. Extra NormalizerUtil logic from ParamUtil
2. Apply NormalizerUtil to StringUtil.shorten

**Comment by dantewang** [comment]
ci result looks good.

**Comment by yuhai** [comment]
please see https://github.com/dantewang/liferay-portal/pull/822 for the changes.

**Pull request closed without merging**
