### PR TITLE
LPS-102169 Copy DLAppTestUtil to document-library-test-util and deprecate the original one

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersionic

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1508. [See changes here.](https://github.com/dantewang/liferay-portal/compare/0098ff468e38~1...0098ff468e38)

**Pull request closed without merging**
