### PR TITLE
[deprecation round2] LPS-104829 modules part1

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1611. [See changes here.](https://github.com/dantewang/liferay-portal/compare/fc73b228219d~2...fc73b228219d)

**Pull request closed without merging**
