### PR TITLE
LPS 128873 Hibernate 2022 3 7

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-128873 Upgrade to Hibernate-core 5.6.3.Final and add required dependencies
- LPS-128873 Auto SF to apply
- LPS-128873 Apply spring-orm patch in LPS-100343 for Hibernate 5: check in original class
- LPS-128873 Apply spring-orm patch in LPS-100343 for Hibernate 5: instead of patching for Hibernate 3, patch for Hibernate 5 now
- LPS-128873 Apply spring-orm patch in LPS-100343 for Hibernate 5: FAKE GRADLE CACHE
- LPS-128873 Apply spring-orm patch in LPS-100343 for Hibernate 5: apply
- LPS-128873 Build lib versions
- LPS-128873 Migrate custom types, we should implement UserType rather than CompositeUserType. CompositeUserType is just a workaround to fix LPS-17984, now we are upgrading to hibernate 5.X, no longer need the workaround anymore.
- LPS-128873 Migrate StringClobType, it is replaced by MaterializedClobType in Hibernate 4; MaterializedClobType#isEqual(Object, Object) method is final, so we have to override the type descriptor which this method delegates to.
- LPS-128873 Migrate LockModeTranslator: org.hibernate.LockMode#parse(String) -> org.hibernate.LockMode#fromExternalForm(String)
- LPS-128873 Migrate CacheModeTranslator: org.hibernate.CacheMode#parse(String) -> org.hibernate.CacheMode#interpretExternalSetting(String)
- LPS-128873 Migrate IDGenerator: org.hibernate.engine.SessionImplementor -> org.hibernate.engine.spi.SharedSessionContractImplementor
- LPS-128873 Migrate SessionFactoryImpl: org.hibernate.engine.SessionFactoryImplementor -> org.hibernate.engine.spi.SessionFactoryImplementor
- LPS-128873 Migrate event listeners: 1) update packages; 2) avoid using deprecated methods in event listeners
- LPS-128873 Migrate customized property accessors: PropertyAccessor -> PropertyAccessStrategy that works as factory of PropertyAccess
- LPS-128873 Migrate SessionImpl: 1) Session#close() in Hibernate 5 no longer returns Connection, return null here to quick fail; 2) SessionFactoryImplementor#getEntityPersister(String) -> MetamodelImplementor#entityPersister(Class); 3) constructor of EntityKey
- LPS-128873 Migrate: remove FieldInterceptionHelperUtil as the bytecode instrumentation code has been removed from Hibernate and replaced by another infrastructure, see HHH-10280
- LPS-128873 Migrate PortalHibernateConfiguration: move logic to CTModelIntegrator
- LPS-128873 Migrate PortalHibernateConfiguration: move event listeners logic to integrator
- LPS-128873 Migrate PortalHibernateConfiguration: move newConfiguration logic to afterPropertiesSet and buildSessionFactory
- LPS-128873 Migrate PortalHibernateConfiguration: remove the optimization for QueryPlanCache and related property. The related Hibernate issue HHH-4959 has been fixed since 5.2.6, so this particular optimization should not be needed for now.
- LPS-128873 Migrate PortalHibernateConfiguration: move this to buildSessionFactory, as it needs the Configuration (LocalSessionFactoryBuilder)
- LPS-128873 Migrate PortalHibernateConfiguration: Remove deprecated property, use new property
- LPS-128873 Migrate PortalHibernateConfiguration: remove Javassist related code since Hibernate only uses ByteBuddy since 5.6.3
- LPS-128873 Update usage of PortalHibernateConfiguration
- LPS-128873 Migrate: use default DialectResolver as fallback. The proper way to integrate into Hibernate is to customize the DialectFactory service during creating of session factory, but in Liferay there are code depending on the DialectDetector to determine database type outside Hibernate, executed even before initialization of Hibernate. If we go with the Hibernate 5 native way, the execution order during startup needs to be adjusted which would be a big change.
- LPS-128873 Migrate: update packages to org.springframework.orm.hibernate5
- LPS-128873 Migrate: use SessionBuilder from SessionFactory to create session from provided connection
- LPS-128873 Migrate: package name
- LPS-128873 Migrate: portal-spring-extender-impl; the javax.persistence-api is required for compiling as Hibernate 5 SessionFactory extends javax.persistence.EntityManagerFactory
- LPS-128873 Migrate: portal-lock-service; the javax.persistence-api is required for compiling as some Hibernate 5 Exceptions extend javax.persistence.PersistenceException
- LPS-128873 Migrate: StatisticsService
- LPS-128873 Migrate VerifySessionFactoryWrapper: org.hibernate.internal.SessionFactoryImpl#getAllClassMetadata() -> org.hibernate.internal.SessionFactoryImpl#getMetamodel()
- LPS-128873 Fix zero based positional query parameters, see https://hibernate.atlassian.net/browse/HHH-13414
- LPS-128873 Fix no transaction issue
- LPS-128873 Fix compile for test
- LPS-128873 Fix compile for aspectj-hibernate-stale-object-state
- LPS-128873 Fix compile for aspectj-hibernate-unexpected-row-count
- LPS-128873 Fix, auto flush is not working for portlet session as it is considered not in active transaction, add logic to check spring's thread local as what's did in hibernate 3.6
- LPS-128873 Fix exception check in LockLocalServiceTest
- LPS-128873 Fix log assertion by adding expected log on BatchingBatch because SQLExceptions in BatchingBatch are logged twice -- see https://github.com/hibernate/hibernate-orm/pull/1544
- LPS-128873 Fix exception handling and assertion; when the error "Row was updated or deleted by another transaction" happened, hibernate.core-3.6.10 throw StaleObjectStateException(refer to AbstractEntityPersister.check()). However, hibernate-core-5.5.2 throw StaleStateException(refer to Expectations#BasicExpectation.checkBatched()).
- LPS-128873 Fix LockLocalServiceImpl: Now Hibernate throws a PersistenceException containing a ConstraintViolationException
- LPS-128873 Fix compile for test
- LPS-128873 Fix failure of ViewCountEntryLocalServiceTest caused by double logging (BatchingBatch)
- LPS-128873 [NEED REVISIT] Workaround: solve Hibernate lazy proxy issue "java.lang.NoClassDefFoundError: org/hibernate/proxy/HibernateProxy" during portal startup.
- LPS-128873 Override the method to use LegacyLimitHandler so that it can invoke our SQLServerLimitStringUtil.getLimitString() to generate the sql. Otherwise, it will use SQLServer2005LimitHandler. This will cause JournalFolderServiceImpl.getFoldersAndArticles() generated sql parse failed. But LegacyLimitHandler is deprecated, only LegacyLimitHandler may invoke the getLimitString() method when processing sql.
- LPS-128873 PostgreSQLDialect was deprecated by PostgreSQL82Dialect. In addition, hibernate 5.5.2 provides one class to return different dialects based on different database versions, please see org.hibernate.dialect.Database. In our case, it will return PostgreSQL10Dialect, and PostgreSQL10Dialect extends PostgreSQL82Dialect. So use PostgreSQL10Dialect as the condition.
- LPS-128873 When transaction Callback executes, TransactionDefinition is PROPAGATION_SUPPORTS and autoCommit of connection is true. For POSTGRESQL, at that time, when resultSet.getClob() executes, the error "org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode." will happen. The reason is that the autoCommit of connection is true. Please see org.postgresql.largeobject.LargeObjectManager.open(). For example, the issue will happen when CompanyLocalServiceImpl#registerCompany executes. The commit sets SqlTypeDescriptor when the database is POSTGRESQL. And then only copy DEFAULT of org.hibernate.type.descriptor.sql.ClobTypeDescriptor as one subClass and let subClass to replace DEFAULT(no logic change). The next commit will add the fix in the subClass.
- LPS-128873 Set autoCommit of connection for false when getClob() executes to avoid the issue happening.
- LPS-128873 Bypass the strict entity check in Hibernate 5 for Session#contains. In Hibernate 3, if the object's class is not recognized as an entity class (FooImpl in our case), it just returns false; while in Hibernate 5, it throws IllegalArgumentException.
- LPS-128873 SemVer
- LPS-128873 Attempt to fix PostgreSQL error: org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode; the previous fix does not take binder into consideration.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look when the tests on this PR finish? Basically the only new change compared to [the last one](https://github.com/dantewang/liferay-portal/pull/2171) is to try to fix the PostgreSQL test failure.

Please ignore any SF error, thanks!

**Comment by dantewang** [comment]
cc @vicnate5 @tinatian @yuhai

**Comment by zhangyan0701** [comment]
The PostgreSQL environments all failed out. 

**1. There are many WARNs like below during portal stratup:**  
```
[parallel] 2022-03-07 09:03:35.639 WARN  [Portal Dependency Manager Component Executor--1][PortalInstanceLifecycleListenerManagerImpl:162] Unable to register portal instance {"mvccVersion": 1, "companyId": 20099, "userId": 0, "userName": "", "createDate": "Mon Mar 07 09:03:09 GMT 2022", "modifiedDate": "Mon Mar 07 09:03:09 GMT 2022", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "system": false, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": ""}
 [parallel] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.HibernateException: Unable to access lob stream
```
Example test: https://testray.liferay.com/home/-/testray/case_results/1628438504
Full log: https://testray.liferay.com/reports/production/logs/2022-03/test-1-31/test-portal-acceptance-pullrequest(master)/2461/functional-tomcat90-postgresql134-jdk8/2/2/liferay-log.txt.gz?authuser=0

2. Many ERRORs when upgrade:
```
     [java] 2022-03-07 09:08:23.502 ERROR [main][SqlExceptionHelper:142] Bad value for type long : 
     [java] 2022-03-07 09:08:24.136 ERROR [Portal Dependency Manager Component Executor--1][SqlExceptionHelper:142] Bad value for type long : <?xml version="1.0"?>
```
Example test: https://testray.liferay.com/home/-/testray/case_results/1628437518
Full Jenkins console: https://testray.liferay.com/reports/production/logs/2022-03/test-1-31/test-portal-acceptance-pullrequest(master)/2461/functional-tomcat90-postgresql134-jdk8/1/19/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 Force pushed. The PR didn't successfully apply my fix/workaround. Now it should at least start portal without issue. Re-triggering tests.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@vicnate5 Summer is on PTO. Could you double check whether there's any unique failure on PostgreSQL, especially those caused by "org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode"?

**Comment by koor4356** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@dantewang We had issues getting the full test results here, CI team is working on a solution.

**Comment by vicnate5** [comment]
@dantewang See PSQL errors on upgrade here:
https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/721/functional-tomcat90-postgresql134-jdk8/1/10/liferay-log.txt.gz?authuser=0

https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/721/functional-tomcat90-postgresql134-jdk8/1/0/liferay-log.txt.gz?authuser=0
https://testray.liferay.com/home/-/testray/case_results/1630725394

Also on upgrade tests:
https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/721/functional-tomcat90-postgresql134-jdk8/1/19/jenkins-console.txt.gz?authuser=0

I am not sure what manual steps are causing these. @zhangyan0701 might have time to look into it more deeply today if you need.

**Comment by dantewang** [comment]
@vicnate5 OK I'll look into these. There's no error with "org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode", right?

**Comment by dantewang** [comment]
@zhangyan0701 Please let me know the manual steps, thanks!

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Hi @dantewang 

The error "Large Objects may not be used in auto-commit mode" is no longer occurs, and the startup error in https://github.com/dantewang/liferay-portal/pull/2173#issuecomment-1061444533 is fixed.

But there are still two issues:

**1.  Error "Bad value for type long" during upgrade.**
Examples:
Upgrade from 62: https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/721/functional-tomcat90-postgresql134-jdk8/1/14/jenkins-console.txt.gz?authuser=0
Upgrade from 70: https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/721/functional-tomcat90-postgresql134-jdk8/1/17/jenkins-console.txt.gz?authuser=0

**2. Enable local staging fail with error:**
```
     [exec] 2022-03-08 09:40:42.706 ERROR [http-nio-8080-exec-4][SqlExceptionHelper:142] ERROR: operator does not exist: text ~~ bigint
     [exec]   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
     [exec]   Position: 200
     [exec] 2022-03-08 09:40:42.710 ERROR [http-nio-8080-exec-4][BasePersistenceImpl:633] Caught unexpected exception
     [exec] org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```
The same error also happens when publish remote staging.

Steps:
- Add a new Site.
- Go to Liferay Site > Publishing > Staging.
- Enable remote staging between Liferay Site and the new site.
- Go to Home page.
- Click Publish to Live. 

Full portal log: https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/721/functional-tomcat90-postgresql134-jdk8/1/22/liferay-log.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 Thanks! I'll look into the new errors.

**Pull request closed without merging**
