### PR TITLE
LPS-88710

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I tested the fix by referring to the steps from https://github.com/tinatian/liferay-portal/pull/1165#issue-243920208 and scheduler worked. In addition, I tried to publish one scheduler event about staging, it also worked.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/1490

**Pull request closed without merging**
