### PR TITLE
Lps 69343 11 4

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/454. [See changes here.](https://github.com/dantewang/liferay-portal/compare/aeadad3bb45a~8...aeadad3bb45a)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1569. [See changes here.](https://github.com/dantewang/liferay-portal/compare/aeadad3bb45a~8...aeadad3bb45a)

**Pull request closed without merging**
