### PR TITLE
LPS-101479 Move BaseLocalServiceTreeTestCase to portal-local-service-tree-test-util | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1501. [See changes here.](https://github.com/dantewang/liferay-portal/compare/2ccb4e77e128~1...2ccb4e77e128)

**Pull request closed without merging**
