### PR TITLE
LPS-X hibernate upgrade

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the [errors ](https://github.com/dantewang/liferay-portal/pull/2131#issuecomment-1000255675) should been resolved for now.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@dantewang, I tested these integration test errors. I can't reproduce them on my side. I just push the change about Semantic Versioning change and then rerun ci test.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai You'll need to look into the CI log to see the real error. InvocationTargetException usually serves as a wrapper of the real exception thrown by the invoked method during reflection operations.

**Pull request closed without merging**
