### PR TITLE
LPS-98626

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, BaseSubscriptionLocalizedContentTestCase uses LayoutTestUtil.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, the test errors seem not related with the fix. I start to another PR without any detailed changes to run "ci:test:relevant"

**Comment by dantewang** [comment]
Just started reviewing :)

**Pull request closed without merging**
