### PR TITLE
[Deprecation] LPS-106103 Remove PortalExecutorManager of portal-kernel

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the https://github.com/dantewang/liferay-portal/pull/1472 requirement.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by yuhai** [comment]
@dantewang, I just check source-format-jdk8, modules-integration-mysql57-jdk8 and modules-compile-jdk8. These errors aren't related with the fix.

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/1654

**Pull request closed without merging**
