### PR TITLE
LPS-142048

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the below jar exists version are different between portal and modules.

```
asm-analysis  module(num:1) used 4.1 version
asm-tree      module(num:1) used 4.1 version
asm-util      module(num:2) used 4.1 version
asm 		  module(num:4) used different versions
jaxws-api 	  module(num:1) used 2.3.1 version, higher than portal/lib
bcprov-jdk15on, in modules, they used 1.69 version by using compileInclude. 
```

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2437
I only rearranged commits.

**Pull request closed without merging**
