### PR TITLE
Lps 76916

### PR DESCRIPTION
**Pull request by tinatian**
Hi Dante,

Could you please confirm if my change break anything?

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:reopen

**Comment by dantewang** [comment]
Fetched <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
ci:retest

**Comment by dantewang** [comment]
@tinatian 

CI updated to Firefox 52 ESR, causing Portlet 3.0 TCK unable to be executed, as the Selenium it uses only supports Firefox 45. As a result, I can't verify the result of all the V2 test cases.

However, I ran V2AddlPortletTests locally and all test cases pass. I think it's good to go.

Thanks!

**Pull request closed without merging**
