### PR TITLE
LPS-115547

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by lipusz** [comment]
Hello, @yxingwu 

This LPS should address only the portal-remote usages, we have a different LPS for the document library: https://issues.liferay.com/browse/LPS-115659

Also, changes to "portal-remote" should be sent to the App Sec team for review (Carlos or Stian).

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
