### PR TITLE
[deprecation round2] LPS-104401 portal-kernel part6

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/ChiZeLin/liferay-portal/pull/236. [See changes here.](https://github.com/dantewang/liferay-portal/compare/46c7b6596ab9~1...46c7b6596ab9)

**Pull request closed without merging**
