### PR TITLE
LPS-81983 Fix HtmlTopTagTest, com.liferay.portal.kernel.servlet.taglib.util.OutputData#addData is removed, use its replacement

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1713.

**Pull request closed without merging**
