### PR TITLE
LPS-120376 Import SampleSQLBuilder generated data into DB

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang @tinatian

For usage please see description in https://issues.liferay.com/browse/LPS-120376

Note: with currently head of master please apply these fix to use the new import function on portal side locally:
1>Apply this fix of SampleSQLBuilder:https://github.com/brianchandotcom/liferay-portal/pull/93706
2>Set 1 to property "sample.sql.max.group.count" in the property file  ${PortalSource}/benchmarks/benchmarks.properties as the issue https://issues.liferay.com/browse/LPS-104499, the origin fix for the issue in https://github.com/dantewang/liferay-portal/pull/1412 is not enough for the current head of master, I am fixing it now.

Thanks
Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Update: 

The issue of https://issues.liferay.com/browse/LPS-104499 be fixed in https://github.com/dantewang/liferay-portal/pull/1732

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@slnn Could you make the following changes:

1. Put your db-builder related logic (in `merge-create-statements`) inside `build-sample-sql` because I think they are also part of building the sample sql. They are needed both for benchmark usage and for your tool usage, so let's just keep it in one place. You should put the logic before the `<delete dir="build" quiet="true" />` line.
2. Please reuse the `build` dir to extract sqls. With 1, you shouldn't need to `unzip` the Sample SQL Builder jar again.
3. Merge `merge-statements` target into `exec-sql` target, because it merges sqls when `sample.sql.output.merge` is false. This should be purely for the tool and not for benchmark. No need to keep a separate target here.

After doing this the benchmark project will need to be updated to remove the db-builder related logic.

**Comment by slnn** [comment]
Please see:
Portal Side:https://github.com/dantewang/liferay-portal/pull/1737
Benchmark project: https://github.com/dantewang/liferay-benchmark-ee/pull/424

**Pull request closed without merging**
