### PR TITLE
LPS-87059

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang

This PR only moves java classes of the package com.liferay.portal.template from portal-impl to module.

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
pmd and modules-unit arr real failures, please fix and resend.

Liferay Continuous Integration <notifications@github.com> 于 2018年11月12日周一
11:16写道：

**Pull request closed without merging**
