### PR TITLE
LPS 151623 9 1

### PR DESCRIPTION
**Pull request by dantewang**
- Revert LPS-112397
- LPS-151623 Create a local service wrapper to do Layout specific validation
- LPS-151623 Make sure the wrapper is always invoked

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:friendly-url

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the friend-url test results? Thanks!

**Comment by dantewang** [comment]
@zhangyan0701 You can ignore any semantic versioning or SF error.

**Comment by zhangyan0701** [comment]
**There is a test failure seems related.**

[com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest](https://testray.liferay.com/home/-/testray/case_results/1964704047) failed with below error:
`com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest.testInitialize: com.liferay.friendly.url.exception.NoSuchFriendlyURLEntryLocalizationException: No FriendlyURLEntryLocalization exists with the key {groupId=43391, classNameId=44010, urlTitle=/test-objects-layout}`

Full console:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-29/test-portal-acceptance-pullrequest(master)/4387/modules-integration-mysql57-jdk8_stable/0/2/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
ci:test:friendly-url

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
