### PR TITLE
LPS-96692

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, compare with https://github.com/dantewang/liferay-portal/pull/1192. I add the last four commits. For the commit https://github.com/dantewang/liferay-portal/commit/f5ddfefabf638085b5345a3e381ade21bbcc4f87, I saw Tina changed this (refer to https://github.com/shuyangzhou/liferay-portal/pull/8076).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by yuhai** [comment]
ci:test:backend-hypersonic

**Pull request closed without merging**
