### PR TITLE
LPS-101479 Move BaseLocalServiceTreeTestCase to portal-local-service-tree-test-util

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@ChiZelin Please copy to modules and deprecate the original one. Let's do this for all the leftover `*TestCase` classes you work on.

**Pull request closed without merging**
