### PR TITLE
[portal-test-integration] LPS-102317 Move SynchronousMailTestRule and com.liferay.portal.test.mail.* to portal-test

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1531. [See changes here.](https://github.com/dantewang/liferay-portal/compare/077e83c61f18~1...077e83c61f18)

**Pull request closed without merging**
