### PR TITLE
LPS-126999

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by yxingwu** [comment]
ci:test:backend

**Comment by dantewang** [comment]
@yxingwu 
1. Could you use SF to auto enforce the versions in modules?
2. What does the patch originally do? Why is the patch useless? Please write something like "it was to fix security issue which is already fixed in latest versions blah blah blah" in the commit message.

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by yxingwu** [comment]
ci:retest:relevant

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2147.

**Pull request closed without merging**
