### PR TITLE
LPS-131933

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yxingwu We were trying to upgrade all jackson dependencies to 2.12.3 but we needed other teams to review the change because of behavior changes. See https://github.com/liferay-commerce/liferay-portal/pull/962

**Comment by jpince** [comment]
@yxingwu @dantewang Brian Chan already applied these changes across portal. The product teams will follow up on any negative impact to their components. 

Can you please verify that all needed changes were made?
```
commit 8023fb2f6e911e64b82ce735db5e775fdfdbfe16
Author: Brian Chan <brian.chan@liferay.com>
Date:   Tue Aug 3 09:17:41 2021 -0300

    LPS-136264 LPS-136265 auto apply (I didn't make these changes manually)

commit 359bb7779e46a183c1a482c8724bb9e52399680d
Author: Brian Chan <brian.chan@liferay.com>
Date:   Tue Aug 3 09:16:36 2021 -0300

    LPS-136264 LPS-136265 Patch 2.10.5.1 to avoid JBoss issue found in LPS-107256 ec45e18019d58ba1f7abf11744af4ff3002cfeae
```

**Comment by jpince** [comment]
Update: please review all changes made under [LPS-136265](https://issues.liferay.com/browse/LPS-136265), especially https://github.com/liferay/liferay-portal/commit/606e1456c5e5c711fbb0505df011058fa7f9bb89

**Comment by dantewang** [comment]
@jpince We also have a pull in review at Tina's list to upgrade it directly to 2.12.x. See https://github.com/tinatian/liferay-portal/pull/2330

**Pull request closed without merging**
