### PR TITLE
Lps 86761

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1084. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6973

**Pull request closed without merging**
