### PR TITLE
LPS-57105 Update PortalImplUnitTest

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:help

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1641. [See changes here.](https://github.com/dantewang/liferay-portal/compare/d1af2517f30c~1...d1af2517f30c)

**Pull request closed without merging**
