### PR TITLE
LPS 128873 Hibernate 2022 3 10 with inline StringClobType

### PR DESCRIPTION
**Pull request by dantewang**
Keeping Hibernate 3 StringClobType logic for backwards and PostgreSQL compatibility.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@vicnate5 @zhangyan0701

**Comment by zhangyan0701** [comment]
Hi @dantewang 

The PostgreSQL issues no longer occur.

But most upgrade tests failed on WebSphere environment,
```
     [java] 2022-03-10 14:11:48.077 ERROR [main][DBUpgrader:79] null
     [java] java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.util.InfrastructureUtil#0' defined in class path resource [META-INF/infrastructure-spring.xml]: Cannot resolve reference to bean 'liferayTransactionManager' while setting bean property 'transactionManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liferayTransactionManager' defined in class path resource [META-INF/hibernate-spring.xml]: Cannot resolve reference to bean 'liferayHibernateSessionFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liferayHibernateSessionFactory' defined in class path resource [META-INF/hibernate-spring.xml]: Invocation of init method failed; nested exception is java.lang.SecurityException: class "javax.persistence.TableGenerators"'s signer information does not match signer information of other classes in the same package
```
The above errors thrown during the upgrade.
Testray link: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1631707996&testrayRunId=1631723857
Example full console: https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2151/functional-upgrade-websphere90-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 Are there other relevant issues you found from these runs? Like the DB2 & Oracle upgrade error you saw in https://github.com/dantewang/liferay-portal/pull/2171#issuecomment-1058139053?

**Comment by dantewang** [comment]
@zhangyan0701 Oh I didn't see the last line of your comment. Thank you very much!

**Pull request closed without merging**
