### PR TITLE
LPS-130177 Change so that we only have to do one pass to the document instead of two. Also, remove the check for portletName since it's already included in the validation

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by GinsonRen** [comment]
@jkappler @dantewang There is diff result for login:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 9d77b57d | 10338 | 175 | 29 | -
PR-1966 | - | 10513 | 171 | 27.5 | 1.69%

**Comment by dantewang** [comment]
@jkappler According to the result, this can be an improvement but not significant.

**Comment by jkappler** [comment]
Hi @dantewang, thanks. We'll keep working on it. Since there was a small improvement for a page that has basic fragments it will improve a bit in other more heavy pages. We'll send these changes keep working on more optimization

**Comment by dantewang** [comment]
@jkappler Sure! Thanks!

**Pull request closed without merging**
