### PR TITLE
[DS-migration] LPS-99323 wiki-service | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/ChiZeLin/liferay-portal/pull/199. [See changes here.](https://github.com/dantewang/liferay-portal/compare/e5dd7e3bf5ee~1...e5dd7e3bf5ee)

**Pull request closed without merging**
