### PR TITLE
Lps 83275 12 1

### PR DESCRIPTION
**Pull request by slnn**
Hi @GinsonRen 

This pull enablt the search bar in the site SampleSQLBuilder generated, Could you please run a diff with this pull?

Please do these:
1> Use the daily monitor runtime test results as a baseline
2>Apply this pull on portal side and apply this pull: https://github.com/slnn/liferay-benchmark-ee/pull/149 on benchmark side to build database for all test cases
3>Run tests for all test cases with the new databases

With the new dbs, you can see the search bar and a search page when you visit the site-1

Search bar:
search-bar
Search page:
search-page

/cc @tinatian

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2052. [See changes here.](https://github.com/dantewang/liferay-portal/compare/e39da39b8f66~2...e39da39b8f66)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/514. [See changes here.](https://github.com/dantewang/liferay-portal/compare/3a11a2672595~2...3a11a2672595)

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1828

**Pull request closed without merging**
