### PR TITLE
LPS-118542 Log4JUtilTest

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I revert your last sf. Because if we don't define one logger's level in config file, it will inherited from its parent level, but its level is null. For example, the logger "com.liferay.hello.world", and we didn't config it in config file. For log4j, it will use root logger's level to judge, for jdkLogger, its parent logger default level is INFO, but its level is null.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, I push-force the changes. Please review.

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2105. [See changes here.](https://github.com/dantewang/liferay-portal/compare/f5dde0b7beb3~5...f5dde0b7beb3)

**Pull request closed without merging**
