### PR TITLE
[deprecation] LPS-103868 portal-kernel part1

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, for the change in LayoutImportController class of the commit https://github.com/dantewang/liferay-portal/commit/87142da99709e46dcd570d0089d21a185d0eb668, the exportImportProcessId field is set in https://github.com/yuhai/liferay-portal/blob/LPS-103868/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/LayoutImportController.java#L658-L660

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull Sent to Tina

**Pull request closed without merging**
