### PR TITLE
LPS-135031 Also add test source to IDE project files

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reevaluate:1187401_6107

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
