### PR TITLE
Lps151639 move properties

### PR DESCRIPTION
**Pull request by W2jx**
Hi dante,
I moved some properties in this pr, but portal can't run now, I will fix it.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@W2jx I think most of the failures are due to the custom portal-ext.properties used by CI. It has `liferay.home`. We need to also update these usages before we can verify the change on CI.

**Comment by W2jx** [comment]
This PR contains all the parameters to be moved, and to verify that the test passes.  And my next step is to optimize the method such as setEnvProperties

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test

**Comment by dantewang** [comment]
@W2jx For env related methods, since you moved it from existing code, you can keep what's it now. For the property-reference resolving code, you can at least make sure it matches all the SF rules. Please try to send out a PR with commits rearranged before end of today.

**Pull request closed without merging**
