### PR TITLE
LPS-84181 Apply petra StringBundler | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1534. [See changes here.](https://github.com/dantewang/liferay-portal/compare/e48dc238f5a5~2...e48dc238f5a5)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1535. [See changes here.](https://github.com/dantewang/liferay-portal/compare/544398e004d5~1...544398e004d5)

**Pull request closed without merging**
