### PR TITLE
LPS-97456 Moving imports to the top

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @dantewang,

I've removed all the code from `init.jsp` and made sure we only create settings once. I would like you to test this approach and see if the performance is better. 

If the numbers are good I prefer this approach to usign fragments. Fragments end up being "pasted" inside the including file and are hard to reuse since they depend on the context. Also, fragments cannot be included inside loops because each variable they declare will be duplicated.

Please let me know your thoughts.

Thanks!

**Comment by dantewang** [comment]
@slnn Please run Blog on this pull, thanks!

**Comment by dantewang** [comment]
@4lejandrito Thanks for the pull.

It's normal if this pull's number is lower than the pull with more aggressive changes. For example, each Blogs front page view will result in 20 includes of `view_entry_content.jsp` which means 20 calls to the 3 `DefineObjectsTag`s (60 in total). Also, setting and getting attributes on the request can also be a big one because of the quantity and the complicated wrapping of the request. But let's wait for the test result, if the number is good then I won't care about that overhead.

On the other hand, I understand the point that full JSP with IncludeTag is easier to reuse. But is it really applicable to `view_entry_content_detail.jsp`.? It's only used in one place, `view_entry.jsp`, and it's not in a loop.

By the way, we can remove the search container related code from `view_entry_content_detail.jsp` because in its context no one sets the search container into the request.

**Comment by slnn** [comment]
Hi all,
Here are test results on Blog with qa env:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 83fd0be | 5711 | 118 | 373
pr-1178 | - | 6018 | 89.8 | 311


Lily

**Comment by dantewang** [comment]
@4lejandrito So most of the overhead was from configuration object creation. The result is good, thanks!

**Comment by 4lejandrito** [comment]
See https://github.com/dantewang/liferay-portal/pull/1179

**Pull request closed without merging**
