### PR TITLE
[Bug] LPS-120281

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please check the reproduced steps from [comment ](https://issues.liferay.com/browse/LPS-120281?focusedCommentId=2321104&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2321104).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2047.

**Pull request closed without merging**
