### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the PR only adds fix for LPS-114310. LPS-114310 added one method to include the case that its source is template and its content needs to be replaced. 

For readPortletResource(String servletContextName, Document document) method, it doesn't exist any usage, but I add it.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@yuhai You have 3 repeated blocks of `publicId` validation logic, which is not acceptable. If it's hard to make the private methods layered (read file -> read XML document), at least extract the `publicId` validation into a method. On the other hand, don't add an API when no one is using it. (`readPortletResource(String, Document)`)

Also, as I reconsidered, the whole refactor should start from private methods. We shouldn't add the new public methods in the first commit. We should split the private logics, make them reuseable and DRY (don't repeat yourself) as much as possible, and then add the new APIs calling the splitted private methods and apply.

Please rearrange the commits / changes and resend.

**Pull request closed without merging**
