### PR TITLE
LPS-134886 Set null for property value of lazy blob column in Hibernate's loaded state

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@vicnate5 Could you review the results?

Liferay Continuous Integration ***@***.***> 于 2021年6月29日周二
21:33写道：

**Comment by vicnate5** [comment]
@dantewang No regressions found

**Pull request closed without merging**
