### PR TITLE
[Deprecations] LPS-105389 part5

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please refer to ci:test result from https://github.com/yuhai/liferay-portal/pull/197. I checked modules-unit-jdk8, modules-semantic-versioning-jdk8 and modules-integration-mysql57-jdk8, these errors aren't related with the fix.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1652.

**Pull request closed without merging**
