### PR TITLE
[DS-migration] LPS-101881 and LPS-101968

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/8435.

**Pull request closed without merging**
