### PR TITLE
LPS-102159 Deprecate BaseDBTestCase in portal-test-integration

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1511. [See changes here.](https://github.com/dantewang/liferay-portal/compare/716905ab03f9~1...716905ab03f9)

**Pull request closed without merging**
