### PR TITLE
LPS-161990 Satisfy Portlet Specification and Servlet Specification: return null for getMimeType(String) when the file type is unknown. Since we rely on Tika to detect mime type, and Tika uses application/octet_stream for both known extensions like "bin" and unknown/undetected type, we need to rule out the file types that Tika knows.

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
TCK should pass: https://github.com/dantewang/liferay-portal/pull/2265#issuecomment-1290050733

     [exec]    after class.
     [exec] Tests run: 4405, Failures: 0, Errors: 0, Skipped: 9, Time elapsed: 240.743 sec - in javax.portlet.tck.driver.TCKLiferayTestDriver
     [exec] 
     [exec] Results :
     [exec] 
     [exec] Tests run: 4405, Failures: 0, Errors: 0, Skipped: 9

**Comment by zhangyan0701** [comment]
There is a integration test failure seems related, only failed in this PR:
[com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest](https://testray.liferay.com/home/-/testray/case_results/2015383162)
```
     [exec] com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest > testUpgradeConfigWithDBAndFile FAILED
     [exec]     java.lang.AssertionError: [Lorg.osgi.service.cm.Configuration;@60b7a94c expected:<1> but was:<2>
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-27/test-portal-acceptance-pullrequest(master)/5517/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
