### PR TITLE
LPS-123838 12-02

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@GinsonRen Could you run a startup diff on this one? Thanks.

**Comment by GinsonRen** [comment]
@dantewang Here are the results:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 6de07bff9 | 51388 | 21975.8 | 21546 | 22048 | 22172 | 22261 | 21852
PR-1830 | - | 45181 | 22084.6 | 22121 | 22,194 | 22049 | 22228 | 21831

**Pull request closed without merging**
