### PR TITLE
LPS-118542

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, Tina asked me to create a separate ticket to submit the test (Please refer to https://github.com/tinatian/liferay-portal/pull/1924#issuecomment-668853582).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/225. [See changes here.](https://github.com/dantewang/liferay-portal/compare/9c5a161ded90~3...9c5a161ded90)

**Pull request closed without merging**
