### PR TITLE
LPS-76502 In CacheControlImpl.setETag method, call the setProperty method only when the eTag is not null

### PR DESCRIPTION
**Pull request by ChiZelin**
@dantewang 

CI test: Is there a problem here? https://github.com/ChiZelin/liferay-portal/pull/70

CI test with tck3: Everything is OK!

Thanks!

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
@ChiZelin your CI result seems OK. Either upstream failures (also fail in upstream) or "build aborted".

**Comment by ChiZelin** [comment]
@dantewang 

OK!

**Comment by dantewang** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/5426. [See changes here.](https://github.com/dantewang/liferay-portal/compare/c6d81384777a~1...c6d81384777a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
