### PR TITLE
Lps 74148 part 3 commerce 7 29

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/488. [See changes here.](https://github.com/dantewang/liferay-portal/compare/1b3334d184f0~2...1b3334d184f0)

**Pull request closed without merging**
