### PR TITLE
LPS-X Use ConcurrentLinkedDeque to store company IDs

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the test results?

**Comment by zhangyan0701** [comment]
Just start reviewing.

**Comment by zhangyan0701** [comment]
All failures are unrelated.

**Pull request closed without merging**
