### PR TITLE
LPS-111235

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
Previous pull request: https://github.com/dantewang/liferay-portal/pull/1591

The test failures from https://github.com/dantewang/liferay-portal/pull/1591#issuecomment-616304418 seem to be related to [FELIX-6081](https://issues.apache.org/jira/browse/FELIX-6081). To resolve the errors, I added the workaround from [LPS-98289](https://issues.liferay.com/browse/LPS-98289).

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@jesseyeh-liferay Could you go with the same way as we did to modules/third-party/asm and regenerate the fake gradle cache, and test it? We usually remove module-info.class from the jar by patching because the file causes issues on JBoss and Wildfly. It may not be the case now because it depends on the version of JBoss or Wildfly we use, but removing the class won't do any harm to us. It's for JDK modular system.

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
@dantewang I used how we handled `module-info.class` in modules/third-party/asm as a reference and noticed that we already handle it similarly in modules/third-party/com-fasterxml-jackson-databind. I then updated segments-test to use our patched version instead, regenerated the fake gradle cache, and successfully ran the segments-test tests locally. Did I understand your comment correctly?

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1802.

**Pull request closed without merging**
