### PR TITLE
LPS-131959

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang, 

ci:test result is from https://github.com/yuhai/liferay-portal/pull/269. No related issues.

Thanks.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Which module needs the dependency deployed by required-dependencies? Since core already has these jars, can the packages just be exported from core?

**Comment by yuhai** [comment]
@dantewang,

**Pull request closed without merging**
