### PR TITLE
[portal-test-integration] LPS-102243

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@ChiZelin Some of the test failures should be related. After switching to use a class via reflection, bnd won't automatically create the corresponding import-package for it. Then you get errors like

> java.lang.ClassNotFoundException: com.liferay.portal.security.permission.SimplePermissionChecker cannot be found by com.liferay.portal.test_7.0.0

**Comment by dantewang** [comment]
Hi @tinatian, it turns out there are more classes depending on portal-impl classes. Some classes can be moved, and simpler logics can be inlined, but some of them are better to be called directly so we have to go with reflection operations. For example, https://github.com/dantewang/liferay-portal/pull/1383/commits/09817a9ebbbd53d70ce778ef2d7bf7d067253ef9, https://github.com/dantewang/liferay-portal/pull/1383/commits/3f7d523cf96a002b0847fec279406365ac1a3055, https://github.com/dantewang/liferay-portal/pull/1383/commits/ad7b3494f601065daea392adf0507920a73cc776

Do you still want `portal-impl` to be excluded from build path of `portal-test`?

**Comment by tinatian** [comment]
Hi @dantewang 
Yes, I still want it to be decoupled from portal-impl. 

Please see my comment for each case to simplify the logic. 

If you have more examples and do not know how to simplify, please let me know.

Tina.

**Comment by tinatian** [comment]
Hi @dantewang ,
Please make the decouple a separate pull, so that we won't bother with other logic.

Thanks.
Tina.

**Pull request closed without merging**
