### PR TITLE
LPS-95015

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang 

The pr is based on https://github.com/yuhai/liferay-portal/pull/138. I merged your last commit to the commit 8d5b8f7fefa6dc68550077a83b6273cb5d57ac81. No unclean data generated in database.

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1387. [See changes here.](https://github.com/dantewang/liferay-portal/compare/6bdeb13fc6af~9...6bdeb13fc6af) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1389. [See changes here.](https://github.com/dantewang/liferay-portal/compare/f196255bf6be~11...f196255bf6be) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
