### PR TITLE
[portal-test-integration] LPS-102245 Do some preparatory work to avoid the coupling between portal-test and portal-impl after migrate stuff from portal-test-integration to portal-test

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Fetched

**Comment by ChiZelin** [comment]
@dantewang force pushed

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by ChiZelin** [comment]
@dantewang force pushed to fix semantic versioning

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1402. [See changes here.](https://github.com/dantewang/liferay-portal/compare/1c84a1f43a0b~1...1c84a1f43a0b)

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Sent

**Pull request closed without merging**
