### PR TITLE
[Bug Fix] LPS-145031

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the issue doesn't exist in MYSQL. So I don't add one integration test to expose the issue.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Actually you can make the integration test only run on certain databases. Please search for "assume" in integration tests for examples.

**Comment by dantewang** [comment]
@yuhai For this PR you can just push the integration test commit. I'll rearrange the order before sending out if it passes review.

**Comment by yuhai** [comment]
> @yuhai For this PR you can just push the integration test commit. I'll rearrange the order before sending out if it passes review.

@dantewang got it, thanks.

**Comment by yuhai** [comment]
@dantewang, I just add one test commit to expose the issue. In the test classes, I only added the tests which can expose the issue.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai I can see that you added test cases into the newly created test files; but in some tests there's only one test case, while in some tests there are 2.

I have some questions:

- How many test cases in total? I guess just 2, right?
- Do these test cases fail on MySQL or MariaDB? Or the cases are not supported at all in these databases? I want to know the reason that you don't want these to run on all databases.

If there's just 2 cases and you want to limit the scope only to affected databases, I think you can just put the `assume` statement in the test method, not in a separate `assume` method for the whole test class.

**Comment by yuhai** [comment]
> How many test cases in total? I guess just 2, right?
yes

> Do these test cases fail on MySQL or MariaDB? Or the cases are not supported at all in these databases? I want to know the reason that you don't want these to run on all databases.

No, these test cases won't fail on MySQL or MariaDB. The reason is the issue doesn't happen MySQL or MariaDB. If I add them on MySQL or MariaDB, it can't expose the issue.

> If there's just 2 cases and you want to limit the scope only to affected databases, I think you can just put the assume statement in the test method, not in a separate assume method for the whole test class.

From my understanding, I may only use Assume.assumeTrue() in test method, instead of invoking AssumeTestRule. I will try to do this.

**Pull request closed without merging**
