### PR TITLE
Lps 104416 fix typo

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang 

After fixing the typo in the test, it will expose the failure when generating data for fragment which caused by https://issues.liferay.com/browse/LPS-117064

I have fixed a similar issue on the homepage with content type generation in https://github.com/GinsonRen/liferay-portal/pull/567, I will connect with Pavel to find how to add these data of fragment manually to see if we can apply the same fix on the fragment issue.

```
2020-09-02 02:16:01.169 ERROR [Thread-4][runtime:59] Error executing FreeMarker template
    FreeMarker template error:
    Java method "com.liferay.portal.tools.sample.sql.builder.DataFactory.newLayoutPageTemplateStructureRelModel(com.liferay.portal.kernel.model.LayoutModel, com.liferay.layout.page.template.model.LayoutPageTemplateStructureModel, com.liferay.fragment.model.FragmentEntryLinkModel)" threw an exception when invoked on com.liferay.portal.tools.sample.sql.builder.DataFactory object "com.liferay.portal.tools.sample.sql.builder.DataFactory@6fea14e1"; see cause exception in the Java stack trace.

    ----
    FTL stack trace ("~" means nesting-related):
    	- Failed at: #local layoutPageTemplateStructureRel...  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/macro.ftl" in macro "insertContentLayout" at line 46, column 9]
    	- Reached through: @insertContentLayout _fragmentEntryMo...  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/fragment.ftl" at line 12, column 9]
    	- Reached through: #include "fragment.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/groups.ftl" at line 24, column 9]
    	- Reached through: #include "groups.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/sample.ftl" at line 13, column 1]
    ----

    Java stack trace (for programmers):
    ----
    freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
    	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
    	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:252)
    	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:77)
    	at freemarker.core.MethodCall._eval(MethodCall.java:62)
    	at freemarker.core.Expression.eval(Expression.java:101)
    	at freemarker.core.Assignment.accept(Assignment.java:134)
    	at freemarker.core.Environment.visit(Environment.java:367)
    	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:872)
    	at freemarker.core.Environment.invokeMacro(Environment.java:809)
    	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
    	at freemarker.core.Environment.visit(Environment.java:367)
    	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
    	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
    	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
    	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
    	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
    	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
    	at freemarker.core.Environment.visit(Environment.java:331)
    	at freemarker.core.Environment.visit(Environment.java:337)
    	at freemarker.core.Environment.include(Environment.java:2694)
    	at freemarker.core.Include.accept(Include.java:171)
    	at freemarker.core.Environment.visit(Environment.java:367)
    	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
    	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
    	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
    	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
    	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
    	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
    	at freemarker.core.Environment.visit(Environment.java:331)
    	at freemarker.core.Environment.visit(Environment.java:337)
    	at freemarker.core.Environment.include(Environment.java:2694)
    	at freemarker.core.Include.accept(Include.java:171)
    	at freemarker.core.Environment.visit(Environment.java:331)
    	at freemarker.core.Environment.visit(Environment.java:337)
    	at freemarker.core.Environment.process(Environment.java:310)
    	at freemarker.template.Template.process(Template.java:383)
    	at com.liferay.portal.freemarker.FreeMarkerUtil.process(FreeMarkerUtil.java:47)
    	at com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilder.lambda$generateSQL$0(SampleSQLBuilder.java:249)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NoClassDefFoundError: org/osgi/framework/FrameworkUtil
    	at com.liferay.fragment.service.FragmentEntryLinkLocalServiceUtil.<clinit>(FragmentEntryLinkLocalServiceUtil.java:818)
    	at com.liferay.layout.util.structure.FragmentStyledLayoutStructureItem.setFragmentEntryLinkId(FragmentStyledLayoutStructureItem.java:105)
    	at com.liferay.layout.util.structure.LayoutStructure.addFragmentLayoutStructureItem(LayoutStructure.java:208)
    	at com.liferay.layout.util.template.LayoutData.getLayoutDataJSONObject(LayoutData.java:74)
    	at com.liferay.portal.tools.sample.sql.builder.DataFactory.newLayoutPageTemplateStructureRelModel(DataFactory.java:2592)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
    	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
    	... 36 more
    Caused by: java.lang.ClassNotFoundException: org.osgi.framework.FrameworkUtil
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 47 more
```

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @dantewang 

I fix the fragment issue as we did for the home page in the forced pushed commit.

Lily

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1965.

**Pull request closed without merging**
