### PR TITLE
[bugFix] LPS-105474

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, these errors are not related with the fix. By the way, please check the "Liferay.Util.fetch" document from https://portal.liferay.dev/docs/7-2/reference/-/knowledge_base/r/handling-ajax-requests-with-fetch

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1700.

**Pull request closed without merging**
