### PR TITLE
LPS-96274 Adding missing dependency

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez, @dantewang,

This pull should work fine. @patriciajeanperez please verify.

Thanks!

**Comment by 4lejandrito** [comment]
ci:test:messageboards

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Re-running the tests as results are mostly blocked by test failures.

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
Hi @4lejandrito, some functional failures that I was able to confirm when I tested manually:

- Reply button in Site Admin is not responsive
`Uncaught (in promise) TypeError: window[editorName].dispose is not a function
    at <anonymous>:446:27`
- Title of replies do not have "Re:"
**Expected:** 
Expected
**Actual:**
Actual

**Comment by 4lejandrito** [comment]
Thanks a lot @patriciajeanperez. I'll look into those today.

**Comment by 4lejandrito** [comment]
See https://github.com/dantewang/liferay-portal/pull/1169.

**Pull request closed without merging**
