### PR TITLE
[Deprecation] LPS-103869

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please refer to ci:test result from https://github.com/yuhai/liferay-portal/pull/180. I checked modules-integration-mysql57-jdk8, source-format-jdk8, modules-unit-jdk8 and modules-semantic-versioning-jdk8. these errors are unrelated with the fix.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@yuhai See https://github.com/tinatian/liferay-portal/pull/1585

I didn't include:

1. https://github.com/dantewang/liferay-portal/pull/1390/commits/a477bba5970cdac1238b6d96cd2971ab399ed2a4 because I can find occasions of "SOCIAL_BOOKMARK_ICON" in functional tests. Let's postpone this to later parts and confirm with QA before going.
2. https://github.com/dantewang/liferay-portal/pull/1390/commits/f1aa97d1489f731ad2fde8b694fd40a502c4f261 Could you confirm with security team guys (maybe Tomas?) to see if `Random` is safe to be here?
3. https://github.com/dantewang/liferay-portal/pull/1390/commits/97bb84bd2b7ab13548dee77a58b06d9186593c4a I found two Freemarker templates setting `invokeTaglibDiscussion` as the action of action url. Please double check.

**Comment by dantewang** [comment]
By the way for https://github.com/dantewang/liferay-portal/pull/1390/commits/97bb84bd2b7ab13548dee77a58b06d9186593c4a I only excluded your removal of `invokeTaglibDiscussion` related methods.

**Pull request closed without merging**
