### PR TITLE
LPS X FileInstallProperties

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X SF, inline, prepare for next
- LPS-X Directly collect file install dirs in DirectoryWatcher
- LPS-X SF, make SF happy
- LPS-X Directly read MODULE_FRAMEWORK_AUTO_DEPLOY_INTERVAL in DirectoryWatcher; since this property is only used by file install, move its default value (2000) to PropsValues.
- LPS-X SF, inline _poll field, since it's now the direct value of PropsValues.MODULE_FRAMEWORK_AUTO_DEPLOY_INTERVAL
- LPS-X Directly read dynamic start level and web start level in DirectoryWatcher
- LPS-X SF, inline these fields
- LPS-X This property seems to be a dead one

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian In this pull, I moved the properties that can be accessed directly from `PropsValues` to `DirectoryWatcher`.

But I'm wondering what we want to do with the other properties that are grouped under the `module.framework.properties.` prefix, like https://github.com/liferay/liferay-portal/blob/13b31e6ff98e97eaf225190e6a362e72538b4521/portal-impl/src/portal.properties#L8026. They are also passed to `DirectoryWatcher` by `BundleContext` properties, but they are processed centralized in https://github.com/liferay/liferay-portal/blob/master/modules/core/portal-bootstrap/src/main/java/com/liferay/portal/bootstrap/ModuleFrameworkImpl.java#L456.

I ask this because at the first glance it seems this kind of properties should be used to override properties in third-party osgi framework libs, but the dependency manager executor Shuyang made also uses this way: https://github.com/liferay/liferay-portal/blob/ec647fea5d398e778c752112a8e8d6742bb48a00/modules/apps/static/portal-dependency-manager-component-executor-factory/portal-dependency-manager-component-executor-factory/src/main/java/com/liferay/portal/dependency/manager/component/executor/factory/internal/activator/ComponentExecutorFactoryBundleActivator.java#L52. So I'm not sure if I should modify the file-install related ones into normal portal properties.

**Comment by tinatian** [comment]
@dantewang Let's make all fileinstall properties separate from the module framework including those defining in portal.properties.
All fileinstall properties should be only used in fileinstall bundle, all other implicit usages of fileinstall properties should be avoided. Let's make the change and run ci test to verify if there is any implicit usage.

Tina.

**Comment by dantewang** [comment]
@tinatian OK I will avoid passing any file install property through bundle
context.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the results of this pull? Thanks!

**Comment by zhangyan0701** [comment]
No related failures found.

**Pull request closed without merging**
