### PR TITLE
LPS-96692

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, based on the requirement from https://github.com/tinatian/liferay-portal/pull/1477#discussion_r311670586, I merge the change to https://github.com/dantewang/liferay-portal/commit/8811da03dec28f971e2fda8faef9cc5b03b05815. I also check the properties in portal-text.properties. They are not related with the test. There are two properties aren't existed in portal.properties (they were used in 6.2) as the followings. 

lucene.merge.scheduler=org.apache.lucene.index.SerialMergeScheduler
lucene.store.type=ram

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:backend

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1478. [See changes here.](https://github.com/dantewang/liferay-portal/compare/968eb8780535~6...968eb8780535)

**Pull request closed without merging**
