### PR TITLE
LPS-135336 Tag <liferay-learn:message />

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, this is just update. The pr lacks of portal-web.json. Since portal-web.json related jsp is in portal-web and portal-web can't invoke module taglib. I may try to hard code to replace <liferay-learn:message /> with <a> tag in portal-web.

### CODE REVIEW

**Comment by yuhai** [comment]
@dantewang, I just push force the new change for portal-web.json. All are done for now.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai My only concern about this, is that you hard code a url in the jsp. Looking at the json file, the it obviously supports multiple languages. Maybe in the future this needs to display different text based on the locale.

Is the tag's logic very complicated?

**Comment by yuhai** [comment]
@dantewang, I will check this.

**Pull request closed without merging**
