### PR TITLE
LPS-161990 Return null if the content type can not be determined (overriding Tika's default behavior which returns application/octet-stream

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@catarineaguiar Could you check whether the tests pass? Especially for the TCK test. Thanks!

**Comment by dantewang** [comment]
ci:test:tck

**Comment by catarineaguiar** [comment]
@zhangyan0701 can you take a look on these tests results, please? Thanks

**Comment by dantewang** [comment]
@zhangyan0701 I think some of the test results in relevant and default are related. But I want to know whether the error in LPS-161990 still exists.

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Pull request closed without merging**
