### PR TITLE
LPS-129172

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi @dantewang, I add the last two commits to solve ci:test existed errors.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, the ci:test result shouldn't be related with the pr. In addition, the pattern "yyyy-MM-dd'T'HH:mm:ss.SSSXXX" referred to https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#rfc822timezone

**Comment by dantewang** [comment]
@yuhai I can accept this, but will this change in jackson affect our
runtime code in portal? Should we inform the corresponding team to take an
extra review?

Yu Hai ***@***.***> 于 2021年4月1日周四 10:39写道：

**Comment by yuhai** [comment]
@dantewang, I didn't check if it affected runtime code (date display). I think we may firstly send it to the corresponding team to review.

**Pull request closed without merging**
