### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/227. [See changes here.](https://github.com/dantewang/liferay-portal/compare/4793ff8da32f~4...4793ff8da32f)

**Pull request closed without merging**
