### PR TITLE
LPS-84064 Aggregate PortletConfig ResourceBundleLoader and servlet context ResourceBundleLoader

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi Dante,

As discussed earlier, let me send you my suggested fix.
Please review my changes, and forward it to the next approver in case you find everything ok.
Link to my LPS:
[LPS-84064](https://issues.liferay.com/browse/LPS-84064)

I have tested my branch against the original issue and everything was working ok.
Then I checked if the "go-to-site" link is displayed correctly -> it was ok!

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by peterpetrekanics** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:retest

**Comment by dantewang** [comment]
Fetched <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/978. [See changes here.](https://github.com/dantewang/liferay-portal/compare/efef79a513bd~1...efef79a513bd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
