### PR TITLE
LPS X Xalan

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Remove Xalan dependency from portal-reports-engine-console-jasper because this module does not import any Xalan package, nor has any compile-time dependency on Xalan
- LPS-X Update patch for DaisyDiff to avoid depending on Xalan. Use XML API and Xerces instead.
- LPS-X FAKE GRADLE CACHE
- LPS-X Apply new version of DaisyDiff
- LPS-X Temp: compileInclude Xalan for XSLTemplate for testing
- LPS-X Remove Xalan from Gradle class path
- LPS-X Remove xalan.jar from core
- LPS-X FreeMarker does not necessarily need Xalan packages; it can use Jaxen instead (see https://freemarker.apache.org/docs/xgui_imperative_formal.html)
- LPS-X Same for this one. The xpath related packages were introduced by the embedded FreeMarker.
- LPS-X Temporarily compileInclude Xalan for these modules as they have too many dependencies, and it's hard to identify which needs Xalan.
- LPS-X Auto SF

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@vicnate5 Could you help me review the results? This PR is mostly similar with https://github.com/dantewang/liferay-portal/pull/2139, just with different changes in portal-reports-console-jasper and commerce-report-impl.

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@dantewang ,
Can you look into these test errors? If they are not related to this PR, then the PR is good. Thanks!
`Testcase: testLibDependencyJarsInVersionsExt(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] Wrong version for lib/portal/daisydiff.jar in lib/versions-ext.xml expected:<...ted.LIFERAY-PATCHED-[2]> but was:<...ted.LIFERAY-PATCHED-[1]>
    [junit] junit.framework.AssertionFailedError: Wrong version for lib/portal/daisydiff.jar in lib/versions-ext.xml expected:<...ted.LIFERAY-PATCHED-[2]> but was:<...ted.LIFERAY-PATCHED-[1]>
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testLibDependencyJarsInVersionsExt(LibraryReferenceTest.java:158)
    [junit] 
    [junit] 
    [junit] Testcase: testVersionsExtJarsInLib(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] lib/versions-ext.xml has a nonexistent reference to lib/portal/xalan.jar
    [junit] junit.framework.AssertionFailedError: lib/versions-ext.xml has a nonexistent reference to lib/portal/xalan.jar
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testVersionsExtJarsInLib(LibraryReferenceTest.java:212)`

https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14145/

I am not sure if this second is caused by this PR. But I am seeing it here only. Take a look at this too. Thanks!

`ERROR [http-nio-8080-exec-6][JDBCExceptionReporter:234] ORA-00904: "TRUE": invalid identifier

2022-01-13 10:20:14.883 ERROR [http-nio-8080-exec-6][PortletRequestDispatcherImpl:304] Unable to dispatch request: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: error executing work
2022-01-13 10:20:14.883 ERROR [http-nio-8080-exec-6][PortletServlet:119] javax.portlet.PortletException: org.apache.jasper.JasperException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: error executing work
javax.portlet.PortletException: org.apache.jasper.JasperException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: error executing work
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:307) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:620) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:636) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:506) ~[portal-kernel.jar:?]
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
	at com.liferay.change.tracking.web.internal.portlet.PublicationsPortlet.render(PublicationsPortlet.java:99) ~[bundleFile:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:570) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:660) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:345) ~[portal-impl.jar:?]
	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.lambda$render$0(MonitoringInvokerPortlet.java:259) ~[?:?]
	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet._render(MonitoringInvokerPortlet.java:363) ~[?:?]
	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.render(MonitoringInvokerPortlet.java:257) ~[?:?]
	at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1425) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.56]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]`

https://testray.liferay.com/reports/production/logs/2022-01/test-1-28/test-portal-acceptance-pullrequest(master)/1537/functional-tomcat90-oracle193-jdk8/1/10/jenkins-console.txt.gz

**Comment by dantewang** [comment]
I'll continue with the other PR.

**Pull request closed without merging**
