### PR TITLE
LPS-99222

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, BaseWebServerTestCase extends BaseDLAppTestCase. I don't move them together because BaseDLAppTestCase should be moved to document-library-test-util module.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
@ChiZeLin Plz move `BaseDLAppTestCase` based on this pull and send them together to me. Add it to your list for now and do it after finishing DS migration.

**Comment by ChiZelin** [comment]
@dantewang Please see https://github.com/dantewang/liferay-portal/pull/1287
cc @yuhai

**Pull request closed without merging**
