### PR TITLE
LPS-110758

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
@dantewang, the pr is based on https://github.com/dantewang/liferay-portal/pull/1575 requirement.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1743. [See changes here.](https://github.com/dantewang/liferay-portal/compare/9d083ee3b076~5...9d083ee3b076)

**Pull request closed without merging**
