### PR TITLE
LPS-129172

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr rebase on https://github.com/dantewang/liferay-portal/pull/2046 and resolve the previous test error.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
@dantewang, I just solved the conflicted files and push force the new changes.

**Comment by dantewang** [comment]
Closing as it's already sent.

**Pull request closed without merging**
