### PR TITLE
LPS-100565

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, this is common issue in other modules. I write one reproduction step to expose the issue. Please refer to https://issues.liferay.com/browse/LPS-100565?focusedCommentId=1942011&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1942011

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Is it possible to add an integration test to expose it?

Liferay Continuous Integration <notifications@github.com> 于 2019年8月30日周五
17:16写道：

**Comment by yuhai** [comment]
@dantewang, the issue was reported by running integration test LockLocalServiceTest. If we need to write another integration test, I will try to do that. I am thinking how to do the integration test explicitly for the race completion case. :)

**Comment by dantewang** [comment]
@yuhai Yeah, let's try to make an integration test to construct the race
condition. The reproducing steps require using debugger, which is not
friendly to qa.

Yu Hai <notifications@github.com> 于 2019年8月30日周五 17:34写道：

**Comment by yuhai** [comment]
@dantewang, got it.

**Pull request closed without merging**
