### PR TITLE
LPS-99323

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the last commit is for checking the previous errors caused reason. Refer to https://portal.liferay.dev/docs/7-0/tutorials/-/knowledge_base/t/making-your-applications-configurable,  WikiGroupServiceConfiguration define scope is ExtendedObjectClassDefinition.Scope.GROUP. So we need to use _configurationProvider. 

If this is good for you, you may merge the last commit to the commit 0dcc7b52e712c7ed329a445f01a978adb86bdb32

cc @ChiZelin

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/861. [See changes here.](https://github.com/dantewang/liferay-portal/compare/6294acb7b91a~2...6294acb7b91a)

**Pull request closed without merging**
