### PR TITLE
LPS 120745

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@vicnate5 Could you verify the ci-test results? Thanks!

By the way before the SF error message there's a line of ANTLR related message. I can not reproduce it locally... Do you have any idea about it?

**Comment by vicnate5** [comment]
@zhangyan0701 can you help Dante with reviewing this?

**Comment by dantewang** [comment]
@zhangyang0701 @vicnate5 The rest builder failure seems to be related. Closing for now. Thanks!

**Pull request closed without merging**
