### PR TITLE
LPS-111104

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I want to explain the [code](https://github.com/dantewang/liferay-portal/blob/1b82ae11f2903fbcbff57b0176d3004af7bac9b2/modules/apps/portal/portal-log4j-test/src/test/java/com/liferay/portal/log4j/Log4jTest.java#L592). I don't use FileUtil.read() because it will replace '\r\n' with '\n'. log4j's XMLLayout used '\r\n'.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/216. [See changes here.](https://github.com/dantewang/liferay-portal/compare/a1e4270dc9b1~6...a1e4270dc9b1)

**Pull request closed without merging**
