### PR TITLE
[SD-migration] LPS-99322 portal-instances-service

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/835. [See changes here.](https://github.com/dantewang/liferay-portal/compare/3535e87d6e1a~1...3535e87d6e1a)

**Pull request closed without merging**
