### PR TITLE
LPS 184766 Equinox Next: Patch to prepare for ContextController inline

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-196987
- LPS-X Initial checkin
- LPS-X Patch ContextController to remove getServletContextDTO(), this can no longer be used in Liferay as we don't register any real HttpServiceRuntime
- LPS-X Patch ContextController to remove fireSessionIdChanged(); the call chain originated from ProxyServlet but was never used even in Equinox
- LPS-X Patch to remove RequestInfoDTO collecting from ContextController.getDispatchTargets() methods,
- LPS-X Initial Checkin
- LPS-X Patch to remove unused method from HttpServletEndpointController interface
- LPS-X Patch to create interface ServletContextHelperController out of ContextController
- LPS-X Patch to apply the interface when necessary
- LPS-X Patch module files
- LPS-X FAKE GRADLE CACHE
- LPS-X Apply

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 could you take a look at this one? thanks!

**Comment by zhangyan0701** [comment]
@dantewang 

No regressions found.

**Pull request closed without merging**
