### PR TITLE
LPS-111104

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr doesn't include replace temp file code because I encountered one issue, the issue is RollingFile appender didn't output log to files(.log/.xml). I will further check this. The PR redo some changes about read configuration file in Log4JUtil and Log4jExtenderBundleActivator. The main reason is Configurator.initialize() can do the configuration, to avoid config twice for same file, I change related code. 

@tinatian, as Dante mentined from the [link](https://github.com/dantewang/liferay-portal/pull/1684#issuecomment-663403043)

> The major challenges of the upgrading are the brand new "LoggerContext" concept and the immutable configurations in Log4J 2.
> 
> When using Log4J 1, all loggers are registered in a single "repository", and we can supply new configurations into this "repository" to add or update loggers.
> 
> When using Log4J 2, we can't do this because
> 
> Configuration classes are immutable, and reconfiguring APIs "replace" instead of "updating" the configs. If loggers are in the same context, reconfigure will be hard and heavy.
> LoggerContext -- each OSGi bundle should have its own LoggerContext by design.
> So this pull takes the one LoggerContext per bundle way.
> 
> Core will have a LoggerContext created by Log4JUtil; each OSGi bundle will have a LoggerContext managed by Log4jExtenderBundleActivator. Reconfiguring happens within each LoggerContext, so it's much easier & lighter to do the configuration replacement.
> I'll try to split the pull but it may not be easy -- as soon as we introduce the new version as dependency, everything will be broken.
> 
> A major problem now exists in LogAssertionTestRule. It installs an appender to the root logger on beforeClass, and removes it on afterClass. However, in the separated LoggerContext environment, it's no-go to install the appender to root logger of every LoggerContext.

In addition, I also encounter one issue about the [commit](https://github.com/dantewang/liferay-portal/commit/0fe9f40c98ee1a3b519afdbf6729204a29160ab5)

In log4j1, our all classes com.liferay.* have same parent logger **"com.liferay"**. In the current changes, since every module own itself loggerContext and the logger **"com.liferay"** doesn't define in the configuration, that is to say, loggers of module can't find the parent logger **"com.liferay"**. Instead, loggers of module will use itself root logger as parent in the case.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1924.

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/223. [See changes here.](https://github.com/dantewang/liferay-portal/compare/16db928105f3~3...16db928105f3)

**Pull request closed without merging**
