### PR TITLE
LPS-95571 REPLACE function can't use for TEXT data type in Sybase.

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, refer to the below content from http://infocenter-archive.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1270/html/iqref/CHDFIBIJ.htm

> string_expr1 is the source string, or the string expression to be searched, expressed as CHAR, VARCHAR, UNICHAR, UNIVARCHAR, VARBINARY, or BINARY data type.

REPLACE function can't use for TEXT data type in Sybase.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1619.

**Pull request closed without merging**
