### PR TITLE
LRQA-53786 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-53786

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc: @vicnate5

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1718. [See changes here.](https://github.com/dantewang/liferay-portal/compare/ec730b22071b~5...ec730b22071b)

**Comment by dantewang** [comment]
@kyle-miho See https://github.com/tinatian/liferay-portal/pull/1718

I made several changes. Please let me know if you have any questions or find any problem with my changes. Thanks!

**Pull request closed without merging**
