### PR TITLE
LPS 148135

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

Main Task: LPS-96117 Optimized Proxy creation replacement.
Sub Task: LPS-148135 Replace proxy creation in modules

No need semantic versioning as LayoutLocalServiceStagingAdvice isn't in an Export-Package, so I didn't add newInstance method.

Thanks for checking!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:tets:sf

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/410

**Pull request closed without merging**
