### PR TITLE
LPS X Remove Counter Data Source keep transaction

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Remove counter data source
- LPS-X Remove counter session factory

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
@GinsonRen @111Anna Could you run both runtime and startup test for this PR? For runtime, run DL first. Thanks!

**Comment by 111Anna** [comment]
Hi @dantewang  @GinsonRen, I ran the startup test, and DL case on main1, here are test results. I will update the test results of other cases later.

CE:
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| d2f55af82| 22543.3 |- |3046|-| 1830 | 88 | 496| 1003 |
Baseline + PR-2286| - |  22544.6 |-0.006%| 2999|1.5%| 1830 | 84 | 492 | 990 |

DXP:
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| d2f55af82| 24962.6 |- |3496.6|-| 1986 | 105| 558| 1092 |
Baseline + PR-2286| - |  24687.6 | 1.1%| 3616.3|-3.4%| 1986 | 98 | 558 | 1079|


DL:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
Baseline| d2f55af82| 36260 | 237 |-|
Baseline + PR-2286| - | 36168 |237| -0.25% |

**Comment by zhangyan0701** [comment]
@dantewang No related failures found from the ci test results.

**Comment by 111Anna** [comment]
@dantewang @GinsonRen, Here are test results of other test cases

Login:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
Baseline| d2f55af82| 51232 | 278 |-|
Baseline + PR-2286| - | 51636 |276| 0.8% |

WC:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
Baseline| d2f55af82| 65551 | 519 |-|
Baseline + PR-2286| - | 64590 |547| -1.5% |

MB:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
Baseline| d2f55af82| 10823 | 821 |-|
Baseline + PR-2286| - | 10960 |283  |1.2% |

Blog:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
Baseline| d2f55af82| 17016 | 42.2 |-|
Baseline + PR-2286| - | 16986 |42.8 |-0.2% |

AP:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
Baseline| d2f55af82| 28649 | 393 |-|
Baseline + PR-2286| - | 28856 |411 |0.7% |

**Comment by dantewang** [comment]
@111Anna Please rerun DL for another time. Thanks!

**Comment by 111Anna** [comment]
Hi @dantewang, I reran DL on main1, here is test result

DL

Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--
Baseline| 5f5176fa8| 36177 | 234 |-|
Baseline + PR-2286| - | 36305 |228| 0.35% |

**Comment by dantewang** [comment]
@111Anna Thanks!

**Pull request closed without merging**
