### PR TITLE
LPS-121111 make ResourceActionsBag immutable

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the fix is on top of LPS-117531. I referred to your branch and tina's branch (LPS-112056) to do this.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Thanks, I'll check it later. Tina asked to do an extra clean up before LPS-117531.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@yuhai The pull is to make `ResourceActionsBag` immutable, but I don't see it being actually immutable. For the specific case of `ResourceActionsBag`, immutable means the contents of every set inside this class can not be modified after the instance is created. But I think you are still modifying the instances of `ResourceActionsBag` in the `ResourceActionsImpl`.

Please recheck the pull and see if it's easy to make the class immutable on top of the current commits. If not, consider another title to better fit the purpose of the changes.

**Pull request closed without merging**
