### PR TITLE
LPS-88710 Separately register Wrapper to MessageBus and Scheduler job.

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/167. [See changes here.](https://github.com/dantewang/liferay-portal/compare/f5018cb12e37~4...f5018cb12e37)

**Pull request closed without merging**
