### PR TITLE
Lps 78980

### PR DESCRIPTION
**Pull request by gregory-bretall**
Hi @dantewang,
This pull is being resent from https://github.com/shuyangzhou/liferay-portal/pull/5871 based on your comments here https://github.com/shuyangzhou/liferay-portal/pull/5871#issuecomment-376813585.

I have removed the call to preparePortlet from processEvent and added in null checks for all 3 of the preparePortlet calls to maintain the check from the original call of preparePortlet from before my change. I also tested with the use cases you mentioned and have found that Full Page Applications work properly with my fix now.

Please let me know if there is anything else that you would like me to change or if you have any further concerns.

https://issues.liferay.com/browse/LPS-78980

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:02e5841788da73778e59d800351ba8ee894ff92c

**Comment by dantewang** [comment]
@gregory-bretall 

Since this is a portlet container change, I tried to run Portlet 3.0 TCK, which will be a part of our CI in the near future, on this PR, and found another issue.

When visiting a site which has only private page with URL `/group/site-name`, the Portal should redirect to a maximized login portlet to let the visitor login. However, on this PR, the login portlet doesn't show up; instead, the page shows the Hello World portlet, which is the content of `/web/guest/home`.

To reproduce:

1. Create a blank site, e.g. with the name "another"
2. Create a private page for that site
3. Navigate to the site, note that the URL is `http://localhost:8080/group/another`
4. Log out and visit that URL
    - You will see the URL containing parameters of Login portlet in the address bar, but the content is Hello World portlet.

By [extracting the group IDs setting logic into another method, and keeping invocation of `preparePortlet` untouched](https://github.com/dantewang/liferay-portal/pull/635/commits/5cab5920dd73e0957b63da1e5be40fbf17205cb0), I can overcome this issue and get 3.0 TCK running. I'll let you know when the TCK results come out.

**Comment by dantewang** [comment]
Hey @gregory-bretall 

Firstly, with my last commit, the 3.0 TCK [result](https://github.com/dantewang/liferay-portal/pull/635#issuecomment-377895564) seems to be good. I sent my change back to you for reference, see https://github.com/gregory-bretall/liferay-portal/pull/56

Then, for the Event phase, my comment might be a bit unclear. I didn't mean to "not having reset logic for Event phase at all". What I meant is, I think the group IDs should be set before Action phase, and reset after Event phase (if there are events to process) -- this should happen, but happen once for these two phases. Could you reconsider this, and adjust the fix if you agree?

And feel free to add comments if you have other considerations.

Thanks

**Comment by gregory-bretall** [comment]
Hi @dantewang,
Could you please clarify a little more on where exactly you intend for the IDs to be reset after the Event Phase? I'm not entirely sure I know where you intend for the change to be made.

**Comment by dantewang** [comment]
@gregory-bretall Never mind, after a second thought I think we can just re-add the reset back to `processEvent()`, calling my `_processGroupdId()` method. I'll add it and let Lily do a performance check, since we changed something that were called once into being called multiple times. If everything's OK I'll forward the PR to Shuyang.

Thanks

**Comment by slnn** [comment]
Hi Dante,
Here are test results on Login and MB:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log out
-- | -- | -- | -- | --
BaseLine | 02e5841 | 19071 | 206 | 52.2
PR | - | 18971 | 190 | 46.5

MB

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
Login | Add MB Thread
BaseLine | 02e5841 | 8883 | 207 | 340
PR | - | 8750 | 191 | 325

**Comment by dantewang** [comment]
@gregory-bretall sent to Shuyang https://github.com/shuyangzhou/liferay-portal/pull/5918

**Pull request closed without merging**
