### PR TITLE
[Bug] LPS-83768

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please refer to the below cases:

**Case 1**: Message1 (backgroundTaskId:1), Message2 (backgroundTaskId:2)
1.A: When Message1 (status:4), Message2(status:3), Message1 firstly go to BackgroundTaskQueuingMessageListener, it will resume itself. And Message2 won't resume backgroundTaskId:1. 
1.B:  When Message1 (status:4), Message2(status:3), Message2 firstly go to BackgroundTaskQueuingMessageListener, it will resume backgroundTaskId:1. And Message1 won't resume backgroundTaskId:1 because its modifiedDate is equal.

**Case 2** : Message1 (backgroundTaskId:1), Message2 (backgroundTaskId:2). Message4 (backgroundTaskId:4)
When Message1 (status:3), Message2(status:4),Message4 (status:1). Message1 firstly go to BackgroundTaskQueuingMessageListener. It will resume backgroundTaskId:2, call it **Message3**. And Message2 won't resume backgroundTaskId:2. At that time,  **Message4** owns the lock and it let Message3 QUEUED again (it will update backgroundTaskId:2 modifiedDate). That it to say, Message3 (status:4), Message 4(status:3). When Message3 go to BackgroundTaskQueuingMessageListener, due to the modifiedDate is different, and it resume backgroundTaskId:2. And Message4 won't resume backgroundTaskId:2 because the modifiedDate is equal.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/yuhai/liferay-portal/pull/237. [See changes here.](https://github.com/dantewang/liferay-portal/compare/6aa26e792ecd~3...6aa26e792ecd)

**Pull request closed without merging**
