### PR TITLE
LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/tinatian/liferay-portal/pull/1972.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Can you also merge my SF commits?

**Comment by yuhai** [comment]
@dantewang, ok.

**Comment by yuhai** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
