### PR TITLE
LPS-117531 4

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
**modules-integration-mysql57-jdk8:**
There is an error in portal log:
`    [junit] 13:01:39,054 ERROR [main][JDBCExceptionReporter:234] Duplicate entry '20099-com.liferay.portal.kernel.model.Group-4-com.liferay.portal' for key 'IX_A9FF4B2C'
    [junit] 13:01:39,068 ERROR [main][PortletTracker:371] Portlet com_liferay_site_memberships_web_portlet_SiteMembershipsPortlet from com.liferay.site.memberships.web_4.0.17 [626] failed to initialize
    [junit] org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update`

Seems like only happens in this PR, didn't see this in other PRs and upstream.

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai See Summer's comment. I've re-triggered another ci-test run. Let's see if it fails again.

**Comment by dantewang** [comment]
ci:test:backend

**Comment by yuhai** [comment]
@dantewang, the error seems unrelated with the PR. I will focus on the second ci:test result.

**Comment by dantewang** [comment]
@yuhai Forwarded as the error didn't happen again.

**Pull request closed without merging**
