### PR TITLE
LPS-80778 Removing unnecessary toLowercase call

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @dantewang,

These changes turn `data-fileEntryId` to `data-fileentryid` everywhere and remove the extra `toLowerCase` call. 

Can you please verify that it meets your needs? If so, please close it and I will run it past Sergio to get it eventually merged.

Regards

### CODE REVIEW

**Comment by dantewang** [comment]
Fetched <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
@4lejandrito Thanks Alejandro! Looks good to me. I'll let Lily run it through benchmark test case and reach back to you after that.

**Comment by slnn** [comment]
Hi @dantewang 

Here are test results on Blog

Portal Version | Git Id | Session Count | Mean Time | Portal CPU % | Old Gen GC Times | Young Gen GC Times
-- | -- | -- | -- | -- | -- | --
Login | Add Blog Entry
BaseLine | ba7bdd4 | 13327 | 402 | 390 | 85,90,91 | 48 | 1218
PR-665 | - | 13269 | 286 | 293 | 83,91,88 | 44 | 1194



Lily

**Comment by dantewang** [comment]
Hey @4lejandrito, the result looks good, although session count doesn't make a difference, we can see the GC improvement. Please feel free to send this PR up. Thank you very much!

**Pull request closed without merging**
