### PR TITLE
LPS 184766 Inline Equinox Http Dev ContextServiceTrackers

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-184766 Create project files
- LPS-184766 Copy over Equinox Http Servlet source code (version 1.2.2.v20211118-0920.LIFERAY-PATCHED-1), no change
- LPS-184766 Move packages, no logic change
- LPS-184766 Add SF suppressions
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet and com.liferay.portal.osgi.web.http.servlet.context
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal
- LPS-184766 Rename Activator to HttpServletBundleActivator and add it to bnd.bnd
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.context
- LPS-184766 SF and modify StringPlus to return String[] to fit most of its usages; this also prepares for the next commit.
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.customizer
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.error (unused classes are removed)
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.registration
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.servlet
- LPS-184766 SF, remove BooleanPlus and use GetterUtil instead
- LPS-184766 SF, remove ServiceProperties.parseBoolean() and use GetterUtil instead
- LPS-184766 Make SF happy: com.liferay.portal.osgi.web.http.servlet.internal.util (unused classes are removed)
- LPS-184766 SF, logging
- LPS-184766 SF, inline
- LPS-184766 SF, use HashMapDictionary and HashMapDictionaryBuilder
- LPS-184766 SF, use ReflectionUtil#throwException
- LPS-184766 SF, clean up
- LPS-184766 Apply, make portal-osgi-web-wab-extender depend on portal-osgi-web-http-servlet
- LPS-184766 Fix CI failures on JDK11: manually add imports that are in the original jar, but not automatically calculated when building the inlined module
- LPS-184766 Activator: Remove code that manually registers ProxyServlet; only register it via OSGi
- LPS-184766 Activator: Remove registered but unused OSGi service properties
- LPS-184766 Activator: Remove internal property, it's not part of the public standard nor used by Liferay
- LPS-184766 Activator: Simplify, track HttpServiceServlet directly
- LPS-184766 Activator: Simplify, use anonymous class
- LPS-184766 Activator: Change constant content
- LPS-184766 Activator: Move package, no logic change
- LPS-184766 Activator & Public Package: add a new interface to register the endpoint, register ProxyServlet internally, and remove HttpServiceServlet which extends the internal class
- LPS-184766 Activator & Public Package: move session listener registration into the HttpServletService tracker so that we don't need to expose HttpSessionTrackerUtil
- LPS-184766 Split into -api and -impl modules
- LPS-184766 Activator: Simplify, Liferay always use Servlet 3.0+
- LPS-184766 Activator: Use HashMap(Dictionary)Builder to clean up
- LPS-184766 Activator: SF, inner class to buy space
- LPS-184766 Activator: SF, remove unused parameter in HttpTuple and inline in HttpServletImplBundleActivator
- LPS-184766 SF, remove unused class
- LPS-184766 HttpServiceRuntimeImpl: SF, inline
- LPS-184766 Activator: Use an alternative way to get the service.id set by the framework which is required by the Whiteboard spec, prepare for next
- LPS-184766 Activator & HttpTuple: Make HttpTuple to take an array of service registrations and unregister in reverse order when destroy
- LPS-184766 Activator & HttpServiceRuntimeImpl: Move default servlet context helper registration to the activator
- LPS-184766 SF, no need to be a list
- LPS-184766 SF, rename HttpTuple to HttpServiceBag and move
- LPS-184766 Clean up, remove interfaces that are not part of the whiteboard spec
- LPS-184766 HttpServiceRuntimeImpl: SF, split implementation of HttpServiceRuntime and other logic into 2 classes so that we don't pass an impl class everywhere.
- LPS-184766 HttpServiceRuntimeController: Use generic to simplify centralized Failed*DTO recording, and move other DTO logic to HttpServiceRuntimeImpl
- LPS-184766 HttpServiceRuntimeController: SF, move ServiceTrackerCustomizer logic inner class
- LPS-184766 HttpServiceRuntimeController: Move HttpService related logic to HttpServiceImpl, prepare for next
- LPS-184766 HttpServiceImpl: SF, use ConcurrentHashMap
- LPS-184766 HttpServiceImpl: SF, no need to use Map with Bundle as key
- LPS-184766 HttpServiceRuntimeController & ContextController: SF, remove unnecessary things: 1) tracking and consuming bundle context -- already removed from activator; 2) servlet version check -- always 3.0+ in Liferay
- LPS-184766 Const: clean up constants, move or replace.
- LPS-184766 ContextController: Inline and change parameter, prepare for next
- LPS-184766 Add ServletTracker to track servlets
- LPS-184766 Apply
- LPS-184766 Proper order

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
There is an error randomly happening during portal startup that seems related:
```
2023-07-26 13:05:12.104 ERROR [SystemExecutorServiceUtil-8][ServletTracker:109] null
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_121]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_121]
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-30/test-portal-acceptance-pullrequest(master)/7281/functional-tomcat90-mysql57-chrome100-jdk8/9/5/liferay-log.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 I'll force push.

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@ginsonren @111anna please run a startup comparison and check the service tracker open count, thanks!

**Comment by dantewang** [comment]
@GinsonRen @111Anna Please also compare the invocation count of `ContextController.match`.

**Comment by 111Anna** [comment]
Hi @dantewang, I ran the PR on CE and DXP, the average startup time and the count of open service tracker are normal. The count of `ContextController.match` is increased by about 20 on both CE and DXP.
cc @GinsonRen

Here are test results:

CE:

Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker |Match ContextController
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--
Baseline | 389548c |18865.3 | - | 2648.3 | - | 1479 | 94 | 120 | 857|5441|33|565,038
Baseline + PR-2309 | - | 18952 | -0.46% | 2612 | 1.37% |  1479|  94| 120 | 857|5442|33|565,018

DXP:

Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker |Match ContextController
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--
Baseline | 389548c |20188| - | 3167.3| - | 1603 | 94 | 126 | 934|5876|33|657,504
Baseline + PR-2309 | - | 20238 | 0.25% |  3117| 1.59% | 1559 |97 | 126 |904 |5877|33|657,487

**Comment by dantewang** [comment]
@111Anna Could you upload the profiles? It seems strange because I merged a series of service trackers opened per context controller into a single service tracker, which should cut off hundreds of service tracker opens.

**Pull request closed without merging**
