### PR TITLE
LPS-87310

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang 

Please let me know if you have further concerns.

Please refer to ci test run result from https://github.com/yuhai/liferay-portal/pull/109. It seems ok. 

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/878. [See changes here.](https://github.com/dantewang/liferay-portal/compare/9da452a028c6~2...9da452a028c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
