### PR TITLE
LPS-89497

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1685. [See changes here.](https://github.com/dantewang/liferay-portal/compare/9179606fada9~7...9179606fada9)

**Pull request closed without merging**
