### PR TITLE
LPS-96274 No need for 2 different variables

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:messageboards

**Comment by 4lejandrito** [comment]
Hi @dantewang, @patriciajeanperez,

This pull fixes all the issues found by @patriciajeanperez. Hopefully this is the final one.

Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
Confirmed all issues are resolved :) @4lejandrito @dantewang

**Comment by slnn** [comment]
Hi @4lejandrito and @dantewang 

Here are test results on MB, I can see about 8%~10% improvement on session count

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | DB CPU Usage (%) | Portal CPU Usage(%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 318f09a | 8098 | 192 | 320 | 19,23,25 | 94,93,94
PR-1169 | - | 8960 | 173 | 311 | 21,26,29 | 93,93,92
PR-1169 | - | 8746 | 172 | 305 | 21,26,29 | 94,93,94


Lily

**Comment by dantewang** [comment]
Thanks @4lejandrito! Sorry for the delay, could you send this change up? We're going to run whitepaper next Friday, so it's great if this can make its way into upstream by the end of next week.

**Comment by 4lejandrito** [comment]
Hi @dantewang,

I want to run this past our front end guys to see if we can make it even better. We will most likely send it on Monday. 

Thanks!

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74555.

**Pull request closed without merging**
