### PR TITLE
COMMERCE-4186 Disable attachements and minor tweaks

### PR DESCRIPTION
**Pull request by dsitu**

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@dsitu Could you resend the COMMERCE-4186 changes (without LPS changes in this pull) and also apply Lily's SF in https://github.com/dantewang/liferay-portal/pull/1980? Thanks!

**Comment by dsitu** [comment]
@dantewang new PR with requested updates sent here https://github.com/dantewang/liferay-portal/pull/2002.

**Pull request closed without merging**
