### PR TITLE
LPS-110862 UnsyncStringWriter and StringBundler | Resend

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Are these failing AppBuilder tests flaky or unique?

**Comment by zhangyan0701** [comment]
Hi @dantewang 

Tests LocalFile.AppBuilder#PublishAppAsWidgetAndSubmitEntry and LocalFile.AppBuilder#PublishAppAsWidgetWithOnlyTableView looks like flaky.

Test LocalFile.AppBuilder#PublishAppsInProductMenuAndReuseItsViews seems a unique failure.
Didn't occur on other PR or upstream.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1820. [See changes here.](https://github.com/dantewang/liferay-portal/compare/1ab1766fd36c~1...1ab1766fd36c)

**Pull request closed without merging**
