### PR TITLE
Lps 135298 7 8

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Hi @dantewang @tinatian

I disabled the generation for Commerce related data in the unit in the last commit temporarily until the issue https://issues.liferay.com/browse/LRQA-68428 be fixed

Regards
Lily

**Comment by tinatian** [comment]
@slnn Who is going to fix the commerce related issue?

**Comment by slnn** [comment]
Will resend after the commerce issue be fixed

**Comment by dantewang** [comment]
@slnn Since the Commerce issue fix has been sent, could you resend this pull? I think it's better to do this first?

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/2038

**Pull request closed without merging**
