### PR TITLE
LPS-98380 Migrate sharing-service to use DS insteand of Spring

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/803. [See changes here.](https://github.com/dantewang/liferay-portal/compare/3e495c18c267~1...3e495c18c267)

**Pull request closed without merging**
