### PR TITLE
LPS 184766 Equinox Next 11 14 Customizers

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-201462 Squashed
- LPS-X *Customizer: Inline and initial SF
- LPS-X *Customizer: Explicitly import LiferayContextController; ContextController will be thrown away after inlining all the classes.
- LPS-X *Customizer: Apply to LiferayContextController
- LPS-X *Customizer: SF
- LPS-X For CI: identify whether there's modified

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you help me watch this PR? Specifically I added some output in  https://github.com/dantewang/liferay-portal/pull/2336/commits/cc31cc473ccb7110f48c913bbbfc939a026b590b, it's error log so it should fail CI when output.

**Comment by zhangyan0701** [comment]
@dantewang 

No regressions found. But there is no output like in https://github.com/dantewang/liferay-portal/commit/cc31cc473ccb7110f48c913bbbfc939a026b590b in any of the failed test.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Pull request closed without merging**
