### PR TITLE
LPS 159031 2 1

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-159031 Remove id to make Spring bean override work properly. This file is enabled when configuring R/W data source, and the InfrastructureUtil bean should override/merged with the bean of the same class in infrastructure-spring.xml, so that the dynamicDataSourceTargetSource is set; otherwise the DynamicDataSourceAdvice won't be created. The id of the bean in infrastructure-spring.xml was removed in 1a0c3c0de03a835b3f4d94d4e2fdb3dfd5eb0de0, so we should also remove the id of this bean to be consistent and make Spring identify the overriding.
- LPS-X Remove usage of @MasterDataSource; the transactions are by default not read-only, so they will always use the write/master data source
- LPS-X Remove support of @MasterDataSource
- LPS-159031 SpringHibernateThreadLocalUtil: add support to get whether the current transaction is read only
- LPS-159031 Create DynamicDataSource to dynamically provide connections from different data sources based on whether the current transaction is read-only
- LPS-159031 Add methods to DynamicDataSource to get the read/write data sources to apply to HikariConnectionPoolMetrics
- LPS-159031 Remove the old dynamic data source infrastructure

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
No related failures.

And the R/W data source functional tests passed in this PR:
[LocalFile.PortalSmoke#SmokeWithReadWriteDatabaseConfigurationJNDI](https://testray.liferay.com/home/-/testray/case_results/2182506409)
[LocalFile.PortalSmoke#SmokeWithReadWriteDatabaseConfigurationJDBC](https://testray.liferay.com/home/-/testray/case_results/2182506410)

**Pull request closed without merging**
