### PR TITLE
Lps 104499 9 10

### PR DESCRIPTION
**Pull request by slnn**
Just sort the ftl include order

https://github.com/brianchandotcom/liferay-portal/pull/93975#issuecomment-689645927

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
@tinatian Forwarding to Brian as the only change was sorting the ftl as Brian commented.

**Pull request closed without merging**
