### PR TITLE
Lps 148593 remove service context factory

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

This pull is to remove the mock serviceContextFactory method.
I deleted the test rule in CompanyThreadLocalTest and add LiferayUnitTestRule for both JSONWebServiceInvokerTest and JSONWebServiceTest to pass SF.   Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang Sorry, my bad. The class names are so similar...

We can register dummy service, or not register any service at all, for `ServiceProxyFactory`.

However, the first 2 tests (`JSONWebService*Test`) are mocking `ServiceContextFactory`. As you can see the `ServiceContextFactory.getInstance()` method has very complicated logic, and we're just lucky that no error occurs during this. However, please still confirm where and how the tested classes call the `ServiceContextFactory.getInstance()` and use the `ServiceContext` returned by the method -- if it just serves as a place holder, then I think it's OK.

Also, please update the commit messages to reflect which commits are related to `ServiceProxyFactory`.

**Comment by JanisZhang** [comment]
Hi @dantewang,
Sorry I misread ServiceContextFactory and ServiceProxyFactory...

For ServiceContextFactory in two test (`JsonService*test`) , yes, we're just lucky that no error occurs. If we don't set up the return value, it will cause **NPE** when excute `_serviceContext = ServiceContextFactory.getInstance(httpServletRequest);` in JSONWebServiceActionParameters  `collectAll()` method , the program catch the exception but throw nothing. 

And I removed mock in two tests (`JsonService*test`)  and set up needed value in HttpServletRequest so that during `ServiceContextFactory.getInstance(httpServletRequest)`, the method can return a real ServiceContext.

Actually the _serviceContext returned by the method only needed by ` @test testServiceContext()` in **JSONWebServiceInvokerTest** and `@test testModifyServiceContext()` in **JSONWebServiceTest** for testing service context merge (`serviceContext.merge((ServiceContext)parameterValue`  in JSONWebServiceActionImpl);), you can find more details in (https://issues.liferay.com/browse/LPS-34125 , https://github.com/hhuijser/liferay-portal/pull/1307 ) . I think the reason put mock in @Before method is that we have global method like   `_serviceContext =  ServiceContextFactory.getInstance(httpServletRequest);  

Thanks for Checking!

**Pull request closed without merging**
