### PR TITLE
LPS X Hibernate 2022 3 2

### PR DESCRIPTION
**Pull request by dantewang**
Removed commit https://github.com/dantewang/liferay-portal/pull/2164/commits/9b3c2e5ac3b4b1747b97eecd6cb27643a877434b because it causes issues in https://github.com/dantewang/liferay-portal/pull/2164#issuecomment-1049890841 as it makes the entity persisters for ExpandoColumn and ExpandoTable to be both mapped twice in the entity persister map. The HQL processing logic will duplicate the query based on how many persisters for the entity exist. The commit is to fix another issue but now we know that the fix is not correct.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Expecting failures of StagedExpando*Test to disappear with https://github.com/dantewang/liferay-portal/pull/2171/commits/3bcf2557ea7b2b9dcdb018d2a805868afca58520.

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the latest test results? Please ignore the previous runs. Thanks!

**Comment by zhangyan0701** [comment]
There are two issues seem related:

**1 Staging doesn't work on PostgreSQL:**

- Publish to Remote Live is not available:

before1

And error in console:
```
     [exec] 2022-03-02 11:53:47.968 ERROR [http-nio-8080-exec-3][SqlExceptionHelper:142] Large Objects may not be used in auto-commit mode.
     [exec] 2022-03-02 11:53:47.972 ERROR [http-nio-8080-exec-3][BasePersistenceImpl:628] Caught unexpected exception
     [exec] org.hibernate.exception.GenericJDBCException: could not execute query
```
Testray: https://testray.liferay.com/home/-/testray/case_results/1623590863
Full Jenkins console:
https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/2717/functional-tomcat90-postgresql134-jdk8/1/22/jenkins-console.txt.gz?authuser=0

- Enable locale staging with below command failed:
```
curl -X POST -u 'test@liferay.com:test' -d 'groupId=54842' -d 'branchingPublic=true' -d 'branchingPrivate=true' -d 'serviceContext={"attributes" : {"staged--staged-portlet_com_liferay_blogs_web_portlet_BlogsAdminPortlet--" : "true","staged--staged-portlet_com_liferay_bookmarks_web_portlet_BookmarksAdminPortlet--" : "true","staged--staged-portlet_com_liferay_calendar_web_portlet_CalendarAdminPortlet--" : "true","staged--staged-portlet_com_liferay_document_library_web_portlet_DLAdminPortlet--" : "true","staged--staged-portlet_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet--" : "true","staged--staged-portlet_com_liferay_dynamic_data_mapping_data_provider_web_portlet_DDMDataProviderPortlet--" : "true","staged--staged-portlet_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet--" : "true","staged--staged-portlet_com_liferay_template_web_internal_portlet_TemplatePortlet--" : "true","staged--staged-portlet_com_liferay_journal_web_portlet_JournalPortlet--" : "true","staged--staged-portlet_com_liferay_knowledge_base_web_portlet_AdminPortlet--" : "true","staged--staged-portlet_com_liferay_message_boards_web_portlet_MBAdminPortlet--" : "true","staged--staged-portlet_com_liferay_segments_web_internal_portlet_SegmentsPortlet--" : "true","staged--staged-portlet_com_liferay_wiki_web_portlet_WikiAdminPortlet--" : "true"}}' http://cloud-10-0-16-129.lax.liferay.com:8080/api/jsonws/staging/enable-local-staging
     [exec]     Response: {}Finished executing commands.
```
Console error:
```
     [exec] 2022-03-02 11:48:48.460 ERROR [liferay/background_task-8][SqlExceptionHelper:142] ERROR: operator does not exist: text ~~ bigint
     [exec]   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
     [exec]   Position: 2830
     [exec] 2022-03-02 11:48:48.470 ERROR [liferay/background_task-8][BasePersistenceImpl:628] Caught unexpected exception
     [exec] org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```
Testray: https://testray.liferay.com/home/-/testray/case_results/1623591051
Full Jenkins console: https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/2717/functional-tomcat90-postgresql134-jdk8/1/10/jenkins-console.txt.gz?authuser=0

**2 Upgrade failed on Oracle 19 and DB2:**

- Oracle: 
```
     [java] 2022-03-02 12:16:51.434 ERROR [Portal Dependency Manager Component Executor--1][SqlExceptionHelper:142] Invalid column type: getCLOB not implemented for class oracle.jdbc.driver.T4CVarcharAccessor
     [java] 2022-03-02 12:16:51.445 INFO  [Portal Dependency Manager Component Executor--1][LoggingTimer:44] Completed com.liferay.layout.page.template.internal.upgrade.v1_1_0.LayoutPrototypeUpgradeProcess#_upgradeLayoutPrototype in 21 ms
     [java] 2022-03-02 12:16:51.446 INFO  [Portal Dependency Manager Component Executor--1][UpgradeProcess:129] Failed upgrade process com.liferay.layout.page.template.internal.upgrade.v1_1_0.LayoutPrototypeUpgradeProcess in 79 ms
     [java] 2022-03-02 12:16:51.449 ERROR [Portal Dependency Manager Component Executor--1][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.layout.page.template.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute query
```
Testray: https://testray.liferay.com/home/-/testray/case_results/1623590252
Full Jenkins console: https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/2717/functional-tomcat90-oracle193-jdk8/1/3/jenkins-console.txt.gz?authuser=0

- DB2:
```
     [java] 2022-03-02 11:24:20.289 ERROR [Portal Dependency Manager Component Executor--2][SqlExceptionHelper:142] [jcc][t4][1092][11644][4.24.92] Invalid data conversion: Wrong result column type for requested conversion. ERRORCODE=-4461, SQLSTATE=42815
     [java] 2022-03-02 11:24:20.301 INFO  [Portal Dependency Manager Component Executor--2][LoggingTimer:44] Completed com.liferay.layout.page.template.internal.upgrade.v1_1_0.LayoutPrototypeUpgradeProcess#_upgradeLayoutPrototype in 46 ms
     [java] 2022-03-02 11:24:20.301 INFO  [Portal Dependency Manager Component Executor--2][UpgradeProcess:129] Failed upgrade process com.liferay.layout.page.template.internal.upgrade.v1_1_0.LayoutPrototypeUpgradeProcess in 418 ms
     [java] 2022-03-02 11:24:20.326 ERROR [Portal Dependency Manager Component Executor--2][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.layout.page.template.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute query
```
Testray: https://testray.liferay.com/home/-/testray/case_results/1623583944
https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/2717/functional-tomcat90-db2111-jdk8/1/3/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 Thanks! So there's no unique failure on MySQL?

**Comment by dantewang** [comment]
@yuhai Is this commit https://github.com/dantewang/liferay-portal/pull/2171/commits/e77ac30b0634a04f9f42f780ed5bcd251a15555b trying to fix the PostgreSQL error `PSQLException: Large Objects may not be used in auto-commit mode`?

**Comment by dantewang** [comment]
For Oracle: `SQLException: Invalid column type: getCLOB not implemented for class oracle.jdbc.driver.T4CVarcharAccessor`
For DB2: `SqlSyntaxErrorException: [jcc][t4][1092][11644][4.24.92] Invalid data conversion: Wrong result column type for requested conversion. ERRORCODE=-4461, SQLSTATE=42815`

Both fails at upgrading of `com.liferay.layout.page.template.service`; all are related to clob??

**Comment by yuhai** [comment]
> @yuhai Is this commit [e77ac30](https://github.com/dantewang/liferay-portal/commit/e77ac30b0634a04f9f42f780ed5bcd251a15555b) trying to fix the PostgreSQL error `PSQLException: Large Objects may not be used in auto-commit mode`?

@dantewang, yes.

**Comment by yuhai** [comment]
> For Oracle: `SQLException: Invalid column type: getCLOB not implemented for class oracle.jdbc.driver.T4CVarcharAccessor` For DB2: `SqlSyntaxErrorException: [jcc][t4][1092][11644][4.24.92] Invalid data conversion: Wrong result column type for requested conversion. ERRORCODE=-4461, SQLSTATE=42815`
> 
> Both fails at upgrading of `com.liferay.layout.page.template.service`; all are related to clob??

@dantewang, I forgot the error description. But when upgrading com.liferay.layout.page.template.service encountered the issue, it should be related with [LPS-145031](https://issues.liferay.com/browse/LPS-145031)

**Comment by dantewang** [comment]
@yuhai So for PostgreSQL it seems your fix didn't work... I'll check. Also LPS-145031 is marked as fixed, did the fix introduce this issue?

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Thanks! So there's no unique failure on MySQL?

Yes, I didn't see any regression on MySQL.

**Pull request closed without merging**
