### PR TITLE
LPS-120753 Mysql Connector / J 8.0.21

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test:relevant

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2016. [See changes here.](https://github.com/dantewang/liferay-portal/compare/ff4406f0f709~5...ff4406f0f709)

**Pull request closed without merging**
