### PR TITLE
LPS X Xalan 2

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Remove Xalan dependency from portal-reports-engine-console-jasper because this module does not import any Xalan package, nor has any compile-time dependency on Xalan
- LPS-X Update patch for DaisyDiff to avoid depending on Xalan. Use XML API and Xerces instead.
- LPS-X FAKE GRADLE CACHE
- LPS-X Apply new version of DaisyDiff
- LPS-X Temp: compileInclude Xalan for XSLTemplate for testing
- LPS-X Remove Xalan from Gradle class path
- LPS-X Remove xalan.jar from core
- LPS-X FreeMarker does not necessarily need Xalan packages; it can use Jaxen instead (see https://freemarker.apache.org/docs/xgui_imperative_formal.html)
- LPS-X Same for this one. The xpath related packages were introduced by the embedded FreeMarker.
- LPS-X Temporarily compileInclude Xalan for these modules as they have too many dependencies, and it's hard to identify which needs Xalan.
- LPS-X Auto SF
- LPS-X Switch to Jaxen as XPath engine for JasperReport to avoid using Xalan, according to https://community.jaspersoft.com/wiki/xml-data-source-very-slow-parse

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@vicnate5 Could you help me review the test results? You can ignore the failure of `LibraryReferenceTest`. Thanks!

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@dantewang 
The only warning error on this PR is below. It happens on DB2 but I don't believe it is related. Can you take a look? If it is not related, then this PR is good to go since we are ignoring `LibraryReferenceTest`. Thanks!

`WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.LAYOUTPAGETEMPLATESTRUCTUREREL, DRIVER=4.24.92: create index IX_CC9B240A on LayoutPageTemplateStructureRel (layoutPageTemplateStructureId, ctCollectionId);
     [java] 2022-01-13 09:28:45.662 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create unique index IX_843407A3 on LayoutPageTemplateStructureRel (layoutPageTemplateStructureId, segmentsExperienceId, ctCollectionId);
     [java] 2022-01-13 09:28:45.663 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.LAYOUTPAGETEMPLATESTRUCTUREREL, DRIVER=4.24.92: create unique index IX_843407A3 on LayoutPageTemplateStructureRel (layoutPageTemplateStructureId, segmentsExperienceId, ctCollectionId);
     [java] 2022-01-13 09:28:45.664 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_34E1EF96 on LayoutPageTemplateStructureRel (segmentsExperienceId, ctCollectionId);
     [java] 2022-01-13 09:28:45.665 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.LAYOUTPAGETEMPLATESTRUCTUREREL, DRIVER=4.24.92: create index IX_34E1EF96 on LayoutPageTemplateStructureRel (segmentsExperienceId, ctCollectionId);
     [java] 2022-01-13 09:28:45.665 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_CA98471 on LayoutPageTemplateStructureRel (uuid_, companyId, ctCollectionId);
     [java] 2022-01-13 09:28:45.667 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.LAYOUTPAGETEMPLATESTRUCTUREREL, DRIVER=4.24.92: create index IX_CA98471 on LayoutPageTemplateStructureRel (uuid_, companyId, ctCollectionId);
     [java] 2022-01-13 09:28:45.667 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_6AC1E153 on LayoutPageTemplateStructureRel (uuid_, ctCollectionId);
     [java] 2022-01-13 09:28:45.669 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.LAYOUTPAGETEMPLATESTRUCTUREREL, DRIVER=4.24.92: create index IX_6AC1E153 on LayoutPageTemplateStructureRel (uuid_, ctCollectionId);
     [java] 2022-01-13 09:28:45.669 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create unique index IX_FC932FB3 on LayoutPageTemplateStructureRel (uuid_, groupId, ctCollectionId);
     [java] 2022-01-13 09:28:45.671 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.LAYOUTPAGETEMPLATESTRUCTUREREL, DRIVER=4.24.92: create unique index IX_FC932FB3 on LayoutPageTemplateStructureRel (uuid_, groupId, ctCollectionId);`

https://testray.liferay.com/reports/production/logs/2022-01/test-1-27/test-portal-acceptance-pullrequest(master)/1414/functional-tomcat90-db2111-jdk8/0/3/jenkins-console.txt.gz

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:reports

**Comment by dantewang** [comment]
Thanks @vicnate5 @koor4356!

I started 2 extra CI test batches to explicitly verify Commerce and Reports, since this PR changed the XPath engine used by them.

@zhangyan0701 These 2 batches should finish during the day, could you review the results when they finish?

**Pull request closed without merging**
