### PR TITLE
LPS 145396 tests data orphan mod 5

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-145396 Delete ResourcePermissions entries in DeleteAfterTestRunMethodTestRule to avoid false positives
- LPS-145396 New method to detect orphan ResourcePermission
- LPS-145396 Check existing company and group
- LPS-145396 Delete the resource permissions of the group and company scopes
- LPS-145396 When DataGuard is executed with method scope the objects deleted during the _autoDeleteLeftovers execution are removed from the _records map and after that we cannot display it in the Assert message. Reverts "LPS-138761 DataGuard: Remove the deleted objects from the _records map as we are not going to need it and we will save memory"
- LPS-145396 Fix false positives in tests, replacing *LocalServiceBaseImpl delete method calls with *LocalServiceImpl ones
- LPS-145396 Add Group to the correct company to avoid having invalid ResourcePermission entries
- LPS-145936 Is this enough for checking orphan ResourcePermission which are left over even after auto delete (auto delete still skips ResourcePermission)?

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
Sent a new PR here https://github.com/liferay-core-infra/liferay-portal/pull/1020 that solves the CI test errors

**Comment by dantewang** [comment]
ci:test:relevant

**Pull request closed without merging**
