### PR TITLE
LPS 143660

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-143660 Make JarUtil require SHA1 checksum for the file it downloads, and check the checksum after downloading
- LPS-143660 Remove methods deprecated for 7.3.x
- LPS-143660 Apply to mysql.jar downloading
- LPS-143660 Apply to tensorflow jar downloading
- LPS-143660 TEMP: apply to Xuggler downloading
- LPS-143660 SF
- LPS-143660 Typo
- LPS-143660 Naming
- LPS-143660 Fix NPE: DataSourceFactoryImpl is executed before Spring context startup, so at the moment the wiring is not available

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results of this pull when they finish? Thanks!

**Comment by zhangyan0701** [comment]
There is a source format issue in file ./portal-impl/src/portal.properties:
```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-impl/src/portal.properties expected:<...E_PERIOD_JAR_PERIOD_[NAME_OPENBRACKET_COM_PERIOD_MYSQL_PERIOD_CJ_PERIOD_JDBC_PERIOD__UPPERCASED_RIVER_CLOSEBRACKET_
     [java]     # Env: LIFERAY_SETUP_PERIOD_DATABASE_PERIOD_JAR_PERIOD_SHA_NUMBER1_]_OPENBRACKET_COM_PER...> but was:<...E_PERIOD_JAR_PERIOD_[CHECKSUM_OPENBRACKET_COM_PERIOD_MYSQL_PERIOD_CJ_PERIOD_JDBC_PERIOD__UPPERCASED_RIVER_CLOSEBRACKET_
     [java]     # Env: LIFERAY_SETUP_PERIOD_DATABASE_PERIOD_JAR_PERIOD_NAME]_OPENBRACKET_COM_PER...>
```

Jenkins log:
https://test-1-32.liferay.com/job/test-portal-source-format/1495/console

No other related failure found.

**Pull request closed without merging**
