### PR TITLE
LPS-96692

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I add the commit https://github.com/dantewang/liferay-portal/commit/52061662baff2d74343169ba0c498d238e6ed008 to solve my mentioned [issue](https://github.com/dantewang/liferay-portal/pull/1189#issuecomment-509056204).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Just started reviewing :)

**Comment by dantewang** [comment]
ci:test:clustering

**Pull request closed without merging**
