### PR TITLE
Resource action

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the ci-test failures?

**Comment by zhangyan0701** [comment]
> Could you take a look at the ci-test failures?

Just start reviewing.

**Comment by zhangyan0701** [comment]
**tck-jdk8: This is unique failure. Didn't see this failure in other PRs**
Test case V2AddlFilterTests_SPEC2_20_Event_filter4 failed.
`     [exec] Tests run: 4405, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 303.526 sec <<< FAILURE! - in javax.portlet.tck.driver.TCKLiferayTestDriver
     [exec] test[V2AddlFilterTests_SPEC2_20_Event_filter4](javax.portlet.tck.driver.TCKLiferayTestDriver)  Time elapsed: 21.587 sec  <<< FAILURE!
     [exec] java.lang.AssertionError: Test case V2AddlFilterTests_SPEC2_20_Event_filter4 failed. 
     [exec] Exception: 
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
     [exec] 	at java.util.Optional.orElseThrow(Optional.java:290)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
     [exec] 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
     [exec] 	at javax.portlet.tck.driver.TCKTestDriver.processClickable(TCKTestDriver.java:405)
     [exec] 	at javax.portlet.tck.driver.TCKLiferayTestDriver.test(TCKLiferayTestDriver.java:163)
     [exec] 
     [exec] 
     [exec] Results :
     [exec] 
     [exec] Failed tests: 
     [exec]   TCKLiferayTestDriver.test:183 Test case V2AddlFilterTests_SPEC2_20_Event_filter4 failed.`
@yuhai Please take a look at this test. Thanks!

**Other failures are not related:**
modules-integration-mysql57-jdk8/26 more like a flaky.

**Pull request closed without merging**
