### PR TITLE
LPS 184766 Equinox Next 11 9 ServletContextAdaptor

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Create a ServletContextWrapper which delegates to ServletContextAdaptor methods when exists, and to the original ServletContext for the rest
- LPS-X Inline ServletContextAdaptor logic, throw away Proxy related logic
- LPS-X SF, extract method to avoid repeating
- LPS-X Clean up, remove AccessController usages
- LPS-X Apply and SF

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results once the ci-test finishes? Thanks!

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you check the results when the tests complete? Thanks!

**Comment by dantewang** [comment]
@zhangyan0701 The result is out, could you take a look? Thanks!

**Comment by dantewang** [comment]
@111Anna Could you run a startup comparison for this pr? cc @GinsonRen

**Comment by 111Anna** [comment]
@dantewang  I ran the PR on CE and DXP, the test results are normal.
/cc @GinsonRen

**CE:**

Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open Query|Open SQL|Open service tracker|Open bundle tracker |ACTIVE | SATISFIED
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--|--|--
Baseline | 8c0d1c0c |12420.3 | - | 2490 | - | 1408 | 77 | 64 | 96|772|5450|33| 2828|8314
Baseline + PR-2335 | - | 12327 | 0.75% | 2465.3 | 0.98% |  1408| 77| 64 |96| 772|5448|33|2828|8314

**DXP:**

Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open Query|Open SQL|Open service tracker|Open bundle tracker |ACTIVE | SATISFIED
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--|--|--
Baseline | 8c0d1c0c |12793.6| - | 2853.3| - | 1529 | 78 | 64 | 96|838|5902|33|2989 |8992
Baseline + PR-2335 | - | 12823.6 | -0.36% |  2838.6| 0.52% | 1529 |78 | 64 |96|838 |5903|33|3056|8929

**Pull request closed without merging**
