### PR TITLE
LPS-97456 Same for the asset entry, fetching at most once

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @dantewang,

I've applied the same pattern to the asset entry. Can you check if the performance is increased? It was being fetched twice in some cases I think.

Thanks!

**Comment by dantewang** [comment]
@4lejandrito Awesome! Thanks!

cc @slnn

**Comment by slnn** [comment]
Hi all,

Here are test results on Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 83fd0be | 5711 | 118 | 373
pr-1179 | - | 5868 | 94.8 | 330

**Comment by dantewang** [comment]
@slnn Could you run the pull again to double check? Thanks!

**Comment by slnn** [comment]
Hi all,

Here are rerun test results on Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 83fd0be | 5711 | 118 | 373
pr-1179 | - | 5868 | 94.8 | 330
pr-1179 rerun |   | 5987 | 99.2 | 301

**Comment by dantewang** [comment]
@4lejandrito I think it's good to go. Please send to Brian. Thanks!

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75045.

Thanks @dantewang & @slnn!

**Pull request closed without merging**
