### PR TITLE
[Bug Fix] LPS-137608

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please check the solution from LPS-137608's comment.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by dantewang** [comment]
See https://github.com/yuhai/liferay-portal/pull/272, @yuhai please add test coverage as we discussed.
cc @tinatian

**Pull request closed without merging**
