### PR TITLE
Lps 149061 3 15

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang

Compare with the previous pull, new changes in this pull:
Replace all the usage of JSONLocalizer's getJSON(Local) with getJSONObject(local) method

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test

**Comment by dantewang** [comment]
@slnn Sorry but this is not what I meant.

It should be changing

```
public String getJSON(Locale locale) { ...
```

into 

```
public JSONObject getJSON(Locale locale) {...
```

And please don't just add an additional commit at the end when you do this. Just directly change the method, and update the usages.

**Comment by slnn** [comment]
Hi @dantewang 

When the method return a JSONObject, SF requires the method name must end with Object, so I will change the  getJSON method and rename it.

**Comment by dantewang** [comment]
@slnn Yes, if SF requires it, put it in a separate commit. Thanks!

**Comment by slnn** [comment]
OK, got it

**Pull request closed without merging**
