### PR TITLE
LPS-95822

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1612. [See changes here.](https://github.com/dantewang/liferay-portal/compare/b23495df0784~1...b23495df0784)

**Pull request closed without merging**
