### PR TITLE
[Bug Fix] LPS-135355

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the issue can be reproduced. I looked wrong tableName, I thought the table was mdrrulegroup, actually is mdrrulegroupinstance.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Which table did you actually change in second commit? Is it the addition of the marketplace one?

**Comment by yuhai** [comment]
@dantewang, It only lacked marketplace_app table in the second commit, another marketplace_module is good(no datetime column on 6.2 and master).

**Comment by dantewang** [comment]
@yuhai Please write the table name you added to the commit message so that we can know only 1 table is added. Due to source formatting it's hard to see it from the diff.

**Comment by yuhai** [comment]
@dantewang, I just push force the change.

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2354 https://github.com/tinatian/liferay-portal/pull/2355

**Pull request closed without merging**
