### PR TITLE
LPS-87327

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang,

The PR is based on #891 requirement.

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1120. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
