### PR TITLE
Lps 120376 pr 1778 11 2

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn The startup resource action population fix has been merged, could you double check current master? If everything works well I will send this to Tina.

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
This pull worked well on portal side with the head of master

I also test this pull and https://github.com/dantewang/liferay-benchmark-ee/pull/432 on benchmark side, it also worked well

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2031. [See changes here.](https://github.com/dantewang/liferay-portal/compare/1bb34c2a862d~1...1bb34c2a862d)

**Pull request closed without merging**
