### PR TITLE
LPS X CleanUpLog4J

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X Add LogListener to allow for listening to log output without depending on Log4J API
- LPS-X Apply to UpgradeReportLogAppender
- LPS-X Rename
- LPS-X Make status related methods default so optional to implement
- LPS-X Apply to OutputStreamContainerFactoryTrackerImpl; it prints a very simple layout which can be simply concatenated, no need to use PatternLayout.
- LPS-X Update test
- LPS-X Remove dependencies
- LPS-X Auto SF

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by dantewang** [comment]
@catarineaguiar Thanks!

**Pull request closed without merging**
