### PR TITLE
LPS-125170

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I just run the test and it worked for me. Thanks

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relavant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:stop

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2083.

**Pull request closed without merging**
