### PR TITLE
LPS-121111

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I don't fetch https://github.com/dantewang/liferay-portal/pull/1771, if you only add the revert commit, the PR includes it. In addition,  I add the two commit. to the last.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Please rebase this once https://github.com/shuyangzhou/liferay-portal/pull/9515 is merged.

**Comment by yuhai** [comment]
@dantewang, got it.

**Pull request closed without merging**
