### PR TITLE
LPS-129172 Upgrade jackson-databind to 12.2.4

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Some errors seem real. Please double check and resend based on https://github.com/dantewang/liferay-portal/pull/2046 (I only rearranged your commits). @yuhai

**Pull request closed without merging**
