### PR TITLE
LPS-125549 Invoke Log4JUtil to configure module's log

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai This error
```
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.Elasticsearch7#AssertSidecarAutoInstall] STANDARD_ERROR
     [exec]     java.lang.Exception: "Sidecar Elasticsearch liferay started at 127.0.0.1:9201" is not present in console
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.assertTrue(BaseWebDriverImpl.java:4614)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.assertConsoleTextPresent(BaseWebDriverImpl.java:303)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1190)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
```
in relevant seems to be caused by missing Sidecar log? Could you check?

@zhangyan0701 Could you take a look at the ci-test result? Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Locally when I build portal on your pull and start it, I do see the following log:
```
2021-01-15 11:03:31.940 WARN  [main][SidecarManager:111] Liferay automatically starts a child process of Elasticsearch named sidecar for convenient development and demonstration purposes. Do NOT use sidecar in production. Refer to the documentation for details on the limitations of sidecar and instructions on configuring a remote Elasticsearch connection in the Control Panel.
2021-01-15 11:03:39.028 INFO  [main][Sidecar:119] Sidecar Elasticsearch liferay started at 127.0.0.1:9201
```

**Comment by dantewang** [comment]
@yuhai
OK, looking at the console output of the failed Poshi test in relevant run, the major issues are:

1. I can see the `Sidecar` message of `Sidecar Elasticsearch liferay started at 127.0.0.1:9201` but the test can't find it;
2. There should be a `SidecarManager` log as I posted in my previous comment, but it's missing from the console output;
3. I can see both logs when I start this pull on my laptop, even if removing `elasticsearch7` directory to let it auto download.

Please look into this, thanks!

**Comment by dantewang** [comment]
@yuhai The ci-test results show more "expected log not present in console" type of functional test failures when the keywords it asserts can actually be found on the Jenkins page. Maybe it's something related to your change.

**Comment by zhangyan0701** [comment]
Hi @dantewang @yuhai 

Sorry for the late reply, my VPN doesn't work very well today.

The function AssertConsoleTextPresent in Poshi looks console text from the log file of portal which is in liferay.home/logs.

From the Jenkins results, looks like the portal log file is empty, that's why all tests that needs to assert console text failed.

Example:
https://testray.liferay.com/home/-/testray/case_results/1418310569
https://testray.liferay.com/home/-/testray/case_results/1418330455

The link Liferay Application Log will open an empty page.

I don't think this is a Jenkins issue, because it only happened in this PR. 

Could you take a look?

**Comment by dantewang** [comment]
@zhangyan0701 Thanks! That makes sense! @yuhai Then this is a real error. Maybe it's an appender issue. Please double check.

**Pull request closed without merging**
