### PR TITLE
LPS-110758 Remove portlet sandbox

### PR DESCRIPTION
**Pull request by yuhai**
Hi @dantewang,

I add the below commits:
1. https://github.com/dantewang/liferay-portal/commit/f675548520e551366629a2084daa4ff13d9c3202, solve Tina said usage.
2. https://github.com/dantewang/liferay-portal/commit/f57346b1d5759a17646f07b057973ea954b7c365, if it is good for you, please help merge it to the previous commit.
3. The rest commits move the two modules to archived folder.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Can you resend a pull and just remove the two modules? They are not even built with ant all in the past. On the other hand, just merge your https://github.com/dantewang/liferay-portal/commit/f675548520e551366629a2084daa4ff13d9c3202 into https://github.com/dantewang/liferay-portal/pull/1575/commits/ebddb49fdf4318a57a52ecbc822a808cf24b960a.

**Comment by dantewang** [comment]
@yuhai Also I don't think you need to deprecate the two methods in https://github.com/dantewang/liferay-portal/pull/1575/commits/f57346b1d5759a17646f07b057973ea954b7c365. The whole intraband is pending deprecation after this pull gets merged. Let's just deprecate the class then.

**Pull request closed without merging**
