### PR TITLE
LPS-103951 Clean up used deprecations from portal-kernel part3

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@ChiZelin I excluded your commit https://github.com/dantewang/liferay-portal/pull/1374/commits/221cb4bdcbe20b59f27fb30be242341739d10605

I found a usage of this in a `.vm` file (Velocity template). Please double check it carefully.

Failures in CI result are real. I made changes and sent to Tina, please see https://github.com/tinatian/liferay-portal/pull/1580

**Pull request closed without merging**
