### PR TITLE
Lps 120376 11 18

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@slnn There's a problem with your solution. You will only be able to pass one of the files (the first one that exists by the order of `<property>`) to SampleSQLBuilder.

If we keep the overriding defined in build-common.xml, we need to take it into consideration that the user may have more than one of the overrides defined. For example, my hostname is `dante-pc` and my username is `dante` so I can have `benchmarks.dante.properties` and `benchmarks.dante-pc.properties` at the same time, with some properties overriden in one of the files and some in the other. Your current solution will not be able to handle this.

That's why I mentioned
> To keep the overriding support, we'll either
> - make SampleSQLBuilder support reading from multiple properties files
> - generate a temp properties file from Ant context and feed it to SampleSQLBuilder.
in the comment of the previous pull to Tina.

I think it's easier to do 2 as it will only need to modify the build.xml -- just like how we generate `grinder.properties` in benchmark project.

**Comment by slnn** [comment]
Hi @dantewang 

All these property files described in portal's build-common.xml can not exist at the same time, the usage of these property file should be like this:
the default one:benchmarks.properties
the custom one to override the properties: benchmarks.${user.name}.properties or benchmarks.${env.COMPUTERNAME}.properties or benchmarks.${env.HOST}.properties or benchmarks.${env.HOSTNAME}.properties
       
by the way, ${env.COMPUTERNAME} this one is normally works with Windows.


> <property file="${project.dir}/benchmarks/benchmarks.${user.name}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.${env.COMPUTERNAME}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.${env.HOST}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.${env.HOSTNAME}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.properties" />

**Comment by dantewang** [comment]
@slnn If you look at the files in the portal repo after `setup-profile-dxp` you will see `build.profile-dxp.properties`; and you may also have your `build.yourusername.properties`. The properties in `build.profile-dxp.properties` overrides everything else.

```
	<property file="${project.dir}/build.profile-dxp.properties" />
	<property file="${project.dir}/build.${user.name}.properties" />
	<property file="${project.dir}/build.${env.COMPUTERNAME}.properties" />
	<property file="${project.dir}/build.${env.HOST}.properties" />
	<property file="${project.dir}/build.${env.HOSTNAME}.properties" />
	<property file="${project.dir}/build.properties" />
```

These files can exist at the same time, why don't `benchmark.*.properties`?

**Comment by dantewang** [comment]
@slnn I mean this feature is definitely supported by Ant itself. As long as we allow it, there can be users who create multiple files to set properties. If users use this way to designate overriding properties files, we must ensure that the final result SampleSQLBuilder reads matches what is in Ant's context.

**Comment by slnn** [comment]
Hi @dantewang 

I got your point, you want to handle when the user may have more than one of the overrides defined, I will try to add this support,  I have some questions about merge properties:
For example: 

If user has these property files at the same time
1>benchmarks.${env.COMPUTERNAME}.properties, it contains these properties:
properties-name-a= 1
properties-name-b= 2
properties-name-c= 3
2>benchmarks.${env.HOST}.properties, it contains these properties:
properties-name-a= 1
properties-name-b= 2
properties-name-c= 3

How do we should handle the property "properties-name-c"?

**Comment by slnn** [comment]
On the other hand, if we make SampleSQLBuilder support reading from multiple properties files, when user passes two property files(benchmarks.${env.COMPUTERNAME}.properties and benchmarks.${env.HOST}.properties), SampleSQLBuilder should generate two outputs or we still need to merge the property files?

**Comment by slnn** [comment]
@dantewang I update my previous comment:
https://github.com/dantewang/liferay-portal/pull/1802#issuecomment-730175894

**Comment by slnn** [comment]
From the origin description in the benchmarks.properties file, it described the property file usage is just adding 
 benchmarks.${user.name}.properties with the properties to overwrite

 

> DO NOT EDIT THIS FILE.
>  To update the properties of this file, create a separate properties file
>  named "benchmarks.${user.name}.properties" with the properties to overwrite.


And in the build-common.xml, the order is like this, the benchmarks.${user.name}.properties has the highest priority:

> <property file="${project.dir}/benchmarks/benchmarks.${user.name}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.${env.COMPUTERNAME}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.${env.HOST}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.${env.HOSTNAME}.properties" />
	<property file="${project.dir}/benchmarks/benchmarks.properties" />

**Comment by dantewang** [comment]
@slnn With the `build-common.xml` way which defines multiple properties files to read:
1. properties that are read first take effect (which is by Ant's design, and should resolve [your comment](https://github.com/dantewang/liferay-portal/pull/1802#issuecomment-730175894))
2. if you want to support multiple files in SampleSQLBuilder, the properties should be merged, but you must make sure the properties that take effect are the same with Ant's
3. so I think "generate a temp properties file from properties read into Ant context" way is simpler, but both ways should be possible to implement.

**Comment by slnn** [comment]
Hi @dantewang 

The order in portal's build-common.xml is this:

<property file="${project.dir}/benchmarks/benchmarks.${user.name}.properties" />
<property file="${project.dir}/benchmarks/benchmarks.${env.COMPUTERNAME}.properties" />
<property file="${project.dir}/benchmarks/benchmarks.${env.HOST}.properties" />
<property file="${project.dir}/benchmarks/benchmarks.${env.HOSTNAME}.properties" />
<property file="${project.dir}/benchmarks/benchmarks.properties" />

so if benchmarks.${user.name}.properties and benchmarks.${env.COMPUTERNAME}.properties exist at the same time, I should make SampleSQLBuilder use the property file which has a high priority like benchmarks.${user.name}.properties in here, right?

**Comment by dantewang** [comment]
@slnn Yes, which appears earlier in build-common.xml has higher priority. So you want to merge the properties files in SampleSQLBuilder?

**Comment by slnn** [comment]
I think we can do it in the build.xml

**Comment by slnn** [comment]
Hi @dantewang 

I think my changes in this pull can do it, if

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1807

**Pull request closed without merging**
