### PR TITLE
test delete unused reference

### PR DESCRIPTION
**Pull request by JanisZhang**
@dantewang

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:etst:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you please help to scan the test results? thx.

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions.

**Comment by dantewang** [comment]
@JanisZhang I think there's an issue with your commit message. In https://github.com/dantewang/liferay-portal/pull/2260/commits/aace1564c572cea75571a4822ef147cd344dee3e the message says the usages were removed in https://github.com/JanisZhang/liferay-portal/commit/792b40a3dfbbd6a89347f38e724fccbdb863f984, but https://github.com/JanisZhang/liferay-portal/commit/792b40a3dfbbd6a89347f38e724fccbdb863f984 was to add this `UserModelListener`. The listener was added with these two unused references. Why do you think the usages are removed in that commit?

**Comment by JanisZhang** [comment]
Hi @dantewang, I just found this problem, by looking into the git history, it shows the reference is removed, then I copy the version number to the commit message.
I don't know why it shows this file was added. 

image

**Comment by dantewang** [comment]
@JanisZhang This is strange. On my local it shows that `UserModelListener` was added in this commit, not renamed as in your screenshot. `gitk` also shows the same history.

**Comment by JanisZhang** [comment]
@dantewang After I click `resume git log Indexing` it seems consistent with the gitk history, I will review my commit message. but it's weird the commit message says Delete xxxxx but actually added a file...

**Comment by dantewang** [comment]
@JanisZhang I think the commit message says what the `UserModelListener` does (deleting something when deleting user), not about the file creation/deletion.

**Pull request closed without merging**
