### PR TITLE
LPS-118542

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/dantewang/liferay-portal/pull/1891. I only tested integration test in my test pr from https://github.com/yuhai/liferay-portal/pull/246 and worked. Please see the whole ci:test result in this pr.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1893. [See changes here.](https://github.com/dantewang/liferay-portal/compare/d1290b21b75d~6...d1290b21b75d)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1894. [See changes here.](https://github.com/dantewang/liferay-portal/compare/3e5a74027fbf~7...3e5a74027fbf)

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2116. [See changes here.](https://github.com/dantewang/liferay-portal/compare/1d433651ad5d~12...1d433651ad5d)

**Pull request closed without merging**
