### PR TITLE
LPS-106612 Patch bcmail.jar and bcprov.jar to fix warnings when starting JBoss or wildfly

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/1672. [See changes here.](https://github.com/dantewang/liferay-portal/compare/43a4d1020083~2...43a4d1020083)

**Pull request closed without merging**
